### ISSUE TITLE
We should save all OTR fingerprints we have ever seen

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#102]
And warn if they change

**Comment by tdruiva** [comment]
This is the same as issue #79?

**Comment by juniorz** [comment]
Nope. #79 is about server fingerprints. This is about contacts fingerprints.

**Comment by juniorz** [comment]
Is it worth having a "fingerprint manager" we can use to manage contacts fingerprints?

**Comment by olabini** [comment]
It's not high on my list of priorities, but yeah, might be good.

**Comment by olabini** [comment]
This has been done.
