### ISSUE TITLE
The protocol goes crazy if you keep flooding before the AKE finishes.

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#103]
I was talking with another account using Adium. The first message I send is stored, then the AKE starts. Then I keep sending unencrypted messages while the AKE is in progress (because I have no idea what is happening behind the scenes) and the protocol goes crazy.

At some point, I start receiving warnings about messages with wrong counter. I can't continue with the conversation unless I click "END OTR" and the other peer does the same.

**Comment by olabini** [comment]
This is a duplicate.
