### ISSUE TITLE
Unable to lock Fedora if menu is displaing

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#104]
![img_20151028_175041](https://cloud.githubusercontent.com/assets/1254745/10805822/c3151a32-7d9e-11e5-8f85-70d353d1ba2f.jpg)

**Comment by tdruiva** [comment]
My log:

Oct 28 18:43:01 localhost.localdomain gnome-session[2300]: Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed
Oct 28 18:43:01 localhost.localdomain gnome-session[2300]: Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed
Oct 28 18:43:01 localhost.localdomain gnome-session[2300]: Gjs-Message: JS LOG: error: Unable to lock: Lock was blocked by an application

**Comment by juniorz** [comment]
This is on Gnome, isn't it?

**Comment by tdruiva** [comment]
@juniorz yeap

**Comment by juniorz** [comment]
I mean, if this is a bug is a bug on Gnome.

**Comment by tdruiva** [comment]
@juniorz yep :disappointed: 
I was able to reproduce the same thing with other applications like Gimp and the terminal.
I'm jumping in their mail list to see if someone have idea...

**Comment by olabini** [comment]
Yeah, in general if a menu is open that blocks a bunch of stuff in Gnome. I think we will have to say "NOFIX" on this one.

**Comment by tdruiva** [comment]
:(
