### ISSUE TITLE
Setup something on the domain coy.im

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#11]
Github pages?

**Comment by tcz001** [comment]
coming *soon* ;P

**Comment by tcz001** [comment]
We can also provide coy.im as a jabber server if we want. 
And in the other hand we can also provide a practice-proved "Security as Default" configuration.

**Comment by olabini** [comment]
I want to wait with setting up a jabber server. Or well, we should set one up for us immediately. But setting up an open server is a major undertaking that I don't think we should do right now.

**Comment by tcz001** [comment]
Tania and I already setup a CAed xmpp.torchz.net:5222 for test.

**Comment by olabini** [comment]
Yeah, I know. =)

**Comment by olabini** [comment]
We now have a cert, so just need some content!

**Comment by tcz001** [comment]
We have it https://Coy.IM, we can add more details later, so close this issue.

**Comment by tdruiva** [comment]
\o/
