### ISSUE TITLE
We should support regular Pinging

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#110]
https://xmpp.org/extensions/xep-0199.html - in order to test our connection, potentially?

**Comment by juniorz** [comment]
We receive whitespace pings (https://xmpp.org/rfcs/rfc6120.html#xml-whitespace) from server. We can also use this.

**Comment by juniorz** [comment]
We only need to determine the disconnect strategy for Pings as well as the interval and timeout for keepalives and pings.

The spec suggests intervals of 5 minutes, but it feels too long. We are in the range of seconds, but it feels too short.
