### ISSUE TITLE
It takes a LONG time for CoyIM to recognize that we lost connections

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#112]
This can potentially be solved with #110

**Comment by juniorz** [comment]
May it be related to how Tor handles timeouts and/or closed sockets on its circuits?
For me, it feels like the golang `net.Conn` takes too long to know it has disconnected/timed out.

**Comment by olabini** [comment]
Yeah, maybe. We probably need to investigate closer what the right approach is here, either by using pings or by using shorter timeouts - or a combination.

**Comment by juniorz** [comment]
By the way, the `net.DialTimeout` is missing on the `proxy.Dialer`
interface :S

On 11/4/15 12:30 PM, Ola Bini wrote:
> Yeah, maybe. We probably need to investigate closer what the right
> approach is here, either by using pings or by using shorter timeouts -
> or a combination.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twstrike/coyim/issues/112#issuecomment-153801006>.
> 

-- 
*Reinaldo de Souza Jr* | Software Developer
*Thought*Works Brasil

EF84 6530 67A5 1559 5554 D8B2 954A 6BEF AF74 ACD7

**Comment by juniorz** [comment]
I suspect this is also related to how `net.Conn` works:

> A deadline is an absolute time after which I/O operations fail with a timeout (see type Error) instead of blocking. The deadline applies to all future I/O, not just the immediately following call to Read or Write.
An idle timeout can be implemented by repeatedly extending the deadline after successful Read or Write calls.

See Conn#SetDeadline https://golang.org/pkg/net/#Conn

I want to try to wrap the connection passed to `makeInOut()` with something that "repeatedly extends the deadline after successful Read or Write calls". I'm still searching is something like this is available on the stdlib.

**Comment by juniorz** [comment]
By playing with `SetReadDeadline` and `SetWriteDeadline`, I was able to make it work as expected. The problem seems to require more changes than simply making the connection to timeout.

The `xmpp.Conn#Next` blocks while waits for the next XML token, so I don't think we can't timeout on reads. Any alternative?

This is the related stacktrace:

```
/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 (0x4325e0c)
	(*block).readFromUntil: m, err := r.Read(b.data[len(b.data):cap(b.data)])
/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 (0x4326511)
	(*Conn).readRecord: if err := b.readFromUntil(c.conn, recordHeaderLen); err != nil {
/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 (0x432a907)
	(*Conn).Read: if err := c.readRecord(recordTypeApplicationData); err != nil {
/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 (0x428db59)
	(*Reader).fill: n, err := b.rd.Read(b.buf[b.w:])
/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:229 (0x428e3ca)
	(*Reader).ReadByte: b.fill() // buffer is empty
/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:861 (0x439ad6d)
	(*Decoder).getc: b, d.err = d.r.ReadByte()
/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:512 (0x43971f8)
	(*Decoder).rawToken: b, ok := d.getc()
/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:247 (0x4395223)
	(*Decoder).Token: } else if t, err = d.rawToken(); err != nil {
/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:40 (0x41ef5ec)
	nextStart: t, err := p.Token()
/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:56 (0x41ef81d)
	next: se, err := nextStart(c.in)
/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/connection.go:60 (0x41de5ab)
	(*Conn).Next: if stanza.Name, stanza.Value, err = next(c); err != nil {
/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:111 (0x41ad7c1)
	(*Session).readMessages: stanza, err := s.Conn.Next()
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 (0x4072051)
```

**Comment by olabini** [comment]
As mentioned in the issue body text, we should implement #110 to solve this, combined with the approach you've detailed here.

**Comment by juniorz** [comment]
For further reference, XEP-0198 could be used together with ping to detect (and resume) dead connections.

See: https://www.ejabberd.im/faq/tcp

**Comment by juniorz** [comment]
We should also make sure we handle every case mentioned in the RFC: https://xmpp.org/rfcs/rfc6120.html#streams-silence

**Comment by juniorz** [comment]
After implementing whitespace keep-alive. I ran the following test on Mac, sending keep-alive every 10 seconds with a 30 seconds timeout.

Without Tor, I got write timeouts for keep-alives  in the range of 1-3 minutes after I turned my wifi off.
With Tor, it took ~4 minutes to receive the first timeout after disconnecting from network.

Tor log mentions:

```
Nov 18 11:42:16.000 [notice] No circuits are opened. Relaxed timeout for circuit 107 (a General-purpose client 3-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway. 13 guards are live.
Nov 18 11:42:17.000 [notice] Tor has not observed any network activity for the past 231 seconds. Disabling circuit build timeout recording.
```

**Comment by olabini** [comment]
Hmm. that's a long time. I wonder how Gajim does it - it notices the disconnect much faster than that.

**Comment by xSmurf** [comment]
Gajim supports XEP-0198 and works really well for that purpose (it's precisely what it is for). Much better tan 0199 in my experience, I would highly recommend it.
