### ISSUE TITLE
Support notifications

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#113]
I do think notification support is necessary for an IM client.

**Comment by olabini** [comment]
Specifically, I mean notifications in the user interface outside of the application

**Comment by 0xPoly** [comment]
Hello. I would like to hack a bit on coyim. Would using https://github.com/0xAX/notificator be the correct approach to adding notification support?

**Comment by olabini** [comment]
Hi, the first step for implementing notifications is to implement full support for GtkApplication in gotk3, and then convert CoyIM to use GtkApplication - this can be seen in #164

**Comment by tcz001** [comment]
I don't think 0xAX/notificator is a good choice, since it's just a command wrapper, and growlnotify is not free and not opensource :)

**Comment by 0xPoly** [comment]
Plus, it seems 0xAX/notificator doesn't work on on MacOS or Windows...

https://github.com/0xAX/notificator/issues/5
https://github.com/0xAX/notificator/issues/4

**Comment by olabini** [comment]
So, the current status is this: we have support for the GLib Notification support in gotk3 - for some reason it doesn't work. GtkApplication has also been implemented and is now inside Coy. In order to make progress we need to understand why the GLib Notification support doesn't work - fix that, and then see if we can get those working on Mac and Windows as well.

**Comment by olabini** [comment]
Using this https://launchpad.net/go-dbus package, it's possible to get notifications to show up on Gnome, but it's a large package - I'm a bit uncomfortable merging it before understanding why GLib Notification doesn't work.

**Comment by chelseakomlo** [comment]
Because #164 is now closed, what remains to be done for this issue?

**Comment by olabini** [comment]
Did you read the two previous comments from me?

**Comment by chelseakomlo** [comment]
Nope. But I have now :)

**Comment by juniorz** [comment]
I've found some "how do I" docs about notifications and DBUS:

https://wiki.gnome.org/HowDoI/GNotification
https://wiki.gnome.org/HowDoI/DBusApplicationLaunching

**Comment by xSmurf** [comment]
Tentative linux only, dbus based supported added in #305

**Comment by olabini** [comment]
I've merged the PR - it's a great first step!

**Comment by olabini** [comment]
Here are some TODOs, based on the ones in the PR:
- [ ] Clicking notifications should bring up the associated conversation view
- [ ] Notifications should be updated when possible
- [ ] Settings for allowing fullscreen and showing the message (leaks on dbus! - obviously)
- [ ] Support OS X
- [ ] Support Windows

**Comment by olabini** [comment]
A related thing is to maybe make a noise or something when a message arrives

**Comment by xSmurf** [comment]
- [ ] Notifications should be updated when possible

Making a sound is possible via the Freedesktop notifications as well and very easy to add with this one liner:

```
hints[notify.HintSoundName] = "message-new-instant"
```

Should I add it before #315 is merged?

**Comment by olabini** [comment]
So in order to support OS X there seems to be two choices
- Use osascript to display a notification. This is fairly easy, but we need to be very careful to clean up the arguments. Biggest downside is the ugly icon that we can't change.
- This library https://github.com/deckarep/gosx-notifier

**Comment by fin** [comment]
i saw notificationCommand in the v0.3.4 settings box, am i right in assuming that the notificationCommand field is unused as of current master?

(i did a cursory code search and nothing but settings dialog stuff popped up)

**Comment by olabini** [comment]
the notificationCommand does work if you set it to something. It will set the configuration option NotifyCommand which is triggered in session/session.go:649.

**Comment by fin** [comment]
thanks! (github search omitted a few instances).

it just … doesn't seem to work on OSX. neither by entering the command directly, nor by creating a `/Users/fin/bin/notifyCoy` and entering `/Users/fin/bin/notifyCoy` in the NotifyCommand box.

Debug Log does not contain anything remotely related as well. I'll try to compile manually, add debug statements and report back over the weekend.

**Comment by olabini** [comment]
I've finally started work on this for OS X - I'm using a fork of gosx-notifier where I've verified the embedded binary is correct.

**Comment by olabini** [comment]
OK, notification support for OS X is finally working! Only Windows to go. @tcz001 - any thoughts?

**Comment by tcz001** [comment]
Cool, for windows there are two options at least, windows10 has a toast-notification as I know, and for the older versions we may need some window popups by the application...

**Comment by fin** [comment]
@olabini thank you, can confirm this works on 10.11.6 with freshly brewed go and gtk3

**Comment by olabini** [comment]
Thanks for the beedback @fin!

**Comment by tcz001** [comment]
I'm closing this because windows toast notification is implemented, the remaining work can be "invoking coyim from notifications", which requires a whole process of registry application and provide a installer to create shorticon on start and status icon bar.
