### ISSUE TITLE
Pango system conf directory env makes text render failing on my mac

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#114]
<img width="456" alt="2015-11-04 14 02 17" src="https://cloud.githubusercontent.com/assets/1702340/10948705/f27e4d44-82fc-11e5-8dbb-f410ce050d9f.png">

**Comment by juniorz** [comment]
It makes me wonder what is the consequence of this and why would it be necessary.

Looking to our first bundle generated by `gtk-mac-bundler` (), this directory had:

```
Contents/Resources/etc % tree
.
└── gtk-3.0
    └── gtk.immodules

1 directory, 1 file
Contents/Resources/etc %
```

This is the commit that introduced this variable into pango: https://mail.gnome.org/archives/commits-list/2010-July/msg01976.html

**Comment by juniorz** [comment]
I suspect the problem is that `gtk.imodules` contains wrong paths.

It currently has:

```
"/usr/local/Cellar/gtk+3/3.18.2/lib/gtk-3.0/3.0.0/immodules/im-viqr.so"
"viqr" "Vietnamese (VIQR)" "gtk30" "/usr/local/Cellar/gtk+3/3.18.2/share/locale" "vi"
```

But it should have:

```
"@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-viqr.so"
"viqr" "Vietnamese (VIQR)" "gtk30" "/usr/local/Cellar/gtk+3/3.18.2/share/locale" "vi"
```

**Comment by tcz001** [comment]
I think this is a pango version problem, after upgrade I can't reproduce this. so close for now
