### ISSUE TITLE
We should make sure messages are tagged no-store and no-copy

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#115]
XEP-0334

**Comment by juniorz** [comment]
We already support Google "Off the Record Chats" extension[1] and XEP-0136[2]. We are unsure if servers will support XEP-0334 (or XEP-0313) and we don't know how to verify if this change will ever be effective.

This[3] list XEP related to archiving implemented by prosody implements. `otr.im` claims to use prosody and we suspect `riseup-net` also uses it (otr.im webpage mentions they worked together to implement a prosody plugin to make OTR mandatory).

This list does not mention XEP-0334.

1 - https://developers.google.com/talk/jep_extensions/otr
2 - https://xmpp.org/extensions/xep-0136.html
3 - https://prosody.im/doc/archiving

**Comment by iapazmino** [comment]
I asked at the OTR channel about servers that implement XEP-0334 and the answer was that it is not usually implemented. The usually implemented extension for archiving, they said, is XEP-313.

**Comment by olabini** [comment]
Hm, I haven't really seen any of those xep's supported very often, so I think we should just close this.

**Comment by tcz001** [comment]
What?! As I remember at least Openfire and ejabberd has XEP-0334
