### ISSUE TITLE
Roster duplicated

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#121]
I don't have idea how I did it...
I just added riseup account one time.

![screenshot from 2015-11-10 14-12-31](https://cloud.githubusercontent.com/assets/1254745/11067948/2ee7826a-87b6-11e5-8d31-b7ca3cf6f5e8.png)
![screenshot from 2015-11-10 14-12-46](https://cloud.githubusercontent.com/assets/1254745/11067947/2ee79872-87b6-11e5-80c0-14f56cdde634.png)

**Comment by olabini** [comment]
This happened again to me, when I imported an account. Not sure how - I looked through the code and can't find a good explanation =/

**Comment by juniorz** [comment]
I suspect of `roster#update()`. The duplication could happen there if we have multiple `*account` for the same `config.Account`. I still haven't found how this could be possible.

**Comment by tcz001** [comment]
I can reproduce this easily by adding an existing account, the ui becomes crazy in this case

**Comment by tcz001** [comment]
another case: disable all the auto connecting, don't merge accounts, add a new account, and connect it manually, the duplicate appears

**Comment by tcz001** [comment]
fixed by f3deeba3dab3415d7f97c482516057b8083e8691 and c5345bcc5df31a792e9a3857b938ead15b6baed0

**Comment by tcz001** [comment]
and b667535ebedfbd7f6b5567d6a3a82def16dc6873
