### ISSUE TITLE
Feedback on presence errors

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#122]
After adding a `@gmail.com` contact to my `@dukgo.com` account and I got a presence error every time I login:

```
&{{jabber:client error}  cancel {urn:ietf:params:xml:ns:xmpp-stanzas remote-server-not-found} Server-to-server connection failed: Encrypted server-to-server communication is required but was not offered}
```

**Comment by juniorz** [comment]
Same thing happens with a contact managed by "Google for Business".

**Comment by olabini** [comment]
What should be the right behavior here? I've seen it too, btw. Should we remove the contact? Give feedback once, and then remember to not do it again?

**Comment by olabini** [comment]
Still not clear on what the right behavior is. Since the problem is server-to-server communication, there might not be much we can do.

**Comment by olabini** [comment]
There are a few circumstances where this happens. I have stuck the information into roster.Peer right now, but we don't really expose it in the UI. AFAICT other apps don't really show this to the user either.
