### ISSUE TITLE
Fix icons on Mac

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#126]
To view icons I have to `export XDG_DATA_DIRS="$(brew --prefix gnome-icon-theme)/share"` before running `coy`.

I also noticed that after upgrading GTK from `2.24.28` to `2.24.28_3` the spinner stopped working because the icon name has changed:

```
(CoyIM:12470): Gtk-WARNING **: Could not find the icon 'process-working-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
```

We need to keep in mind the app bundle generation could break unless we make sure the correct versions are used.

**Comment by juniorz** [comment]
The spinner is still not working on the Mac Bundle :S

**Comment by tdruiva** [comment]
Ouch!

**Comment by olabini** [comment]
We are not using the spinner anymore. Does everything else look OK?

**Comment by juniorz** [comment]
We must double check the menu arrows using the app bundle on a fresh Mac. I
have a spare Mac here to test.
Em 12/01/2016 6:13 PM, "Ola Bini" <notifications@github.com> escreveu:

**Comment by aepsil0n** [comment]
I'm having a similar issue on a MacBook running ArchLinux… the icon size is roughly half of what i guess it should be. I'm having this issue with a lot of applications though, so maybe the error is on the side of my configuration. What do you use for the GUI?

**Comment by olabini** [comment]
that sounds like a different problem than the one we have here.
Your problem seems to be that GTK is tricky on a retina display. Try setting:
  export GDK_SCALE=2
  export GDK_DPI_SCALE=0.5

**Comment by aepsil0n** [comment]
now i'm getting a different issue… let me detail that in a separate issue

**Comment by olabini** [comment]
@juniorz ping

**Comment by olabini** [comment]
Is this still a problem, @juniorz?

**Comment by juniorz** [comment]
I've just tested on a fresh Mac OS. Closing.
