### ISSUE TITLE
Can't load previous encrypted conf with tag -config-file after restart

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#130]
This doesn't happen when we use the default config file path.

**Comment by juniorz** [comment]
I start the app pointing to a non-existing config file:

`coyim -debug -config-file ~/strike-test-conf-aa.enc`

I reply "yes" to encrypt the file and I create a new account. The file fails to save with the error:

> [CoyIM] 2015/11/16 11:52:18 /Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:195: Failed to save config file: rename /Users/rjunior/strike-test-conf-aa.enc.000~ /Users/rjunior/strike-test-conf-aa.enc: no such file or directory

**Comment by tcz001** [comment]
The reason why encrypted file can't be reloaded by -config-file param is because we are using the suffix ".enc" as mandatory to indicate a.ShouldEncrypt, in this case adds a -config-file-enc maybe a workaround, but I would propose it's better to have this config field in file not using a suffix.

**Comment by tcz001** [comment]
I think it's fixed by dcdb7eb and f1807ed
