### ISSUE TITLE
Fix fonts on Mac

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#134]
The fonts look terrible on Mac after GTK 3.16, but they look great from 3.10 to 3.14.

**Comment by juniorz** [comment]
Idea: Look at which 3.16 this is broken: https://download.gnome.org/sources/gtk+/3.16/

**Comment by juniorz** [comment]
The problem is on GTK 3.16.5.

I'll start by looking at these tickets:

```
Overview of changes in GTK+ 3.16.5
==================================

* Bug fixes:
 750489 gtk settings c910 warning unexpected annotation element type command
 750605 icontheme: don't modify symbolic SVG dimensions when recoloring
 750690 Recent Chooser Widget doesn't expand
 750718 Improve documentation for deprecated properties
 750870 gtk3 does apparently ignore replayed events?
 750888 Fix return value error in _gtk_text_handle_set_direction
 750994 X11: First mouse wheel event ignored after right click or Alt+Tab...
 751018 Widget: GtkMenuButton+GtkPopover gtk_toggle_button_set_active() n...
 751050 Moving the mouse while a stepper is activated causes the scrollba...
 751082 GtkTreeView draw performance is bad when contents are not larger ...
 751227 file picker list box height stretches to match extra widgets area...
 751443 resource_path value cleared in gtk_image_set_from_resource
 751739 Deadlock in X11 when setting XSetErrorHandler while another threa...
 751752 Memleak when both opening shm and opening file in tmp fail
 751754 GtkSwitch: calling gtk_switch_set_active in the handler for notif...
        Fix ridge/groove border rendering
        GtkListBoxRow: propagate in the draw vfunc
```

**Comment by juniorz** [comment]
For reference, this is how it looks on 3.16.4

<img width="365" alt="roster-gtk 3-316-4" src="https://cloud.githubusercontent.com/assets/30809/11271182/650ce55a-8e92-11e5-8538-6b62cca732a6.png">

And this is how it looks on 3.16.5

<img width="365" alt="roster-gtk 3-316-5" src="https://cloud.githubusercontent.com/assets/30809/11271188/69723e4c-8e92-11e5-928a-dc48cb2d7ac6.png">

**Comment by juniorz** [comment]
GNOME bugzilla ticket: https://bugzilla.gnome.org/show_bug.cgi?id=758338

**Comment by olabini** [comment]
Nice!

**Comment by juniorz** [comment]
Should be fixed now: https://bugzilla.gnome.org/show_bug.cgi?id=710501#c15

We need to test when next version is released.
