### ISSUE TITLE
User Flow - Verify Fingerprint - Change verify fingerprint window after it been verified

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#139]
After verify fingerprint, in our currently implementation, if you open the window again looks like the fingerprint wasn't verified

**Comment by juniorz** [comment]
We are currently only warning if something is wrong, like when the fingerprint is not verified.

Are we supposed to add some "green light" on the window to signal everything is right? Also, isn't this part of #95?

**Comment by tdruiva** [comment]
What I mean is, if I had verified your fpr and click on `Verify fingerprint`, the window that displays looks like I haven't verified

![screenshot from 2015-12-16 16-49-56](https://cloud.githubusercontent.com/assets/1254745/11854980/53cb1eb8-a415-11e5-8673-d04b878c650b.png)

**Comment by juniorz** [comment]
Should it? You ask to verify and it says what you need to verify. ;)

Also, I suspect the only way you will see this is by choosing the action
from the "Developer menu" - which is supposed to be removed.

**Comment by olabini** [comment]
This all ties in to the main "security" feedback flow, that we haven't started on yet, things like #32

**Comment by olabini** [comment]
Since this feature doesn't match with our plans, I'll close this issue.
