### ISSUE TITLE
Turn on configuration file encryption after setup

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#147]
I think would be very nice if we have an option to encrypt latter, if user decided not to encrypt when use CoyIM for the first time

**Comment by tcz001** [comment]
and maybe vise versa?

**Comment by olabini** [comment]
Yeah, that would be nice - however, it might be the case that once you've put it on disk unencrypted, you don't get so much security from later encrypting it. Thoughts?

**Comment by tcz001** [comment]
So, I'm starting to think about if unencrypted config is necessary in our target market, it's like people are using a keepass but not encrypting the most important password...

**Comment by olabini** [comment]
Well, some people will want to edit the file. And requiring a password on every startup is a big enough burden that a lot of people will be turned off by it. And if you have an encrypted harddrive, it might be enough. It really depends on your threat model.

**Comment by olabini** [comment]
I think we should provide advanced options for moving to unencrypted mode and to encrypted mode. It's not high on my priority list right now though.
