### ISSUE TITLE
Roster is not displayed in some cases.

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#151]
The `Session` handles timeout for IQ requests. In some cases, the roster request times out, and the roster is never displayed. We could retry the request if this happens, or we could periodically request the roster list anyways (I remember having seen this on Pidgin).

**Comment by olabini** [comment]
I couldn't find how the roster request ever could time out.  However, I've added a period re-request of the roster list.

**Comment by juniorz** [comment]
The `Session` times out the IQ if they are not replied after some time, and also closes the reply channel. I don't remember having experienced it tough (no `session: roster request cancelled or timedout` message).

**Comment by olabini** [comment]
Where does it happen? As far as I can tell, there is nothing that actually does that, unless the underlying connection is closed.

**Comment by olabini** [comment]
That error message happens if the "inflights" channel is closed, but afaict that can't happen without closing the connection - and in that case we shouldn't re-request the roster, right?

**Comment by juniorz** [comment]
The inflight (response) channel is closed when the roster request is canceled (`Conn#Cancel()`) and it also happens on timeout (see `Session#watchTimeout()`).

However, it seems you need to explicitly set a timeout using `Session#Timeout()`, so I'm convinced this is not the case.

**Comment by juniorz** [comment]
And it brings the questions:

- Should we add a timeout to this `RequestRoster` to prevent it from indefinitely blocking `watchRoster`?
- Should we add timeout to any other request?

**Comment by olabini** [comment]
Hmmmmmmmmmmmm. We can continue thinking about it. I haven't really seen these problems so far at least.
