### ISSUE TITLE
User Flow - Setup User Account - Duplicate dialog

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#153]
- Configure an account without saving the password
- Click to connect this account
- Don't type the pass and don't close the pass dialog
- Add a new account
- Previous password dialog will duplicate

**Comment by tcz001** [comment]
I guess this is related to the issue https://github.com/twstrike/coyim/issues/121

**Comment by tcz001** [comment]
And since that's fixed, probably this is fixed also, @tdruiva , can you please confirm again, I can't reproduce anymore.
