### ISSUE TITLE
User Flow - Setup User Account - Not saving account

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#155]
- CoyIM is encrypted
- Open it
- Add new account
- Close CoyIM
- Open CoyIM again

The account is not been saved :cry:

**Comment by tcz001** [comment]
I guess It probably because of saving encrypted taking long time, and the UI don't wait untill it finishes.

**Comment by tdruiva** [comment]
> I guess It probably because of saving encrypted taking long time

I'm not sure if this is the real reason 'cause I added an account and waited 2 minutes before to close CoyIM and still not saving...

**Comment by olabini** [comment]
That seems wrong... =(

**Comment by olabini** [comment]
The key generation from the password takes 200-500ms, and the encryption is WAY faster than that, since we don't have any asymmetric operations.

**Comment by tdruiva** [comment]
Tks man!
