### ISSUE TITLE
Implement X-OAUTH2 mechanism for SASL

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#159]
This is simple. We need to send the user to the URL `https://accounts.google.com/o/oauth2/auth?response_type=code&scope=https://www.googleapis.com/auth/googletalk&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=OURCLIENTID& login_hint=JID`

In our case "send the user to the URL" means displaying the URL and asking the user to login there and copy and paste the code in the same window (just like Adium does).

The user will see this after going to the link:

![image](https://cloud.githubusercontent.com/assets/30809/11444367/c459182e-94f2-11e5-8635-52d516fef82c.png)

After receiving the "authorization code", we need to request an "access token" using the "client secret". We probably need to setup something on a server to request this.

After having the "access token", we implement the SASL mechanism like this:

```
<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl"
    mechanism="X-OAUTH2"
    auth:service="oauth2"
    xmlns:auth="http://www.google.com/talk/protocol/auth">
  base64("\0" + user_name + "\0" + oauth_token)
</auth>
```

The OAuth client ID (`OURCLIENTID`) must be registered and managed by a Google Account. Its value is public and I don't think we need to provide configuration for this, for creating an "app-specific password" will be easier than configuring a custom OAuth credential.

**Documentations**
Google OAuth: https://developers.google.com/identity/protocols/OAuth2InstalledApp
SASL: https://developers.google.com/talk/jep_extensions/oauth?hl=en

For reference, this is the Adium URL: `https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogletalk%20https://www.googleapis.com/auth/userinfo.email&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=853036734951.apps.googleusercontent.com&login_hint=juniorz@gmail.com`

**Comment by olabini** [comment]
I'm not sure we should be doing this, if it is necessary for us to host something for it to work. Can you expand on that?

**Comment by juniorz** [comment]
I'm also not sure. Actually, Google accounts are not friendly to use with our setup and require some extra work to allow Tor anyways. The default setup, will block login attempts from Tor exit nodes and send you an email asking to approve the new device.

I suspect that using 2-step auth and/or app-specific passwords make Google relax on that (I was able to login with no problem) but we still need to document this to the user, since we had some support request related to this issue.

**Comment by olabini** [comment]
We have another issue for documenting this and give a warning when it happens, #168
