### ISSUE TITLE
Migrate app to a GtkApplication

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#164]
See

- https://developer.gnome.org/gtk3/stable/GtkApplication.html
- https://developer.gnome.org/gio/stable/GApplication.html

**Comment by olabini** [comment]
What would it actually give us?

**Comment by tcz001** [comment]
When we want to use the system menubar, hide/reopen, and make sure there's only one instance of coyim running in system.

**Comment by tcz001** [comment]
and also probably notification feature on gnome

**Comment by iapazmino** [comment]
+1 for the notifications

**Comment by olabini** [comment]
OK, makes sense! =)

**Comment by juniorz** [comment]
I found this example of a `GtkApplication`: https://developer.gnome.org/gtk3/stable/ch01s04.html

Bonus: I also discovered that glib already have something to turn templates into code: `glib-compile-resources exampleapp.gresource.xml --target=resources.c --generate-source`

`exampleapp.gresource.xml` is a kind of manifest of UI files.

**Comment by tcz001** [comment]
wow, no more ruby!
