### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#166]
We can build windows in appveyor now, but it's necessary to add a installer for most windows users, we can package all runtime dependencies and use qt installer to wrap a msi file.

**Comment by tcz001** [comment]
it's a subtask of #52

**Comment by tcz001** [comment]
[Here](https://ci.appveyor.com/project/tcz001/coyim/build/1.0.361/artifacts) is a working binary bundle of windows.

**Comment by olabini** [comment]
Is it repeatable and easy to do? How good is the experience? Did you add a link from the CoyIM home page?

**Comment by tcz001** [comment]
Appveyor will build the binary when we push to master and release, It just needs unzip and user can create a quick link to the executable from anywhere. The only remaining problem is uploading to Bintray is not working(always showing uploaded successfully but only get 200+Byte file)
