### ISSUE TITLE
Our QueryMessage lacks a friendly message

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#167]
When we send a message to a contact that has no support to OTR, the contact doesn't see a nice message. Only `?OTRv23?`

Other clients append a descriptive message after this.

**Comment by tcz001** [comment]
why not use whitespace query?

**Comment by tcz001** [comment]
And I can't imagine how can we send a friendly message if we never get any AKE response back when the other side doesn't support. Or probably send an "I'm trying to establish a OTR channel with you." every time?

**Comment by juniorz** [comment]
I meant sending a friendly message to the other person, not to the coy user. Most of the clients send query messages with an extra message, like: `?OTRv23? john is trying to initiate a private conversation with you, but you seem to not support. More details in https://otr.cypherpunks.ca/ `.

If the other person supports OTR, this message will never be displayed because it will be handled by the protocol.

**Comment by tcz001** [comment]
So my question is why not use whitespace query, can't it be appended with the same message?

**Comment by juniorz** [comment]
Yep, whitespace tags are just appended to your plain message.

I remember we had chosen to force OTR and refuse sending plain text
messages, and whitespace is against this choice.

Whitespace does not actually force OTR because it fails silently.

**Comment by olabini** [comment]
We should definitely have a nice message, but let's do it without the link and the name of the user.

**Comment by juniorz** [comment]
It only fix the case of the user clicking the "Start encrypted chat" on the developer menu.

Our current OTR policy, auto-starts the AKE. In this case, the query message is sent as part of the protocol, and is not addressed by c98aafa.

I would expect the protocol having some configurable "Query Message banner".

**Comment by juniorz** [comment]
See `otr3.Conversation#sendMessageOnPlaintext`: https://github.com/twstrike/otr3/blob/master/send.go#L36

**Comment by olabini** [comment]
Ah, good point. Sigh.
