### ISSUE TITLE
Setting up a google account is annoying

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#168]
Every time you connect to a gmail XMPP account over Tor it warns you that you have a login from a new location. You must approve the login, or disable this security feature.

You wont see the warning if you have 2-step auth enabled (need to confirm), but you will only be able t login using an app-specific password or via OAuth token (see #159).

We can auto-detect a login failure for a Google account (by the presence of the `X-OAuth` SASL mechanism, for example) and take some action.

We could at least give the user some information about how annoying it can be to setup a gmail account.

**Comment by juniorz** [comment]
We could add a FAQ page explaining the issue.

Add the following resources:
- How to enable "less secure apps": https://support.google.com/accounts/answer/6010255
- Creating app-specific passwords: https://support.google.com/accounts/answer/185833

**Comment by tcz001** [comment]
A easy and stable way is just setting up the app-specific passwords. OAuth is for webapps(that should never expose the secrets) let's ignore it. I'm creating a FAQ page on CoyIM-page.

**Comment by olabini** [comment]
@juniorz - where in the app do you think is the right place to recognize this condition? I think adding a popup with information about app-specific passwords is a good idea, inside of the app itself, since we can detect it.

**Comment by juniorz** [comment]
When the user attempts to login using her password the authentication will fail (even if the password is correct). At this moment we have an `xmpp.ErrAuthenticationFailed` and can detect whether the account is managed by Google if it supports `X-GOOGLE-TOKEN` and/or `X-OAUTH2` SASL mechanisms.

We react to `xmpp.ErrAuthenticationFailed` errors by displaying the "Enter your password" dialog (`AskForPassword.xml`). There is no additional information telling the user the authentication failed.

We can add a message to this dialog informing that the authentication failed and its likely due how Google handles XMPP authentication for its accounts.

The user can then follow either "Allowing less secure apps to access your account" or "Sign in using App Passwords". I'm rather inclined to encourage the user to use app passwords.

Thoughts?
