### ISSUE TITLE
Credits link is not working

### ISSUE THREAD

**Issue by merongivian** [twstrike/coyim#174]
on the about coyim dialog i got this this error
![coyim](https://cloud.githubusercontent.com/assets/4277403/11791958/bb52084e-a271-11e5-9e6f-fc5962a29bdf.png)

**Comment by tdruiva** [comment]
:disappointed: 
This should only open your default email client.
Is just this text `STRIKE Team <coyim@thoughtworks.com>`

@merongivian Which OS are you using?

**Comment by merongivian** [comment]
@tdruiva im on OSX yosemite

**Comment by olabini** [comment]
We shouldn't actually have a link here.

**Comment by tdruiva** [comment]
Yeah, I blame Gtk :hamster: 
It's a default behavior in GtkAboutDialog.

@juniorz was looking this thing yesterday.

**Comment by juniorz** [comment]
I had forgotten to push.
