### ISSUE TITLE
Easy CoyIM install on Mac

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#178]
- [ ] Brew formula
- [x] Brew cask

Or one of them?

**Comment by sriprasanna** [comment]
I just raised a pull request to add CoyIM installer [here](https://github.com/caskroom/homebrew-cask/pull/16366).

I would like add an AUR package for CoyIM, should I create a separate issue or is it possible to add that to the platforms list above?

**Comment by vitorgalvao** [comment]
Just to stop any confusion, @sriprasanna’s contribution is not a homebrew formula, but rather a homebrew-cask cask (different projects).

The main difference is that in homebrew-cask we’re just getting the ready-made package you provide, while homebrew can compile from source. If what you want is the latter rather then the former, then the submissions has to go about a different way. In the past we had no problem in having the same package across projects, but since we’re in talks of merging under the same repo, we want to stop that duplication.

**Comment by sriprasanna** [comment]
@tdruiva With the context provided by @vitorgalvao let me if you prefer homebrew formula over the cask.

**Comment by tcz001** [comment]
I've split this issue, for fedora it's here #197

**Comment by sriprasanna** [comment]
@tcz001 So are we going ahead with the cask?

**Comment by tcz001** [comment]
I think for now we can accept cask since we already have a binary built by travis-ci & bintray. And for people who want to try build from source, we provide documentation for dev.

**Comment by juniorz** [comment]
`cask` does not require the user to compile (and download/compile all the dependencies) but relies on somebody else (us?) to always provide compiled versions (.dmg), and the user must trust this version does not have any backdoor.

What benefit it provides over downloading the .dmg? Automation? Who are the target users for this?

I'm ok with having a brew cask, but it's one more piece of software that needs to be manually maintained on every version released. It can't be automated since it depends on a 3rd party to accept a PR to some brewcask repo.

**Comment by tcz001** [comment]
brew formula is actually having similar problem, we need to make sure the build process is not having backdoor and also need to provide more instructions about dependencies.

We already have dmg and binaries released on bintray, this *has* been a highly trusted place we do distribution officially.

**Comment by sriprasanna** [comment]
@juniorz I understand your concern. 

You are right, homebrew-cask doesn't require user to download and compile the source code. Instead, it downloads binaries from trusted source(Bintray in this case). You can find complete information on the [official page.](http://caskroom.io/)

Homebrew-cask is just an extension on top of homebrew(just another tap) which lets you install binaries with ease.

### Maintenance:
It doesn't matter if we go with homebrew or homebrew-cask we still have to modify the installation formula. 

##### Automating this with homebrew-cask in the pipeline is pretty easy: 
1. Push to Bintray 
2. Update version and sha256 
3. Push to Github
4. Raise pull request

The steps for homebrew-cask remains the same even if you add a new dependency to the application(ex: go, gtk+3, etc,.). 
**But it will not be the same for homebrew formula**. You will have to manually modify your homebrew formula to include the new dependencies.

### Target users
I personally use homebrew to install all system packages(ex: git, postgres, ack, etc,. ) and use homebrew-cask for all desktop applications(ex: Firefox, Virtualbox, LibreOffice, etc,.). For example: You cannot install Firefox through homebrew directly but you can install by tapping homebrew-cask. So far homebrew-cask has 2938 casks available.

### Pull requests
Both homebrew and homebrew-cask communities work in a similar fashion. If you want the formula in the main repository you will have to raise a pull request.

Hope that helps.

**Comment by vitorgalvao** [comment]
@juniorz Regarding your concerns, @sriprasanna made a good job of explaining how homebrew-cask works (and how it compares to homebrew), but there are some points I’d like to add:

+ We do not accept any cask in our main repo that has a download source that every user can verify by going to the application’s website. Only official verifiable sources are allowed.
+ We’re pretty fast accepting PRs. Many times just a few minutes, and most of the time in the same day (if it’s just a version bump, you can be pretty sure that’ll be the case).
+ You don’t have to depend on a third party. You can just as well keep the file in your own repo (which you have write access to) a direct user to install from there via `brew cask install <url>`.

**Comment by adityadalal924** [comment]
Now available with `brew cask install coyim` (`brew update` if you don't see it, of course)

**Comment by sriprasanna** [comment]
Thanks @vitorgalvao @adityadalal924

**Comment by tcz001** [comment]
Thanks for updates :)

**Comment by sriprasanna** [comment]
@tcz001 Are you going to close this issue?

**Comment by vitorgalvao** [comment]
Just noticed [the updated first post](https://github.com/twstrike/coyim/issues/178#issue-122273278).

[To reiterate](https://github.com/twstrike/coyim/issues/178#issuecomment-168817393), we’re currently [trying to get rid of duplicates](https://github.com/caskroom/homebrew-cask/issues/15603), and this is something both teams agree is a good thing.

So it’s either a (in the official repos) cask or a formula, but not both.

**Comment by tcz001** [comment]
Closing

**Comment by sriprasanna** [comment]
@tcz001 Thanks.
