### ISSUE TITLE
Generated binaries should have a hash to verify download

### ISSUE THREAD

**Issue by iapazmino** [twstrike/coyim#181]

**Comment by tcz001** [comment]
we already have it see here e0915c99bbd0efa8cdb3830bb80e5bc9ca85af9e

**Comment by tcz001** [comment]
but since we are using a ci solution for this, I'm not quite sure if we already have a reproducible build for us to check by matching the binary hash built on our own machine.

**Comment by iapazmino** [comment]
Awesome.
