### ISSUE TITLE
Possibility to block when is receiving unsafe message

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#186]
Would be nice to have an option to bock to receive unprotected message.

I mean, when this notification appear, would be interesting to have a button "Hey peep, I can not talk in this way" or something like

![screenshot from 2015-12-16 11-26-01](https://cloud.githubusercontent.com/assets/1254745/11846919/d97a9296-a3e8-11e5-832d-beefe5687233.png)

**Comment by olabini** [comment]
I'm not sure how this technically can be done. We can't stop the other side from sending things - we can block the messages from being seen but that doesn't really make anything better. Can you expand?

**Comment by olabini** [comment]
I don't really understand what the feature would be, so I'll close this for now.

**Comment by xSmurf** [comment]
I like this idea a lot, specially if OTR is to be made mandatory, there should be some way to signify to the contact that you cannot talk to them due to lacking encryption.
