### ISSUE TITLE
Provisioning scripts should be put in other places for easy dev

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#190]

**Comment by juniorz** [comment]
As mentioned in #192, provisioning scripts assumes you have a controlled environment. The current provisioning scripts (inside the `ci/` folder) assumes the Travis VMs environment.

Moving this to a generic provisioning script is only valuable if you have a controlled environment (Docker image, Vagrant box, etc).

**Comment by merongivian** [comment]
@juniorz  I'll try addressing this with Docker, thanks for the suggestion :+1:

**Comment by olabini** [comment]
Any progress here?

**Comment by olabini** [comment]
I think we are already covering this with #284 so I'll close this issue.
