### ISSUE TITLE
When account is disconnected, roster don't reflect it

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#191]
After been connected during while, my account was disconnected.
I received the notification about account been disconnected, but the roster doesn't behave like been disconnected.
Also, if I click in the roster, this frozen CoyIM.

```
[CoyIM] 2015/12/17 17:05:22 /home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/connection.go:214: xmpp: error receiving stanza. read tcp 127.0.0.1:59518->127.0.0.1:9050: use of closed network connection
>>> ALERT error reading XMPP message: read tcp 127.0.0.1:59518->127.0.0.1:9050: use of closed network connection
```

![screenshot from 2015-12-17 17-23-39](https://cloud.githubusercontent.com/assets/1254745/11883809/665a77b2-a4e3-11e5-947b-c50060df412a.png)
Names removed because of reasons :smiling_imp:

**Comment by olabini** [comment]
Fixed with 0748d320ee7e66760a2a0baf9fd28ac3c6bf1627
