### ISSUE TITLE
Problem in macos after send message.

### ISSUE THREAD

**Issue by rxvc** [twstrike/coyim#193]
Alway when i send a message in macos coyim crash . I send you the log 
>>> INFO New OTR session with ipazmino@thoughtworks.com established
    2 [CoyIM] 2015/12/21 15:39:32 /Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui_reader.go:25: gui: loading compiled definition "VerifyIdentityNotification"
    1 panic: gui: failed load VerifyIdentityNotification: Error on line 28 char 13: Element 'child' was closed, but the currently open element is 'interface'

**Comment by tdruiva** [comment]
@rxvc Have you downloaded recently?

**Comment by juniorz** [comment]
This is supposed to be fixed in v0.1. You can find it at https://dl.bintray.com/twstrike/coyim/v0.1/mac-bundle/coyim.dmg

**Comment by olabini** [comment]
@rxvc can you verify that this doesn't happen in the latest version?

**Comment by rxvc** [comment]
Hey the issue was solved Thanks a lot.
