### ISSUE TITLE
Verify-bar doesn't disappear if you choose verify from the menu

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#196]
If you haven't verified the fingerprint, and then get the verify-bar, and you choose dev-options and press verify fingerprint there, the verify bar doesn't disappear after verifying it.

**Comment by juniorz** [comment]
Is not the menu supposed to go away? That is why I had ignored this.

**Comment by olabini** [comment]
True, but since we still have it, and people have started using it, it seems like a good idea to fix it. (which I've lready done)
