### ISSUE TITLE
Investigate OMEMO protocol

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#199]
http://conversations.im/xeps/multi-end.html

> a protocol that leverages axolotl encryption to provide multi-end to multi-end encryption, allowing messages to be synchronized securely across multiple clients, even if some of them are offline.

More info: http://conversations.im/omemo/

**Comment by olabini** [comment]
For now I would like to close this issue. OMEMO is different enough in communication style, and relies on multicasting all messages to every place - OTR has different goals and I don't feel OMEMO is compatible with Coy right now. If any other protocol should be investigated, it is Ricochet, but let's wait with that as well.
