### ISSUE TITLE
GTK deps issue

### ISSUE THREAD

**Issue by du5t** [twstrike/coyim#200]
Followed instructions in README, but ran into the following error both by installing through `go get` and trying to build from source (os: Ubuntu 14.04 amd64):

```
# github.com/gotk3/gotk3/gdk
could not determine kind of name for C.gdk_pixbuf_new_from_bytes
```

It stems from https://github.com/gotk3/gotk3/issues/56, but I'm not sure how to solve it.

**Comment by juniorz** [comment]
gotk3 requires Gtk+3 >0 3.12 (per README).

This function is supposed to be available since 2.32 (https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-bytes)

I suspect you have an old GTK+3 version.

**Comment by juniorz** [comment]
See: https://github.com/gotk3/gotk3/issues/56

**Comment by olabini** [comment]
This has been fixed in gotk3.
