### ISSUE TITLE
Use godep to protect ourselves from gotk3

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#202]
Coy is broken since this: https://github.com/gotk3/gotk3/pull/54

I propose to use `godep` (https://github.com/tools/godep) to better manage gotk3 versions and protect ourselves from this kind of problems. I suspect it would make setup a little bit more complicated (`go get` wont simply work), but it would work.

Thoughts?

**Comment by tcz001** [comment]
Will this influence our install process, etc: `go get github.com/twstrike/coyim`?

**Comment by olabini** [comment]
I'm unsure. How much more annoying will setup be?

**Comment by juniorz** [comment]
As far as I understand (from the docs at https://github.com/tools/godep), besides running `godep restore` (the equivalent of `bundle install` in ruby land), you may need to prepend `godep`to your go commands, like `godep go test`.

It also gives you the same benefit of having direnv to manage a separate $GOPATH per project. You just need to set `GOPATH=$(godep path)`

However, I suspect this is the easier way to go towards reproducible builds, once we need to have more control over the dependencies and `godep` would give us this for free.

**Comment by olabini** [comment]
I want to punt on this for now - we haven't generally had problems with dependencies.

**Comment by tcz001** [comment]
I'm reopening this issue, because now we can't reproduce the v0.2 without specifying an old Gotk3 version

**Comment by olabini** [comment]
I'm looking at this for a variety of reasons - but we should be careful to not make it necessary for a new checkout to using anything extra. Vendoring etc maybe?

**Comment by olabini** [comment]
First, the right solution seems to be to use the go tools vendor support (except I'm not a huge fan of the idea of using git submodules). However, the go vendor support is experimental in 1.5 (behind an ENV variable). That could be OK, except it won't work on 1.4, and I think we still need to support Go 1.4 for Tails, correct?

**Comment by olabini** [comment]
OK, after trying, it seems the vendor support is definitely _not_ ready yet - all kinds of lovely compiler errors and other stupidity.

**Comment by olabini** [comment]
OK, I've just pushed this - we are now using godep with rewriting of import statements, so all dependencies we use are in our source tree. Yay.
