### ISSUE TITLE
Two ci badges ?

### ISSUE THREAD

**Issue by merongivian** [twstrike/coyim#208]
One is passing and the other one is failing , the passing one seems to be pointing to another forked repo, so why don't merge it ?

**Comment by tcz001** [comment]
The appveyor one is for windows build. We are trying to fix the travis.

**Comment by merongivian** [comment]
@tcz001 oh got it

**Comment by merongivian** [comment]
@tcz001 why is it the repo under you're user though ? , that got me confussed :confused:

**Comment by tcz001** [comment]
Because appveyor don't have organisation account. I have to attach it to my own github account, but it's still building upon this repo.
