### ISSUE TITLE
Graphical conversation

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#21]

**Comment by juniorz** [comment]
We have a basic conversation window. It has 2 text areas: the one in the top displays the history of messages, and the other is the place you can type your messages.

`Enter` sends messages and any combination of modifier key + `Enter` adds a newline to the message. Every message is sent and received through an `otr3` conversation.

**Comment by olabini** [comment]
At some point we need to support/fallback to non-OTR, of course. Or does otr3 take care of that too?

**Comment by juniorz** [comment]
Depending on the policy, yes. If your policy is not too restrictive (`REQUIRE_ENCRYPTION`) otr3 should simply send/receive plaintext messages if you never do an AKE.

**Comment by tdruiva** [comment]
As we decide to all conversation to be OTR and to be send by Tor, do we need to care about this conversation for Dogfood?

**Comment by olabini** [comment]
For dogfood, I think we have the basics necessary.
