### ISSUE TITLE
Manually importing private key from different clients

### ISSUE THREAD

**Issue by blackbnu** [twstrike/coyim#211]
I was using Adium in a different computer and decided to migrate to Coy when I got a new machine. In order to do that I copied the otr.private_key and otr_fingerprints files expecting to be able to manually import the files somehow or even copying it's values to coyim config file.

Apparently that's not possible and I'll have to create new keys for that same account and verify fingerprints once again with all users.

**Comment by olabini** [comment]
Yes, currently we can only import things that are configured for other clients - we don't support manual import, although that should be very easy to support. Wanna write some Go-code? =D
