### ISSUE TITLE
Importing account from Adium that uses Tor links is not working

### ISSUE THREAD

**Issue by rodrigomaia17** [twstrike/coyim#213]
Looks like the AdiumImporter is not setting the "RequireTor" config property when importing an account with onion links. 

This works if I create a new account by coyim itself.

**Comment by olabini** [comment]
What do you mean with onion links?

**Comment by rodrigomaia17** [comment]
When the server of the account is behind a .onion hidden service url.

**Comment by olabini** [comment]
Ah of course, sorry. Yes, that should definitely work.
