### ISSUE TITLE
Ideas to make it awesome

### ISSUE THREAD

**Issue by aels** [twstrike/coyim#214]
Hi. This is list of staff i'm missing.

//== add global hotkeys
- to show message window w\ active conversation (or incoming messages)
- Esc key to hide all coyim windows (when all done)
- key to show\hide contact list (maybe like iTerm do, but from the right side)

//== ability to merge message window & cl (like skype does)
//== tabs support for chats
//== built-in OTR (w\ color indication of current chat status)
//== fully colorable UI
//== fast search in whole chat history w\o leaving chat window
//== chat files in the right col (like in HipChat)
//== Ability to hide Doc icon & live only in tray
//== "autostart" checkbox in UI
//== auto-reconnect (+ OTR session renew!) ability

Hope it will be useful for you. Thanks.

**Comment by olabini** [comment]
Hi,

Thanks for the list of things. Let me give some thoughts on some of these:
- The different ways of changing how windows work and making them more flexible would be nice. However, we also want to have the code be as simple as possible, so I would be strongly in favor of choosing one option and going with that
- OTR is already built in - it's just not exposed in the UI as much as it could be
- Search of chat history: we will never have chat logs turned on by default, and right now there is no support for chat logs at all - from a privacy and security standpoint, this is something that is quite important.
- Not sure I understand what "chat files in the right col" means
- auto-reconnect we already have, and OTR session renew as well.

Cheers

**Comment by aels** [comment]
sorry for my inattention.
- So, by meaning "files stash on the right side of chat" i mean something like this: ![](https://i.gyazo.com/a6f02bec92984ce4a7d97e3426cfee66.png)
- Chat history is the doubleside edge, yes, but ability to store history (ever encrypted) is important part of coyim usage like serious messenger to work (not for chit-chat only). W\o ability to save important info inside Coyim, users will try to store it outside (often in places more dangerous, like just on their disks). So, maybe storing history encrypted inside Coyim is more like "care" of users rather than inprivacy.

**Comment by tcz001** [comment]
The reason we use OTR by default is trying to avoid any sensitive data been stored and recovered with single key/password, important history should be stored in a safer place rather than CoyIM at least for now. Maybe a select-mode to store it in PGP format is a good idea.

**Comment by aels** [comment]
ok, got it. Thanks.
