### ISSUE TITLE
Show me my own otr fingerprint

### ISSUE THREAD

**Issue by rodrigomaia17** [twstrike/coyim#216]
It would be good if I could see my own OTR fingerprint in a easy way.

**Comment by olabini** [comment]
You can see that when bringing up the dialog to verify another user

**Comment by 0x27** [comment]
This should be implemented for the purposes of pre-sharing OTR fingerprints, to be fair. It is considered good practice to publish your OTR fingerprint alongside your jabber id for new contacts to streamline verification procedures.

**Comment by olabini** [comment]
Oh, absolutely. That's why I left the issue open.

**Comment by olabini** [comment]
This is fixed in d3a98702
