### ISSUE TITLE
Registration of Accounts broken/Some UX Issues/Ideas

### ISSUE THREAD

**Issue by 0x27** [twstrike/coyim#218]
Let me know if this needs breaking out a bit.

While testing the client on a Debian Jessie host (i386, old netbook) I noticed a few issues that made the client un-useable from a "first run" perspective of someone without a pre-existing XMPP account. 
Annoyingly, I cannot get screenshots off the device I was testing it on at the moment due to stupid reasons, but I can get some if it helps reproduce in a couple of days. I am typing out the last lines of the debug from one device to another, hence the lack of backtrace... 

The scenario here is someone who has just installed the client, and is trying to get themselves set up with an account using Tor. For Tor, the user is running the Tor Browser Bundle.

Steps to reproduce (first route).  
1. Run the Tor Browser Bundle, to launch a Tor instance locally. Wait for it all to connect, confirm Tor is connecting through the Tor browser and https://check.torproject.org/
2. Run the `coyim` executable (launches the GTK client).
3. Create a master password on launch as asked by the client.
4. coyim asks for account details now. Because we don't have an account, click cancel.
5. Click on "Accounts -> Register..." in the GUI.
6. A small window will appear titled "Choose a server for your account", the dropdown box will be blank initially, but on clicking, you can select a server. Pick any server, it doesn't matter. Click apply.
7. Nothing happens. No further menus load to proceed with account creation. It simply sits there. User gives up and goes home ;)

The last line here in the debug log is `/gui/ui_reader.go:25: gui: loading compiled definition "AccountRegistration"`, and nothing else happens after "Apply" is clicked on the server selection menu. You can retry this repeatedly, the client does not crash.

Steps to reproduce (second route).
1. Run the Tor Browser Bundle, to launch a Tor instance locally. Wait for it all to connect, confirm Tor is connecting through the Tor browser and https://check.torproject.org/
2. Run the `coyim` executable (launches the GTK client).
3. Create a master password on launch as asked by the client
4. coyim asks for account details now. We don't have an account, so we enter some fictitious details for a known to be working XMPP server in the hopes it makes an account for us. "dukgo.com" is suggested so we used that. We do not select "Other Settings", and hit "Save".
5. The GUI notifies us the account was added successfully.
6. We right click on the account and click "Connect".
7. We get repeated authentication failures due to failing to enter the correct password for the account, as it was not registered. There should be a mechanism here for registering if the server tells us the account does not exist.

So, to wrap up. The in-band registration built in does not work yet, so the client cannot register an account itself. 

It also was noted that without watching the debug log, there is nothing to say it is explicitly using Tor. While from examining the source, there is a "not tor" warning somewhere, there should be a "Yes, I am using Tor for this" UI alert to positively confirm for the user that the client is, in fact, using Tor.

For first-run, once the master-password is dealt with, it would be more user-friendly if the user was first presented with a dialogue with 4 buttons on it. "Create Account", "Import Accounts", "Add Account" and "Cancel".
"Create Account" would launch the "Accounts -> Register" UI, "Import Accounts" would launch the "Accounts -> Import" UI (NOT tested yet), "Add Account" would launch the "Accounts -> Add" UI, and "Cancel" would skip this and drop to the client itself, where the user can do that themselves.

While clicking around I did find another thing that caused it to crash, but it will take a bit of mucking about to reproduce this.

Unrelated: any typos are due to the lightbulb in the room failing mid-typing...

Host: Linux 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt10-1-deb8u3
Coyim Git Version: https://github.com/twstrike/coyim/commit/d44546231aec54ade904f091159a4229f40c6447

**Comment by 0x27** [comment]
Edit: I should also note that adding an extant account works fine, just to avoid any confusion. If I create an account on dukgo.com using Pidgin, and then put those creds into Coyim, it seems to work fine. No idea if it syncs contact list from the server yet.

**Comment by juniorz** [comment]
> 6. A small window will appear titled "Choose a server for your account", the dropdown box will be blank initially, but on clicking, you can select a server. Pick any server, it doesn't matter. Click apply.

The in-band registration has been tested on `calyxinstitute` server only. The reason is because it does not require any extra fields (like captchas) which still need to be implemented.

**Comment by 0x27** [comment]
I'll retest specifically with the calyxinstitute server and report back with how that works out shortly. Based on testing with Pidgin though, the dukgo server does not require any captcha - it just asks to confirm creds (which I think pidgin does anyway for some servers) which can probably be done transparent to user.

**Comment by olabini** [comment]
I've added #282 to capture some of these problems. #272 and #267 covers the other things I think.
