### ISSUE TITLE
Graphical OTR conversation information

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#22]

**Comment by iapazmino** [comment]
What is the information we want here?

These are what I've got so far:
- Time the conversation started.
- How long has the conversation been going on.
- Is logging enabled.
- Is OTR enabled.

**Comment by juniorz** [comment]
I can remember of the following information:

- Our fingerprint
- Their fingerprint
- Session ID
- Whether the channel is encrypted or not (since we are enabling OTR by default)
- Whether the other peer's identity has been verified or not

**Comment by tcz001** [comment]
I'd prefer to see a encrypted channel on a more visible place, and identity trusty as well.

**Comment by juniorz** [comment]
It doesn't necessarily have to be displayed in another window. The issue is about coming up with a graphical representation for it ;)

Be creative =D

**Comment by olabini** [comment]
Most of these things I think we shouldn't show by default. Remember, we want this to be secure-by-default and easy to use for Roy and Glenn. I have a suggestion on how to convey some of this information, will open another ticket about it.

**Comment by olabini** [comment]
I'm going to close this, I think we should basically rethink this quite deeply.
