### ISSUE TITLE
Menus appear outside the window

### ISSUE THREAD

**Issue by aepsil0n** [twstrike/coyim#220]
I'm testing CoyIM on ArchLinux inside the i3 window manager on a MacBook with Retina display and thus running it using environment variables set like this:

```
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
```

It looks like the menus appear outside of the window (which is probably not intended). See [this screenshot](http://i.imgur.com/iTwOHeN.png).

This only happens when I tile the windows next to each other and the CoyIM window is on the right side. By making the CoyIM window slightly larger the menu starts to move into the window again.

**Comment by olabini** [comment]
That's extremely strange, although I have a hard time seeing this is a problem with CoyIM - we use very standard controls, and my guess is that this is a bug in GTK.

**Comment by aepsil0n** [comment]
Okay, if you are not doing any manual menu placement, it probably isn't… it might even be a bug in i3. That is kind of hard to pin-point. I guess I have to look elsewhere for a place to complain about this.

Thank you for the feedback nonetheless!
