### ISSUE TITLE
Multiples dialogs when tries to connect

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#223]
How to reproduce:
- Have a configured account with the "wrong password"
- Click to connect
- Wait some seconds after the first "type password" appear

Current behavior
- Multiples dialogs to type password shows up
- if you submit the password in the lasted opened dialog, don't connect and don't close the previous one

![screenshot from 2016-02-01 13-57-02](https://cloud.githubusercontent.com/assets/1254745/12727798/88f25150-c8ec-11e5-82b3-17e377f5542a.png)

**Comment by olabini** [comment]
I think the right choice here is to keep the Session in state "connecting" while waiting for the password - that should fix this problem.

**Comment by tdruiva** [comment]
:+1:

**Comment by codeadict** [comment]
Having same issue
![screenshot from 2016-02-23 12-07-39](https://cloud.githubusercontent.com/assets/168440/13259743/b64b2bcc-da26-11e5-95e2-46648a76af23.png)

**Comment by tcz001** [comment]
Now it won't popup multiple dialogs, but we should consider sending a disconnectCmd signal when user choose Cancel or Directly close the dialog, which still has bug in #256

**Comment by tcz001** [comment]
Closing this and track further problems in #257

**Comment by tdruiva** [comment]
Tks!
