### ISSUE TITLE
Graphical SMP (Socialist Millionaire's Protocol)

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#23]

**Comment by olabini** [comment]
It's time to start thinking about what this looks like. We know what the technical implementation looks like - we need to figure out a nice way to present this to the user. @SweetVirginia

**Comment by SweetVirginia** [comment]
Hey, for the sake of documentation, here are the links for the previous work we did. 

Alice: https://invis.io/X39QQUGE9
Bob: https://invis.io/PY9QR0EVG

There's plenty to iterate still, specially copy writing and visuals. 

<3

**Comment by rosatolen** [comment]
Todos:

- [ ] Embedd Image files
- [ ] Enable Fingerprint flow
- [ ] Bob's UI
- [ ] Connect UI with SMP logic

**Comment by jvoisin** [comment]
Are you planning to support (like Pidgin) a question/answer based scheme, or just a pin-based one?

**Comment by olabini** [comment]
Hi,

We will likely support "receiving" q/a from Pidgin and showing them, but maybe not generation of them - at least not in the first revision. The problem is that the more options we add, the more confusing it becomes to users.

**Comment by yakiradixon** [comment]
We've merged the work for this feature (including receiving q/a from Pidgin ans showing it in CoyIM) into master. Closing this for now.
