### ISSUE TITLE
We allow people to connect without Tor even `RequireTor` is true.

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#230]
The previous logic used `RequireTor` to force having a Tor proxy configured using a common case scenario: default Tor proxy at 127.0.0.1 on common ports. That is how Tor is usually installed even for non-technical end-users that just downloaded Tor Browser bundle.

Any connection attempt would fail if `RequireTor` but no "Tor-like" proxy could be found, which would protect the regular non-technical user from connecting without Tor.

Now you can have `RequireTor` and no Tor proxy configured you will only fail to connect if the user tries to connect using an .onion address, but in this case it will fail due not resolving DNS for the .onion address.

Introduced by (for reference): 1b924e2219aa549f6e8801801958c3ccb484f0d5

**Comment by juniorz** [comment]
That is, currently `RequireTor` means "check if Tor is running before connecting" and not really require Tor to be configured on the account.

**Comment by pixelrust** [comment]
Maybe related?
CoyIM 0.2 for Linux doesn't connect unless/until Tor Browser is running. 
Error message: _"Tor is not running"_

**Comment by olabini** [comment]
Hi, that's a different issue - by default, CoyIM will only connect using Tor. If you want to change this, you need to configure the proxies and remove the tor-auto:// proxy. However, a better solution for you would be to just install Tor as a service and run in the background all the time:
on Debian/Ubuntu that would be
  sudo apt-get install tor
and on Fedora
  sudo dnf install tor

Then you just need to start the service and set it to be on.

**Comment by pixelrust** [comment]
Thanks for the explanation. 
I'm still confused though: is Tor included in CoyIM? Is it supposed to work (in default mode, connecting to Tor) even if Tor is not pre-installed and/or running on the system?

**Comment by olabini** [comment]
No - CoyIM doesn't ship with Tor. We do try hard to use Tor if it's running, but you have to install it yourself.

**Comment by tcz001** [comment]
> If you want to change this, you need to configure the proxies and remove the tor-auto:// proxy.
I still get error saying "Tor is not currently running" when no proxy in the list.

**Comment by juniorz** [comment]
@tcz001 Are you connecting to a .onion address?

**Comment by tcz001** [comment]
No, it's thoughtworks.com

**Comment by juniorz** [comment]
We have decided to remove `RequireTor` and use the existence of `tor-auto://` proxy to indicate whether we should automatically use an `.onion` address.

See: #238
