### ISSUE TITLE
Display revision/version # from command line - also add support for proper version, not just revision

### ISSUE THREAD

**Issue by dma** [twstrike/coyim#231]
Either via CLI flag or in the UI (Help->About shows "1.0"). Useful for us testing in SGOS.

**Comment by olabini** [comment]
Help->About is supposed to show the git revision as well, from where you built it - how are you building?

**Comment by olabini** [comment]
Ah, if you only do a "go get" it won't be able to figure out the git version - you have to build it with the makefile for that to happen.

**Comment by juniorz** [comment]
Adding a "--version" flag would also be helpful.

**Comment by dma** [comment]
Ah, I see, of course, make sense, I'll advise my colleague who is maintaining the package for SGOS. Thanks. Yes, the CLI flag would be useful also. Sorry for the noise!

**Comment by olabini** [comment]
Actually, let's keep it open to track adding a CLI --version flag

**Comment by tdruiva** [comment]
For `--version`, we wanna to print the version generated by [this file](https://github.com/twstrike/coyim/blob/master/gen_version_file.sh), passing the result of this operation `git rev-parse HEAD` or we wanna to print `0.2`, the same version displayed in coy.im?

**Comment by tdruiva** [comment]
CoyIM version is going to be **or the flag** with the lasted commit **or its hash**.
