### ISSUE TITLE
Automate author list

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#237]
The about dialog list every author of Coy. It would be helpful to automate that into an `AUTHORS.md` file and simply add a reference to that file to the about dialog.

**Comment by olabini** [comment]
That would be nice. The previous thing called "git" when creating the dialog, which I don't particularly like.

**Comment by codeadict** [comment]
I can help with this task, excellent project guys, ill try to help the most i can, still newbie in Go but have a lot of experience with GTK

**Comment by iapazmino** [comment]
Great. Thanks @codeadict .
