### ISSUE TITLE
Ideas to detect if an account is configured to use Tor

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#239]
We discussed about different ways of detecting whether an account is configured to use Tor (either via `tor-auto` or a manual proxy configuration):

1. Build the proxy chain configured for the account and try to access `check.torproject.org`
2. Use our DNS resolver over Tor to resolve an `.onion` address. The initial idea was to use the `.onion` address for `check.torproject.org` which I was not able to find, only this issue[1].
3. Rely on the Tor extensions to SOCKS protocol, as described in [2]: unsupported `BIND` command and/or new `RESOLVE` command.

1 - https://trac.torproject.org/projects/tor/ticket/6098
2 - https://svn.torproject.org/svn/tor/branches/hidserv-perf/doc/spec/socks-extensions.txt

**Comment by olabini** [comment]
Remind me why we needed to do this? To decide if we can safely translate to hidden services for known servers, or for some other reason?

**Comment by juniorz** [comment]
This is also what I have in mind. If the user has `tor-auto` proxy we can assume "tor mode" (auto translate hidden services, for example).

But not having `tor-auto` does not mean the user is not eligible to "tor mode" (she can be using tor via transparent proxy, or a separate Qubes VM, for example).

**Comment by meejah** [comment]
Of possible interest: check.torproject.org has an API to tell you if you're reaching it via Tor: `https://check.torproject.org/api/ip`
