### ISSUE TITLE
Create real software packages for different platforms

### ISSUE THREAD

**Issue by micahflee** [twstrike/coyim#241]
It would be nice if CoyIM ran Linux repositories (or at least released .deb and .rpm packages) rather than just binaries. It should have .desktop files, etc.

And for Windows rather than just releasing a .zip that you extract and run somewhere, it would be nice if it something like `CoyIM_Setup.exe` instead, with an installer that puts these files in `C:\Program Files`, added start menu shortcuts, and included an uninstallers.

I have tested the Mac version yet, but probably the same. :)

**Comment by juniorz** [comment]
We have a `.dmg` for Mac with "drop to applications" and so on. It can be improved (by adding background image and some branding, for example) but I think this issue is really about Linux and Windows.

**Comment by juniorz** [comment]
Related to #197.

**Comment by tcz001** [comment]
Before CoyIM_Setup.exe comes out we need to find a better way to sign the application on our own offline building machine, closing this issue because it's been detailed in other issues.
