### ISSUE TITLE
Importing key material from file with multiple keys results in all keys associated to the account

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#243]
Given a file with private key material for multiple account (ex: adium files contain all the keys in one - or files exported from `keysync`) when using the import function all the keys are added to the one account. Expected behavior: only import the key for the selected account; alternatively prompt the user to select which key to import. This is quite problematic as there is currently no way to a) remove the key material b) select which key to use if multiple keys exist for an account.

**Comment by olabini** [comment]
Are you talking about when importing an otr-file manually, or when importing a full account?

**Comment by olabini** [comment]
I would not like the behavior to be importing keys for the selected account - then it would be impossible for people to retain keys over several accounts.

**Comment by olabini** [comment]
You can remove the extra keys by editing the configuration file manually, but yeah, at some point it should be possible to edit those things.

**Comment by olabini** [comment]
I'm not sure how we could expose a "key-deleting" interface though, there is no metadata associated with the keys - they are just binary blobs. Would you like to be able to delete them based on their fingerprint or something?

**Comment by xSmurf** [comment]
Hi Ola,

> Are you talking about when importing an otr-file manually, or when importing a full account?

When importing key material manually with the "Import Private Keys..." button.

> I would not like the behavior to be importing keys for the selected account - then it would be impossible for people to retain keys over several accounts.

Then if multiple keys are available maybe it should prompt the user for which one to import? Either by fingerprint and/or by account (as in the case of importing from Adium/Pidgin the key material is associated with an account in the file). There's definitely no point in importing more than one key for one account as a user cannot select which key to use. Or maybe I'm missing the point?

> Would you like to be able to delete them based on their fingerprint or something?

That sound reasonable.

**Comment by olabini** [comment]
Yeah, that makes sense. That sounds like the right way to do it.

**Comment by olabini** [comment]
I think for now I'll fix this by giving a choice if there are more than one keys in the file. Later we'll add some kind of support for editing/moving/deleting keys etc.
