### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by pixelrust** [twstrike/coyim#249]
This is to track / discuss Italian translation. 
See https://translate.zanata.org/zanata/project/view/coyim

**Comment by pixelrust** [comment]
I started translating. I've been using the web interface. 
I've also installed the Linux command line client. Do I actually need to use it? In which steps of the translation process?

**Comment by pixelrust** [comment]
I'd want to build a version of Coy that includes my Italian translation. To see the translated terms "in action" would help me to understand if I properly translated them

How do I do that? 
(I don't have previous experience with Golang and its compile/building process)

**Comment by pixelrust** [comment]
I see that some commands in the en-US translation begin with an underscore.

Should that underscore persist in translations? 
What's its role?

**Comment by pixelrust** [comment]
cc'ing @tdruiva to ask them help

**Comment by tcz001** [comment]
underscore is a feature used by gtk, https://www.gnu.org/software/guile-gnome/docs/gtk/html/GtkLabel.html

**Comment by iapazmino** [comment]
@pixelrust yes please add the underscore, it will activate the first letter in the word to launch the command.

**Comment by pixelrust** [comment]
Thanks for the help!

If command1 and command2 are in the same menu and they both begin with the same letter, should I choose a different activation letter for command2, e.g. putting the underscore before a different letter in command2?
That seems to be allowed by GtkLabel/mnemonics specs.

Btw, is there a rationale about which commands begin with the underscore in the en-US translation and which ones don't?

**Comment by tcz001** [comment]
Hey, I think you can decide which is a better place for underscore, Not sure if you are able to compile & test yourself, it's simple just run `make i18n` and `bin/coyim` will show the result.

About the style of naming, it probably be different for Italian, to me Mandarin is not possible to have that feature, so it always depends. Anyway, we can modify if we got report saying it wrong, so take it easy for now.

**Comment by tdruiva** [comment]
@pixelrust Thanks for the helping us with the translation.

> I'd want to build a version of Coy that includes my Italian translation. To see the translated terms "in 
> action" would help me to understand if I properly translated them.
> How do I do that? 

After download CoyIM project and provide the dependencies:
- build CoyIM `make build-gui`
- Edit `i18n/Makefile` and add the Italian folder, like this:
```
en_US/LC_MESSAGES/$(DOMAIN).mo \
**it/LC_MESSAGES/$(DOMAIN).mo \**
pt_BR/LC_MESSAGES/$(DOMAIN).mo \
```
- run `make i18n`
- edit `i18n/it/LC_MESSAGES/coy.po` and put some translation there (or just download your translations from Zanata)
<img width="300px" src="https://cloud.githubusercontent.com/assets/1254745/13440004/06d35a28-dfbe-11e5-8a51-bccc0a92ade1.png">

- run `make i18n` again to generate `.mo` file
- open coy `./bin/coyim`

> I've also installed the Linux command line client. Do I actually need to use it? In which steps of the
> translation process?

Naaa, don't need to use it. You can download the translation directly from Zanata's site

If you use IRC and need something, we're in the OFTC IRC server, channel #coyim

**Comment by pixelrust** [comment]
Thanks @tdruiva , it worked!

**Comment by pixelrust** [comment]
Translation is 100% complete. 
I still haven't found other Italians available for reviewing.
What would be the next steps?

**Comment by tdruiva** [comment]
Ideally we should review before release it.
@iliasbartolini wanna help us? :panda_face:

**Comment by iliasbartolini** [comment]
Happy to help :)
Overall the corrent translations look great.
There are only a couple of sentences for which I can think of slightly different alternatives. 
Is there a way I can comment directly on zanata with pixelrust? You can add my account there "iliasbartolini"

**Comment by tdruiva** [comment]
@iliasbartolini done and tks for the help! :wink:

**Comment by pixelrust** [comment]
Ciao Ilias :) Ho appena modificato alcune entries che mi erano sfuggite, tra cui "Fingerprint of peers" che ho tradotto con "Fingerprint dei contatti" e soprattutto "Are you liking it?" che trovo difficile e per cui propongo "Ti sta piacendo CoyIM?". Quello che ho modificato lo trovi in verde. Ora non toccherò altro, modifica e completa tu come ritieni meglio. Grazie!

**Comment by iliasbartolini** [comment]
Ciao pixelrust! couldn't find a way to comment on zanata.
Ti volevo solo chiedere riguardo il dilemma tra criptare, crittare, cifrare o ...
Inizialmente ho notato che avevi scelto quello che credo sia un po' meno comune (che può essere una bella scelta!) e solo sapere se avevi valutato le opzioni prima di ricambiarlo.

**Comment by pixelrust** [comment]
In effetti in seguito ho riflettuto proprio su questa serie di termini, finendo con lo scegliere quelli che più si avvicinano, anche letteralmente, al termine "crittografia". Il mio ragionamento è che il termine "crittografia" ormai viene usato diffusamente anche fuori dall'ambito strettamente tecnologico; di conseguenza, persone non esperte forse possono intuitire il significato del termine "crittare" più facilmente rispetto a "cifrare" o "codificare". Per questo vorrei evitare questi due termini. Nessun problema invece a usare "criptare" invece di "crittare", se lo ritieni migliore.

**Comment by olabini** [comment]
This is fascinating. With my Spanish I can _almost_ read these things. =)

**Comment by iliasbartolini** [comment]
Cool, we completed the whole translation on zanata.

@pixelrust : I went back to the "crittare" translation form :)

**Comment by pixelrust** [comment]
I'm closing the issue as the translation is done. Feel free to reopen if needed.
