### ISSUE TITLE
Unify peer details in a single dialog

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#251]
From #87 we decided it will be better to unify all contact-related information in a single place.

The "peer details" dialog (accessed via `right-click` -> `Edit...`) already contains:
- JID
- Nickname
- Groups

We are missing to move to this dialog:
- [ ] Fingerprints
- [x] Security settings (always/never encrypt)

**Comment by olabini** [comment]
How's this coming along?

**Comment by juniorz** [comment]
I'll work on this for this week.

**Comment by olabini** [comment]
Any update on this?

**Comment by juniorz** [comment]
Not done yet.

We should consider #393 when implementing this, as well as exposing the access to this "Edit..." via a "contact info toolbar" (mentioned in #343, but not converted in an issue).

**Comment by olabini** [comment]
#393 is fixed. I don't know if I understand the "contact info toolbar"

**Comment by juniorz** [comment]
What I had in mind is something like Adium toolbar: it provides different actions (with an icon) that can be performed in the context of a contact / conversation (the thing above the transcript in the following image).

https://adium.im/help/gfx/Chat%20window-Encryption.png

**Comment by olabini** [comment]
Hmm I see. I don't think we should do that right now - since that whole thing will need to be part of a bigger discussion about how users will interact with Coy.

**Comment by olabini** [comment]
For now, the focus should really be on getting the unification done.

**Comment by olabini** [comment]
Any progress?
