### ISSUE TITLE
Account menu should be the same

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#253]
To improve user experience, we should have the same account menu 
 
Accounts > account_id > 
<img width="218" alt="1" src="https://cloud.githubusercontent.com/assets/1254745/13302950/7bbea6d8-db1a-11e5-9d6b-050b44f0fd37.png">

Right click in the account_id, in the Roster:
<img width="122" alt="2" src="https://cloud.githubusercontent.com/assets/1254745/13302951/7be5fbd4-db1a-11e5-9e5c-04a5b97f13cb.png">

**Comment by juniorz** [comment]
Why? I think the right-click menu should be "give me only the essential commands" and the other should be "give me all the options".

**Comment by tcz001** [comment]
Why we need a dump info?

**Comment by tdruiva** [comment]
@juniorz what do you mean with "give me only the essential commands"?
How to define what's essential and what is not, for this case?

To provide a better usability, we should follow patterns. This makes user's journey easier.
Like if you see ThunderBird, right-click in a message is going to show the Message menu otions (the same menu as in the top of the application)
```
4 - Consistency and standards
Users should not have to wonder whether different words, situations, or actions mean the same thing.
Follow platform conventions
``` 
http://tfa.stanford.edu/download/TenUsabilityHeuristics.pdf

**Comment by olabini** [comment]
We can probably put the dump info behind a debug flag or something, but for now it's there. I agree with Tania though, we should expose the same things there. I've refactored the code (AND TESTS) and unified the two menus.
