### ISSUE TITLE
Shortcut for input method is not working

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#254]
I mean Shift when use Chinese input method

**Comment by olabini** [comment]
Any thoughts on where this problem is happening?

**Comment by tcz001** [comment]
Tried to unbind the shift in key-style but not work

**Comment by olabini** [comment]
Any news on this?

**Comment by tcz001** [comment]
I fixed this on linux, but for mac still doesn't work...

**Comment by olabini** [comment]
Hm, ok - do you know what to do about it on Mac?

**Comment by tcz001** [comment]
no

**Comment by olabini** [comment]
Any news? Will you be able to investigate it more deeply?

**Comment by tcz001** [comment]
I can ask for help in gtk-osx-devel-list for both this and #189

**Comment by olabini** [comment]
OK, that would be great!

**Comment by olabini** [comment]
Any update on this?

**Comment by tcz001** [comment]
According to the gtk-osx-devel-list suggestion, I suspect this problem is from some input method actually overriding system event handler, I'm going to try a bit building a simple InputMethodKit for debug, if it's really a issue of that special inputMethod only, we can close this issue.

**Comment by tcz001** [comment]
This is a common trouble that osx quartz port of GTK, closing this issue because it's not a coyim problem
