### ISSUE TITLE
Question/possible issue about Installation instructions

### ISSUE THREAD

**Issue by pixelrust** [twstrike/coyim#255]
Re: https://github.com/twstrike/coyim/

```
GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _ | cut -d '_' -f 1-2)
go get -u -tags "gtk_${GTK_VERSION}" github.com/twstrike/coyim
```

Is this meant to be a single command or two separate commands?

If it's a single command, shouldn't `\` be added before `go get...` ?

Otherwise, isn't `export` needed before `GTK_VERSION=....`?

(personally I thought these instructions were  2 separate commands, but I found I had to add `export` in order to make it work and complete the installation. Later, I realized the same result should be achieved by writing everything on a single line).

**Comment by tdruiva** [comment]
> Is this meant to be a single command or two separate commands?
> If it's a single command, shouldn't \ be added before go get... ?
> Otherwise, isn't export needed before GTK_VERSION=....?

Yeah, you're right. Is 2 commands, we should have the `\` or the `export`

**Comment by juniorz** [comment]
Yes, this is supposed to be two commands and there is no need for the export.

**Comment by juniorz** [comment]
By the same reason, this should work without `export`:

```
$ FOO="YEAH"
$ echo $FOO
YEAH
```

**Comment by olabini** [comment]
@juniorz it depends on whether the shell spawns a subshell for each line or not - some shells do, some don't.

"export" makes the variable available in subshells, without export, it only sets it in the current shell.
