### ISSUE TITLE
Bugs after gtka merge

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#259]
- [x] Need to remove Gotk3 in gopath, otherwise rightclick will crash the app
- [x] gui/hacks_darwin.go `cannot use gtki.STYLE_PROVIDER_PRIORITY_USER (type gtki.StyleProviderPriority) as type uint in argument to g.gtk.AddProviderForScreen`
- [x] localization(i18n) of account menu is not working 
- [x] crashes when close notification bar (see log [here](https://gist.github.com/tdruiva/284666994b6fdd314930))

**Comment by tcz001** [comment]
https://github.com/twstrike/coyim/commit/1534d0797cfd2c7011b1e79d830d4a8801403109

**Comment by tcz001** [comment]
@olabini What's the reason to comment [these two lines](https://github.com/twstrike/coyim/blob/master/i18n/localize.go#L7), I tried to change it back, it works fine.

**Comment by olabini** [comment]
I think it's all done now.
