### ISSUE TITLE
Use Snap CI (and Docker) if we want to

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#26]
We have access to Snap Docker Preview and we can use docker images to build and test:

    sudo docker build -t twstrike/coyim ./ci/Dockerfile
    sudo docker run --rm twstrike/coyim

**Comment by tdruiva** [comment]
Nice!

**Comment by olabini** [comment]
Do we have this working? What would be the benefits over continuing with Travis?

**Comment by juniorz** [comment]
The difference is we have access to a docker environment, meaning we could build docker images as part of our pipeline.

At the moment, we are not building the gui version as part of our travis pipeline. If we have any problem due lack of gtk2-dev packages we could use docker images. I was also afraid of needing to install packages not supported on travis if we want to do reproducible builds.

We could also test on different flavors of linux if we need to.

**Comment by juniorz** [comment]
And it seems we're gonna need this.

`gotk3/gotk3` requires GTK 3.6-3.16, but Travis boxes run `ubuntu:precise` which only has `libgtk-3-dev_3.4.2` [1]

1 - https://travis-ci.org/twstrike/coyim/jobs/85229840

**Comment by olabini** [comment]
OK, we are running well on Travis and Snap Docker support seems to be too early days. Let's revisit this for the next project.
