### ISSUE TITLE
Add deb packaging

### ISSUE THREAD

**Issue by codeadict** [twstrike/coyim#260]
Would be nice to add packaging for Debian based distros.

**Comment by SleuthKid** [comment]
There is a ITP for debian now: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819469
But packaging for debian would require all dependencies to be part of the packages maintained by the go-pkg team (http://pkg-go.alioth.debian.org/packaging.html).

As coyim is using Godeps this also probably requires patching of all imports all over the coyim source code for the debian go toolchain to work.

**Comment by olabini** [comment]
Thanks for the information.

**Comment by satta** [comment]
BTW, I have resurrected this and packaged the necessary dependencies for Debian, took care of the unvendoring and prepared a package for CoyIM. These are ready for upload and should get into Debian in the next couple of days. I have also sent an email to the ITP author letting them know about my work and will follow up on their reply.

**Comment by olabini** [comment]
Wow, fantastic work! Thanks!

**Comment by satta** [comment]
Done! 0.3.7 is now in Debian unstable and will hopefully make it into stretch! :)

**Comment by olabini** [comment]
Wow, that's really cool!
