### ISSUE TITLE
Fix colors for dark mode

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#263]
If you use the dark Gnome mode, some colors don't change which creates a semi-bad experience. We should deal with this.

**Comment by tcz001** [comment]
Gnome user should deal with this :100:

**Comment by xSmurf** [comment]
This has been on my radar for a bit as I'm actually a gnome dark theme user. The setting needs to be looked up in gsettings under the `gtk-application-prefer-dark-theme` key.

Just bumping for now but maybe I will take it on later (or sooner).

**Comment by olabini** [comment]
OK, merged and pushed! Thank you!
