### ISSUE TITLE
We should protect/lock memory from getting swapped

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#264]

**Comment by tcz001** [comment]
According to [this discussion](http://grokbase.com/t/gg/golang-nuts/138ess1xtr/go-nuts-how-to-secure-variables-in-memory), Go seems to use a non-compacting GC, and in that case we have to lock it by syscall and probably only allocate memory

**Comment by olabini** [comment]
Looking into this, it seems more and more unfeasible to do this for us. The problem is that we have key material all over the place, and in order to use something like mlock we would need to identify those areas and turn them into native types that can be mlocked - and we would need to provide the same functionality to the other platforms.

I'm not giving up on it, but right now I'm not sure how to do it in a good way.

**Comment by olabini** [comment]
Closing for now.
