### ISSUE TITLE
Entry or TextView

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#265]
After another round of discussion with @xSmurf we came to an agreement around the input method for sending messages. What we want is something like that has this behavior:
- Works well with multiple lines of input
- Sends the message on enter
- Can insert a newline in the box with ctrl+enter
- The box should grow to two or three lines of text, and then stop growing and add a scrollbar, when too much text is added.

**Comment by tcz001** [comment]
Why send on enter, newline on ctrl+enter?
I prefer ctrl+enter for send and enter for newline, because it feels more safe, especially while you are typing a lot.

**Comment by olabini** [comment]
Primarily because of usability. Oneliners will be MUCH more common than multiline statements, on the order of 1 to 50 or 1 to 100. Making the more common action take an extra key doesn't feel very user friendly to me.

**Comment by tcz001** [comment]
Well I understand, for users in Asia, we did things different, I need to `enter` when mixin English words and Japanese input will also have enter for each Character

**Comment by olabini** [comment]
Hmm. Interesting. So "enter" would be a bad solution for Asian languages? How does other clients solve that problem? Should we detect the language used and have either shift-enter or enter depending on what kind of language? Thoughts, @xSmurf?

**Comment by tcz001** [comment]
We can firstly have this solution, and then consider the global east :P

**Comment by olabini** [comment]
OK, but it would still be great to know how global east solves the problem. =) Any thoughts?

**Comment by tcz001** [comment]
We just use the opposite way to handle it, enter for newline, ctrl+enter for sending

**Comment by tcz001** [comment]
I think we can detect the locale but for now, I don't think it necessary.

**Comment by olabini** [comment]
OK, will add the option to do it that way. Thanks.

**Comment by olabini** [comment]
OK, almost everything works now - except for the small stuff around when the resizing of the window happens. A few more small annoying things to sort out with that.

**Comment by xSmurf** [comment]
Re <enter> vs <ctrl+enter>, maybe this is a good candidate for the start of a preferences pane with some user configurable options (I could see the unified mode going in there as well for example)? Detecting the locale might work as well, but it's not guaranteed it will match the user's input mode (ie: a user could be using the system in English and have Japanese keyboard configured or vice versa).

**Comment by olabini** [comment]
Yeah, it's starting to get time. I feel uneasy about trying to do it with heuristics as well.

**Comment by xSmurf** [comment]
Yeah it seems like unnecessary complexity when a simple settings flags would do just fine :)

**Comment by olabini** [comment]
OK, this is done. It currently doesn't allow for changing the enter/shift-enter behavior. I want to create a new ticket for the global pref menu. Need to figure out whether it's time to integrate gsettings as well. =/
