### ISSUE TITLE
Adding jabber.otr.im to default list of jabber servers to register new account on

### ISSUE THREAD

**Issue by DrWhax** [twstrike/coyim#266]
jabber.otr.im offers a free and secure Jabber service that anyone can use by registering an account through your favorite chat client.

Finally, this server has a special quirk. It forces communication to be OTR encrypted, thus cleartext messages between clients is impossible. With the help of Riseup, we have developed a prosody plugin to achieve mandatory OTR communication.

Our onion service: 5rgdtlawqkcplz75.onion

Adding this server might be of interest to include it in the list of servers to register new accounts on.

David Goulet and Myself are administrating this specific machine.

**Comment by olabini** [comment]
This, we should definitely add that.

**Comment by olabini** [comment]
Ah, I'm stupid, we added that way back: https://github.com/twstrike/coyim/blob/master/servers/known.go#L31

**Comment by olabini** [comment]
Ah, I'm an idiot - you meant for the registration place.

**Comment by DrWhax** [comment]
Indeed so!
