### ISSUE TITLE
Support for ping command

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#268]
Almost every server supports sending manual ping commands, it's rather useful for checking that you are still connected to a server and that the connection didn't go stale. It would be great if it were possible to trigger this from the contextual menu or the account menu. This is implemented using [XEP-0050](https://xmpp.org/extensions/xep-0050.html).

**Comment by olabini** [comment]
The current heartbeat code is pretty aggressive, so it should be very visible anytime your connection goes down. That said, if a manual ping is something that would be useful, I suspect it should be easy to add, maybe on the context menu per account?

**Comment by tdruiva** [comment]
Hey @olabini @xSmurf, to check...
This ping to certify if account stiil connected to server is the same as decribed here in [XEP-0199: 4.2 Client-To-Server Pings](https://xmpp.org/extensions/xep-0199.html#c2s)

**Comment by olabini** [comment]
It seems to me that XEP-199 is the right way to do this, yes.

**Comment by olabini** [comment]
So I think the behavior we want here is very simple - on the context menu for the account name, we allow a Ping to be sent. This will send one of the IQ pings from XEP-199. After a timeout of 10 or 20 seconds, if we don't get an answer, we go through the same flow of reconnecting as when an internal ping times out.

**Comment by tdruiva** [comment]
![screenshot from 2016-08-24 15-39-27](https://cloud.githubusercontent.com/assets/1254745/17947161/233e7cdc-6a11-11e6-8465-5315f239c3a6.png)

Also, do menu item should be "Check Connection" or this can be only "Ping"?
