### ISSUE TITLE
"Tor is not currently running" endless loop

### ISSUE THREAD

**Issue by vitalyster** [twstrike/coyim#269]
I have remove tor from proxies list, but still can not connect

**Comment by tcz001** [comment]
which version are you using? master shouldn't have this problem anymore

**Comment by vitalyster** [comment]
@tcz001 using dmg from the front page

**Comment by vitalyster** [comment]
And my friend on windows have the same problem

**Comment by tcz001** [comment]
Thanks for confirming, please try this latest version below, If problem still exist, I will take a look
https://bintray.com/twstrike/coyim/coyim-bin/master/view#files/master

**Comment by tcz001** [comment]
in Files "mac-bundle" is the dmg

**Comment by vitalyster** [comment]
works now, thanks
