### ISSUE TITLE
Enable InstanceTag support

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#27]
OTR3 is supporting InstanceTag for multi devices, but we also do some change on Client to make it possible

**Comment by juniorz** [comment]
I'm not sure this is necessary since `otr3` already handles everything related to ignoring the messages.

**Comment by olabini** [comment]
Not sure about this. Don't we need to save instance tags and set them etc?

**Comment by olabini** [comment]
Since they are supposed to be long-lived.

**Comment by tcz001** [comment]
instance tags is auto-generated by OTR during AKE

2015-09-25 17:53 GMT-05:00 Ola Bini <notifications@github.com>:

**Comment by olabini** [comment]
Yes, they are. But they shouldn't be if we have one since before. The OTR spec says instance tags should be long lived.

**Comment by juniorz** [comment]
I was going to ask the same. I remember Ola mentioning that libotr
stores them.

On 9/25/15 5:57 PM, Ola Bini wrote:
> Yes, they are. But they shouldn't be if we have one since before. The
> OTR spec says instance tags should be long lived.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twstrike/coyim/issues/27#issuecomment-143371621>.
> 

-- 
*Reinaldo de Souza Jr* | Software Developer
*Thought*Works Brasil
