### ISSUE TITLE
Support for XMPP resources

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#277]
XMPP users can be connected in multiple places, it is currently impossible to know which resources of a contact one is talking to. At the very minimum the resource should probably be displayed somewhere. While normally letting the server select the highest priority resource is fine, there are cases where one might want to be able to select which resource to talk to.

**Comment by olabini** [comment]
Not sure about the design of this. Ideally this should be three parts: show which resource you're talking to, show which resources are currently available for a peer, and decide to start a conversation with a specific resource.
I'm punting on this for the second, and will get back to it next week or so.

**Comment by xSmurf** [comment]
For selection I like Gajim's design, right click on a user with multiple resources and it allows you to open a chat with a specific resource.

**Comment by xSmurf** [comment]
At the very minimum (for the short term) I think CoyIM *must* reply to messages with the full jid (jid/resource) and not just the bare JID.

I have not confirmed this but I have a hunch it is making it impossible for some people to initiate OTR sessions in the following scenario:

User A uses pidgin on Computer 1
User B uses CoyIM.
A<>B initiate an OTR session.
User A connects to XMPP on Computer 2 and that computer has a lower resource priority than Computer 1
User A on Computer 2 tries to initiate a new session
User B replies to the session negotiation with the bare JID
Server sends the negotiation reply to the higher priority JID on Computer 1
Negotiation fails, time to call a strike!

**Comment by xSmurf** [comment]
Use A just told me that they get the following message which confirms my suspicions:

```
(07:30:52 PM) scrubbed@domain.tld has sent a message intended for a different session. If you are logged in multiple times, another session may have received the message.
```

**Comment by olabini** [comment]
We have some other issues with resources that need to be solved as well, since we are not fixing the receiver right now.

**Comment by olabini** [comment]
I've opened more specific issues, #327 and #328 in order to track the two specific features in this discussion. I'll close this one instead.
