### ISSUE TITLE
Registration and general login of accounts in SubgraphOS fail

### ISSUE THREAD

**Issue by RooneyMcNibNug** [twstrike/coyim#278]
Hi.

I am using Coy within SubgraphOS alpha (x64) and am having issues with both logging into already existing xmpp accounts and registering new ones.

I am able to add a per-existing account to Coy, so that it appears in the accounts list, but in attempting to connect it continues to ask for my password over and over, echoing multiple password prompt windows, and never connecting when I put them in correctly.

FYI I am using KeepassX to copy/paste the passwords from for each account I have tried so far, but I don't believe this to be the root of the issue.

In terms of registering for a new jabber account within Coy, It says that the account was successfully created (I tried with multiple jaber.ccc.de accts), but then the aforementioned password issue continues where it attempts to connect over and over again, presenting me with several password prompts, but never actually accepting the correct password. The connect loop runs seemingly nonstop until I force the account to disconnect via right-click > "Disconnect".

Please let me know if any further information is needed, and I can provide screenshots later if necessary.

Thanks,
- RooneyMcNibNug

**Comment by iapazmino** [comment]
This was fixed at #257 
@RooneyMcNibNug CoyIM needs to be updated in SubgraphOS

**Comment by RooneyMcNibNug** [comment]
`dpkh -l | grep coy`

returns..

`ii coyim       0.2-4`
`ii coyim       A safe and secure chat client`

I believe this is running the latest version? Apologies if I'm mistaken.

**Comment by xSmurf** [comment]
@olabini I think you can close this. The version we are packaging is definitely lagging behind quite a bit.

@RooneyMcNibNug We are packaging the version in SubgraphOS ourselves and have fallen behind, we will update promptly. Feel free to open a ticket in https://github.com/subgraph/subgraph-os-issues/issues :)

**Comment by olabini** [comment]
Great, closing it for now.
