### ISSUE TITLE
UX/UI on developer options menu 

### ISSUE THREAD

**Issue by alisonLFP** [twstrike/coyim#279]
Many users will ignore this menu because it sounds like something advanced that they shouldn't touch. All the options under it relate to encryption. Change the name to something like "encryption".

**Comment by olabini** [comment]
Actually, the reason why it's named that way is because it is going to go away - we want to have a better experience for these options than just menu choices with confusing names. However, we've been a bit overrun so haven't had the chance to design that experience yet. Bear with us!

**Comment by alisonLFP** [comment]
Ola Bini:
> Actually, the reason why it's named that way is because it is going to go away - we want to have a better experience for these options than just menu choices with confusing names. However, we've been a bit overrun so haven't had the chance to design that experience yet. Bear with us!

Sorry to be impatient. :) Thanks for all your work on this.

Alison

**Comment by olabini** [comment]
No worries. I'll close this ticket for now.
