### ISSUE TITLE
What should the default UI be?

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#28]
What do we plan to have as the default UI: GUI or CLI?

We can use [build tags](https://golang.org/pkg/go/build/) to enable the alternative UI (or disable the default UI).

For instance, `pond` client defaults to GUI. If you want to build a CLI version, you can use the build tag `nogui`: `go get -tags nogui github.com/agl/pond/client`

**Comment by iapazmino** [comment]
I would say GUI is the default and users who what they are doing would get a nogui instance.
This goes under the assumption this product is mainly aimed to regular users instead of power/technical users.

**Comment by tcz001** [comment]
I would prefer to provide a binary release/installer instead of letting regular users to build aganst our source code.

**Comment by juniorz** [comment]
See: ab11fbb19ba4f0a1fbe915aa9b561418c080537c

For now, `go get github.com/twstrike/coyim` build a CLI version (it's essentially an improved version of `xmpp-client`). If you want the GUI, `go get -tags nocli github.com/twstrike/coyim`.

There's also two make targets: `build` and `build-gui`.

We can change this when we have something usable for the GUI.

**Comment by juniorz** [comment]
We are moving forward with GTK for now.

**Comment by olabini** [comment]
I think long term we should default to CLI for the build yourself case. This will likely be for people who don't want to drag in GTK dependencies and all that stuff, so they will always build from source. The packages will be default GUI.
