### ISSUE TITLE
Notify user when encrypted chat ends

### ISSUE THREAD

**Issue by alisonLFP** [twstrike/coyim#280]
There's a notification at the start of the encrypted chat, but not the end.

**Comment by olabini** [comment]
Hm. There are two different places where an encrypted chat ends - can you specify which one you mean?
- When the OTHER user ends their conversation in whatever way
- When the user presses end conversation on the Developer menu

Actually, both those should give a notification - which version are you using?

**Comment by alisonLFP** [comment]
Hi Ola,

Ola Bini:
> Hm. There are two different places where an encrypted chat ends - can you specify which one you mean?
> - When the OTHER user ends their conversation in whatever way

Just tested this. When the other user ends her conversation, I get a
notification that the private conversation has been lost.

> - When the user presses end conversation on the Developer menu

When I do this, I get no notification, UNLESS I send a new message to
the other user and then it says "private conversation lost" and then
immediately "attempting to start a private conversation". So then
there's a message that goes through (or seems to go through)
unencrypted, and it's the sending of that message that prompts the
notification that my private convo has been lost.
> 
> Actually, both those should give a notification - which version are you using?
> 

It's version 0.2 from the CoyIM site. I'm testing on Debian. I haven't
tried CoyIM yet in SGOS but after talking to Smurf about this it seems
to be an issue with the site having an older build. For example, I also
don't have the unified UI, but separate windows.

Alison

**Comment by olabini** [comment]
Ah, great. Saying the conversation was "lost" might not be the best user experience. Should revisit this.
Also, no message will go through unencrypted from your end, if you haven't turned off OTR encryption (which we don't support right now). If you send a message when no session is running, it will cache the message and send it once the actual OTR session has been started. This is not obvious from the UI either. I'll keep this ticket open until I can create separate issues for those specific things.

We should probably also notify immediately that the OTR session has been torn down when you choose that from the menu.

Thanks for giving the version information. The 0.2 on the site is also fairly old at this point - we are gearing up to release a 0.3 this week, and there will be a huge amount of changes in there.

Incidentally, you won't get the unified view by default even with the newer versions - for now you have to give the command -single-window to the command line to get the unified view. We are aiming to put this as a configuration option somewhere, but haven't gotten around to it yet.

**Comment by alisonLFP** [comment]
Ola Bini:
> Ah, great. Saying the conversation was "lost" might not be the best user experience. Should revisit this.
> Also, no message will go through unencrypted from your end, if you haven't turned off OTR encryption (which we don't support right now). If you send a message when no session is running, it will cache the message and send it once the actual OTR session has been started. This is not obvious from the UI either. I'll keep this ticket open until I can create separate issues for those specific things.
> 

Thanks for your attention to this!

> We should probably also notify immediately that the OTR session has been torn down when you choose that from the menu.

Yep, I think that would be useful, especially since I don't think it's
clear that you can't have an unencrypted conversation.

> 
> Thanks for giving the version information. The 0.2 on the site is also fairly old at this point - we are gearing up to release a 0.3 this week, and there will be a huge amount of changes in there.
> 
> Incidentally, you won't get the unified view by default even with the newer versions - for now you have to give the command -single-window to the command line to get the unified view. We are aiming to put this as a configuration option somewhere, but haven't gotten around to it yet.

Good to know! Thanks Ola!

Alison

**Comment by olabini** [comment]
Yeah, I would like to make it more clear that by default there is no way to send anything unencrypted in general, but I have no idea how to actually communicate that in a useful non-intrusive way. If we have any brilliant flashes of UX insight on that subject, do let us know!

Thanks.

**Comment by alisonLFP** [comment]
Ola Bini:
> Yeah, I would like to make it more clear that by default there is no way to send anything unencrypted in general, but I have no idea how to actually communicate that in a useful non-intrusive way. If we have any brilliant flashes of UX insight on that subject, do let us know!
> 
> Thanks.

Testing it a bit further to try to think through how that might look. I
think you could add some text in one of the notifications you get at the
beginning of the conversation, eg "Verified conversation started. Please
note: all conversations on CoyIM are encrypted by default". That is a
bit wordy, but if it's along with the other notifications that show up
with new conversations, it's not really intrusive.

Something else I observed while thinking about this...the attached
message ("you are talking over an unencrypted channel") is misleading if
there is no way to have an unencrypted conversation on CoyIM.

Thanks for all your work on this. I will probably contribute a lot of UX
suggestions over time, so I hope that doesn't get annoying. :D

Alison

**Comment by xSmurf** [comment]
@alisonLFP 

> Something else I observed while thinking about this...the attached message ("you are talking over an unencrypted channel") is misleading if there is no way to have an unencrypted conversation on CoyIM.

The thing is it is possible, but jumping through some hoops, to actually send en unencrypted message so that message is still relevant. That feature may or may not go away in the future, but people still want it (to communicate with people who don't have OTR and to send unencrypted offline messages)

**Comment by olabini** [comment]
Yeah, but the point remains - we need to revisit the exact messages and try to figure out how to make them more heloful
