### ISSUE TITLE
Reproducible builds: Create docker instances for Linux building

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#284]
- Create two docker definitions that will compile linux x86 and x64 reproducibly
  - Use faketime and other reproducibility techniques
  - Base them on something like basic Debian with minimum libraries installed (make sure it's a base image that won't change, that we have a checksum for etc)
  - Install the needed dependencies (GTK is probably the only big one)
  - Build Golang from scratch (download a specific src-ball, verify checksum) (1.5.3 or something for now)
    - We don't need Golang to build reproducibly - just that it generates the same binary when we compile
  - Build CoyIM, link it against the lowest GTK version we will support. Let's make it 3.10.
  - This should generate the same binary no matter if it's run on Linux or OS X.

**Comment by juniorz** [comment]
I don't understand the difference between "generating the same binary" and "building reproducibly". For example, in:

> We don't need Golang to build reproducibly - just that it generates the same binary when we compile.

**Comment by olabini** [comment]
What I meant is this:
we don't need the build of Go itself to be reproducible. Even if the "go" binary is different over different builds, as long as it still generates the same "coyim" binary, we are fine.

**Comment by olabini** [comment]
The latest commits have finished implementing this work. We now have reproducible builds for Linux on AMD64, which means v0.4 will make it possible to have signed releases on Linux!
