### ISSUE TITLE
Removing a group for someone should persist

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#288]
We can do this either by saving "negative"s locally, or we can update the server. I prefer the first alternative.

**Comment by juniorz** [comment]
So we don't update the server on additions, but update on removals?

This would be very surprising if I add groups under the promise coy wont mess up with my online group information (for privacy reasons), but then I remove a group and coy changes my online gorup information.

**Comment by olabini** [comment]
Well, as I said in the text, I prefer the alternative that doesn't update the server.

**Comment by juniorz** [comment]
Or we could ignore remote group information if a local group information is available, rather than merging both (as I believe it currently works).

**Comment by juniorz** [comment]
An empty local group information would mean you have removed all existing remote groups from the local contact information, and a not empty local group information would mean you have changed the remote group information locally (initially merged with the remote).

Your local information is the authoritative group information in both cases.
