### ISSUE TITLE
TLS handshake do not timeout

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#29]
We noticed something weird today. `coyim` hanged during the `Starting TLS handshake` and did not time out.

We suspected something was wrong with my Tor, then we found this in the logs

```
Sep 22 10:20:39.000 [notice] Your system clock just jumped 2034 seconds forward; assuming established circuits no longer work.
Sep 22 10:22:53.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:5222. Giving up. (waiting for circuit)
Sep 22 10:22:59.000 [notice] No circuits are opened. Relaxed timeout for circuit 41 (a General-purpose client 3-hop circuit in s
tate doing handshakes with channel state open) to 139912ms. However, it appears the circuit has timed out anyway. 14 guards are
live.
Sep 22 10:23:00.000 [notice] Tor has not observed any network activity for the past 2181 seconds. Disabling circuit build timeou
t recording.
Sep 22 10:23:00.000 [notice] Our IP address has changed.  Rotating keys...
Sep 22 10:23:00.000 [notice] Tor now sees network activity. Restoring circuit build timeout recording. Network was down for 2181
 seconds during 1 circuit attempts.
Sep 22 10:23:01.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Sep 22 10:23:01.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Sep 22 12:41:57.000 [notice] Catching signal TERM, exiting cleanly.
```

The weirdness happened during the time in between the last two lines on the log.

After restarting Tor, everything worked fine.

We should at least timeout the connection when it takes too long to do the TLS handshake.

**Comment by olabini** [comment]
Tor is pretty not-so-good when it comes to noticing that the network is down, so this could be part of the problem as well. Timing out is definitely a good fix on our side.

**Comment by olabini** [comment]
I have fixed at least two places where we didn't time out the dialing process at all (SRV lookup, and initial dial). I've set the default timeouts to these pretty low, so we might have to adjust that. Also, when a timeout happens, it proceeds to ask for a custom server entry, which isn't really right for a timeout issue. Not sure how we should handle this. Connection failures shouldn't automatically mean we ask for a custom server, right?

**Comment by juniorz** [comment]
https://xmpp.org/rfcs/rfc6120.html#tcp-resolution-prefer says:

> If the initiating entity receives a response to its SRV query but it is not able to establish an XMPP connection using the data received in the response, it SHOULD NOT attempt the fallback process described in the next section (this helps to prevent a state mismatch between inbound and outbound connections).

Although we were following this, we were not making any distinction and we asked for a custom server even if the SRV lookup succeeded but failed to connect.

I suspect we only want to ask for a custom server if there was no SRV records and it failed to connect using the fallback. If there was SRV records but it failed to connect to all of them, we know the address is correct but the server is offline.

Does it make sense?

**Comment by olabini** [comment]
Yeah, that sounds good to me.
