### ISSUE TITLE
Input TextView first line too small to view text

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#293]
The new TextView input field is too small to view the first line, after adding another line it seems to be calculated properly. This is under go1.6 and unified layout, I did not try replicating under go1.5.x or multi-window layout.

![coyim_input_toosmall_1](https://cloud.githubusercontent.com/assets/525356/14021525/c39ed17e-f1d3-11e5-87ef-37b35f0eaa68.png)

![coyim_input_toosmall_2](https://cloud.githubusercontent.com/assets/525356/14021543/d28e281a-f1d3-11e5-8dbc-b56c5fdd0a35.png)

**Comment by olabini** [comment]
Hm, I didn't try the single-window layout. Will try.

**Comment by olabini** [comment]
OK, I see it. Will see if I can fix.

**Comment by olabini** [comment]
Have pushed a fix for this - will try to get a new release out later today with this and some other things.
