### ISSUE TITLE
Hide empty groups or groups with noone online

### ISSUE THREAD

**Issue by duritong** [twstrike/coyim#296]
It would be nice to be able to hide groups that are empty or where noone is online.

This would make the ui much less cluttered

**Comment by xSmurf** [comment]
In the same line, it would be nice if the contact list remembered the collapsed status of groups.

**Comment by olabini** [comment]
You mean between restarts?

**Comment by xSmurf** [comment]
@olabini yeah exactly.

**Comment by olabini** [comment]
Yep. That would be great. We should try to save it in gsettings instead of the conf file, but I want to make sure to not leak group names etc. Make run the groupname through a kdf with some secret value from the config file, and then use that to store setting information.

**Comment by xSmurf** [comment]
That sounds very reasonable (albeit obviously more complex). Fir sure the original feature request from the ticket (hiding empty groups) is much easier and is already helpful as is.

**Comment by olabini** [comment]
I've opened #303 and #304 to track the other things in here.
