### ISSUE TITLE
Not able to send messages

### ISSUE THREAD

**Issue by duritong** [twstrike/coyim#299]
I'm just playing around with coyim (0.3.1) and I'm using awesome as my window manager. Unfortunately, I'm not able to send a message to one of my peers, because there is no send button in the message window, nor does pressing ```enter```, ```ctrl```+```enter```, ```shift```+```enter``` and what not send the message. It's just adding line breaks to the input window, as you can see on my screenshot.

![no_send](https://cloud.githubusercontent.com/assets/9511/14042044/8fa0f980-f276-11e5-9b88-44782888475a.png)

Even if I go in floating (not tiling) or full screen mode, I'm not able to send a message at all.

Also coyim doesn't seem to register with an icon in the widget bar, I'm not sure it does either on other windows managers. And it also lacks an exit/quit shortcut/menu entry, as on a tiling WM you might not have any window decorations to close/exit a program.

**Comment by olabini** [comment]
Hi, sorry that you're having trouble.
CoyIM is using GTK and is fairly deeply integrated with Gnome. If awesome doesn't send key events correctly (which it sounds like from your problem), there isn't much we can do about that. 

We currently do not have a .desktop file which I assume is what is needed for entries into the desktop environment. Hopefully that will come at the same time as proper packages (.deb's and .rpm's). 

Actually, CoyIM follows the standard guidelines for shortcuts. We don't have a menu item, but we do support Ctrl+W and Ctrl+Q as it's supposed to work. If those aren't working for you, it might be due to the same problem with key events as mentioned above.

**Comment by olabini** [comment]
It would be great if you had a pointer to what awesome does differently around the key events - otherwise it will be quite hard for us to debug.

**Comment by duritong** [comment]
I was wrong ctrl+w and crtl+q works perfectly fine. Only enter is not working correctly, which is weird as awesome should be pretty standard and I don't think it sends keystrokes any differently.
I will try to investigate it further...

**Comment by duritong** [comment]
So I went forward and logged in into my standard Fedora 23 gnome setup and messages are also not sent when pressing enter. I get the exactly same behavior as with awesome.
Do you have any suggestions how I could provide you with more information regarding e.g. which keystrokes gtk gets?

**Comment by olabini** [comment]
Uhm, that's extremely strange! I'm using Fedora 23 for development. I'm afraid the only solution for you would be to build a custom version of Coy with some extra logging added. If you want to go down that path, check out the v0.3.1 branch, apply this patch: https://gist.github.com/olabini/9a15ed8f6abb33177536 and rebuild and try. Run coyim with the -debug flag to see the output.

**Comment by iseeareddoor** [comment]
I experience the same problem using i3wm, a patched build of 0.3.1 gives the following output when I press the enter key:

    [CoyIM] ... go/src/github.com/twstrike/coyim/gui/conversation.go:264: isInsertEnter(state=16, keyVal=65293)
    [CoyIM] ... go/src/github.com/twstrike/coyim/gui/conversation.go:264: isInsertEnter(state=16, keyVal=65515)

**Comment by iseeareddoor** [comment]
found the root cause: num lock on => enter broken, num lock off => enter works
with num lock off the log shows that state is 0..

**Comment by olabini** [comment]
Perfect, thanks! That's exactly what we need to fix it. Sorry about that.

**Comment by olabini** [comment]
This fix should be in a new release sometime this week. Thanks for your patience.
