### ISSUE TITLE
Investigate GUI frameworks and decide on the most appropriate one

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#3]

**Comment by tcz001** [comment]
I'm looking into the ui options for Go, it seems there's no official native support, if we want a GUI talking with go in-memory, I guess andlabs/ui is the only choice. 
Or if we can treat otr as a binary-tool or a service like Enigmail+GnuPG does (which ‘may’ have vulnerability), then options will be much more XPCOM/Qt/GTK/Webkit blablabla.

Ps: try cgo is another option which I haven't got time to look into.

**Comment by tcz001** [comment]
## GUI

*Libraries for building GUI Applications*

* [go-gtk](http://mattn.github.io/go-gtk/) - Go bindings for GTK
* [go-qml](https://github.com/go-qml/qml) - QML support for the Go language
* [gosx-notifier](https://github.com/deckarep/gosx-notifier) - OSX Desktop Notifications library for Go.
* [gotk3](https://github.com/conformal/gotk3) - Go bindings for GTK3.
* [gxui](https://github.com/google/gxui) - A Go cross platform UI library.
* [ui](https://github.com/andlabs/ui) - Platform-native GUI library for Go.
* [walk](https://github.com/lxn/walk) - Windows application library kit for Go.

**Comment by juniorz** [comment]
We should also take into account which OS we are targeting. For instance, `go-qml` requires Qt (> 5.0.X) and `go-gtk` requires GTK.

Tails includes GNOME (https://tails.boum.org/doc/about/features/) which contains GTK+ runtime. If we choose `go-gtk`, Tails doesn't need to add a new runtime dependency to be shipped with `coyim`. I'm not sure about Qt being included in Tails.

I'm biased towards the declarative aspect of QML though.

**Comment by juniorz** [comment]
By the way, `go-gtk` can't be built on OSX for now (https://github.com/mattn/go-gtk/issues/245)

**Comment by olabini** [comment]
So, we need something that can work well on Windows and OS X. We need something that works in Tails. We need something that preferably has a small attack surface on native code.

Did you look at gxui and gotk3?

**Comment by olabini** [comment]
I did a survey of the different GUI frameworks available. All of them seem very immature and doesn't work well outside of Linux. For now we should just use GTK. We should make sure to separate out the GTK specific code as much as possible - in fact, I would prefer if we only refer to the GTK packages from inside of coyim/gui
