### ISSUE TITLE
Tabbed conversation windows

### ISSUE THREAD

**Issue by cubi7** [twstrike/coyim#300]
Is it possible to get the option for tabbed conversation windows so it is not to have an individual window per conversation?

**Comment by xSmurf** [comment]
This already exists, start CoyIM with the `-single-window` flag. :)

**Comment by olabini** [comment]
As Smurf said, start with the flag! We would like to expose this setting in a more obvious place in the UI later, but for now the flag is the way to do it.

**Comment by cubi7** [comment]
@xSmurf @olabini thank you.  I missed that option.

Have you thought of adding github wiki to document such switches so people like me don't crreate needless ticket? :)

**Comment by xSmurf** [comment]
@cubi7 that option will probably be migrated to an actual preferences/configuration panel at some point in the future which should make it easier to find.
