### ISSUE TITLE
OTR error flood still happens

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#301]
Not sure how I managed to make it happen, but a loop of errors started between two CoyIM instances. This manifests as thousands of "We received an unreadable encrypted message. It has probably been tampered with, or was sent from an older client." messages. We should probably recognize this situation quickly, and bail out in some way. Not sure how the other clients deal with this - there must be some subtle difference in how we do OTR.

**Comment by xSmurf** [comment]
+1 on this, I'm getting these quite often these days, specially when talking to other contacts that use CoyIM, or when trying to send a message to a contact which doesn't support OTR at all and the negotiation fails (it spams them).

**Comment by olabini** [comment]
Yeah, I'll have to figure this one out at some point. Sorry about that.

**Comment by olabini** [comment]
Having trouble replicating this at the moment. @xSmurf - do you have a way of replicating it?

**Comment by olabini** [comment]
OK, I have replicated it
Managed to make one thing happen by saying something, and then saying something again, before the OTR session was set up. There has to be a timing thing happening here though, because it doesn't happen every time.

**Comment by olabini** [comment]
Will try to describe the pattern of events here

**Comment by olabini** [comment]
(this is when both sides have require encryption turned on)

**Comment by olabini** [comment]
OK, so this is roughly what happens - the different OTR sessions established are indicated in square brackets before:

Alice says "Hi" -> Bob
(Coy recognizes we have no OTR, so stops the message from being sent and starts OTR session)
[O1] Alice sends "?OTRv23?" -> Bob
[O1] Bob sends an OTR Commit -> Alice
[O1] Alice sends an OTR Key -> Bob
Alice says "Bla" -> Bob
(Coy recognizes we have no OTR, so stops the message from being sent and starts OTR session)
[O2] Alice sends "?OTRv23?" -> Bob
[O1] Bob sends an OTR Reveal -> Alice
(At this point, Alice has gone secure, with session O1)
[O1] Alice sends an OTR Sig -> Bob
[O1] Alice resends "Hi" in an encrypted data message
[O1] Alice resends "Bla" in an encrypted data message
[O2] Bob sends an OTR Commit -> Alice
[O2] Alice sends an OTR Key -> Bob
Bob sends "?OTR Error: You sent encrypted data to a peer, who wasn't expecting it." -> Alice
   (for the "Hi" message - this is because O2 has already started for Bob, so Bob has no context for O1 anymore)
[O3] Alice sends "?OTRv23?" -> Bob
Bob sends "?OTR Error: You sent encrypted data to a peer, who wasn't expecting it." -> Alice
   (for the "Bla" message)
[O4] Alice sends "?OTRv23?" -> Bob
[O2] Bob sends an OTR Reveal -> Alice
(At this point, Alice is considered still secure, with session O2)
At this point, resend is tried
  it immediately fails, because we have started new contexts so we don't have a functioning session
  the resend messages are saved for later resend, with the "[resent] " prefix
[O2] Alice sends an OTR Sig -> Bob
[O2] Alice resends "[resent] Hi" in an encrypted data message
[O2] Alice resends "[resent] Bla" in an encrypted data message
[O3] Bob sends an OTR Commit -> Alice
[O3] Alice sends an OTR Key -> Bob
[O4] Bob sends an OTR Commit -> Alice
[O4] Alice sends an OTR Key -> Bob
Bob sends "?OTR Error: You sent encrypted data to a peer, who wasn't expecting it." -> Alice
   (for the "[resent] Hi" message - this is because O3/O4 has already started for Bob, so Bob has no context for O2 anymore)
[O5] Alice sends "?OTRv23?" -> Bob
etc etc etc

**Comment by olabini** [comment]
I do think we should consider checking if we started an OTR conversation recently, and in that case just wait for it to proceed.
