### ISSUE TITLE
Add support for displaying "/me" actions properly

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#307]
This one is definitely just a _want_ and not a _need_ but I feel like this is such a standard basic feature that is should really be there. :)

Also it's part of the XMPP sandard under [XEP-0245](https://xmpp.org/extensions/xep-0245.html)

**Comment by olabini** [comment]
Well, calling any XEP a standard is stretching it slightly. =)
Personally, I kinda hate this feature, but if others like it I can bend. @juniorz @iapazmino @tdruiva @tcz001  - thoughts?

**Comment by xSmurf** [comment]
For what it's worth, this is the patch for this:

```
diff --git a/gui/conversation.go b/gui/conversation.go
index 1653103..5feeb08 100644
--- a/gui/conversation.go
+++ b/gui/conversation.go
@@ -30,6 +30,7 @@ type conversationView interface {
 	displayNotificationVerifiedOrNot(notificationV, notificationNV string)
 	setEnabled(enabled bool)
 	isVisible() bool
+	formatMessage(form string, message []byte, outgoing bool) []taggableText
 }
 
 type conversationWindow struct {
@@ -581,19 +582,33 @@ func (conv *conversationPane) appendStatus(from string, timestamp time.Time, sho
 	conv.appendToHistory(timestamp, taggableText{"statusText", createStatusMessage(from, show, showStatus, gone)})
 }
 
-func (conv *conversationPane) appendMessage(from string, timestamp time.Time, encrypted bool, message []byte, outgoing bool) {
-	conv.appendToHistory(timestamp,
-		taggableText{
+const mePrefix = "/me "
+
+func (con *conversationPane) formatMessage(from string, message []byte, outgoing bool) []taggableText {
+	arHist := []taggableText{}
+	sep := ":  "
+	if string(message[:len(mePrefix)]) == mePrefix {
+		sep = " "
+		message = message[len(mePrefix):]
+		arHist = append(arHist, taggableText{
 			is(outgoing, "outgoingUser", "incomingUser"),
+			"* ",
+		})
+	}
+
+	return append(arHist, []taggableText{
+		{is(outgoing, "outgoingUser", "incomingUser"),
 			from,
 		},
-		taggableText{
-			text: ":  ",
-		},
-		taggableText{
-			is(outgoing, "outgoingText", "incomingText"),
+		{text: sep},
+		{is(outgoing, "outgoingText", "incomingText"),
 			string(message),
-		})
+		},
+	}...)
+}
+
+func (conv *conversationPane) appendMessage(from string, timestamp time.Time, encrypted bool, message []byte, outgoing bool) {
+	conv.appendToHistory(timestamp, conv.formatMessage(from, message, outgoing)...)
 }
 
 func (conv *conversationPane) displayNotification(notification string) {
```

**Comment by olabini** [comment]
Ping everyone?

**Comment by juniorz** [comment]
Well, I have no particular feeling regarding this feature. The XEP seems to be just about how/when apply a particular presentation to a message body.

I have no concern about merging it besides lack of test (at least for the presenting part).

**Comment by tcz001** [comment]
I'm not quite concerned about this, but adding feature like this is not on our prioritized list at least.

**Comment by tcz001** [comment]
And to the XEP description, it seems more frequently used in group chat, which we haven't considered yet.

**Comment by xSmurf** [comment]
I believe the focus of the XEP on MUC is because of special considerations regarding this use case, not because it is mainly used in the context of MUCs.

**Comment by olabini** [comment]
I'm fine with us doing this - although maybe we can have it turned off by default? I'm in the process of creating a preferences screen and gsettings, and this is setting will be included.
