### ISSUE TITLE
GTK default keybindings for Mac OS

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#31]
For example, I need to use CTRL+C , CTRL+V instead of CMD+C and CMD+V

**Comment by olabini** [comment]
So whiny! ;P

**Comment by olabini** [comment]
So we need to figure out how this works for GTK3 in order to do it, right?

**Comment by tcz001** [comment]
Didn't we added the darwin tag on travis build?
···
ack darwin
gover.coverprofile
395:github.com/twstrike/coyim/gui/style_darwin.go:163.30,165.16 2 0
396:github.com/twstrike/coyim/gui/style_darwin.go:170.2,171.16 2 0
397:github.com/twstrike/coyim/gui/style_darwin.go:165.16,168.3 2 0
398:github.com/twstrike/coyim/gui/style_darwin.go:171.16,173.3 1 0

gui/style.go
1:// +build !darwin

gui.coverprofile
164:github.com/twstrike/coyim/gui/style_darwin.go:163.30,165.16 2 0
165:github.com/twstrike/coyim/gui/style_darwin.go:170.2,171.16 2 0
166:github.com/twstrike/coyim/gui/style_darwin.go:165.16,168.3 2 0
···

**Comment by tcz001** [comment]
GTK_DATA_PREFIX in `CoyIM.app/Contents/MacOS/Coy` is the reason, If set, makes GTK+ use $GTK_DATA_PREFIX instead of the prefix configured when GTK+ was compiled.

**Comment by juniorz** [comment]
Does it mean `gui/style_darwin.go` has never worked?

**Comment by juniorz** [comment]
Or maybe it should also have been called inside GTK main thread.

**Comment by olabini** [comment]
It never worked once we updated to GTK3.

**Comment by juniorz** [comment]
I'll remove it.
