### ISSUE TITLE
Lots of PII in logs

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#311]
When running coyim in oz - I've found that coyim spits out a lot of messages - usually including the user names of peers (eg: a gmail user name). It would be nice if that debug information could be hidden entirely unless requested (eg: a debugging mode).

**Comment by olabini** [comment]
This is a bug that should be opened in Subgraph OS - CoyIM will by default not run in debug mode - you have to give it the -debug flag for that. My suspicion is that the .desktop file for SGOS adds that flag. @xSmurf correct?

**Comment by xSmurf** [comment]
Hey @olabini, no this isnt the debug information. @ioerror is referring to XMPP logging like:

```
>>> INFO Fetching roster
>>> INFO Roster received
>>> INFO Roster received
>>> ALERT While processing message from SCRUBBED@DOMAIN.TLD: otr: message not in private
>>> INFO SCRUBBED@DOMAIN.TLD has ended the secure conversation.
>>> INFO Secure session with SCRUBBED@DOMAIN.TLD has been automatically ended. Messages will be sent in the clear until another OTR session is established.
>>> ALERT While processing message from SCRUBBED@DOMAIN.TLD: otr: message not in private
>>> INFO Fetching roster
>>> INFO Roster received
>>> INFO Fetching roster
>>> INFO Roster received
```

**Comment by olabini** [comment]
Ah, ok - those are remnants from CLI xmpp-client and should be removed completely. Good point.
