### ISSUE TITLE
Importing .xmpp-client configs

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#312]
I'd like a way to easily import an old style .xmpp-client config. Especially useful would be extracting of seen/unknown/confirmed fingerprints. I don't see an easy way to *select* an old config for conversion. Is there one?

**Comment by xSmurf** [comment]
Does the "import fingerprint" in _account config > encryption_ not work with xmpp-client style files?

**Comment by ioerror** [comment]
On 3/30/16, xSmurf <notifications@github.com> wrote:
> Does the "import fingerprint" in _account config > encryption_ not work with
> xmpp-client style files?

It specifically says Pidgin/OTR format in the window - I haven't tried
it yet for that reason.

**Comment by olabini** [comment]
Actually, the import will automatically find old style .xmpp-client files, as long as you have them in the expected place - ~/.xmpp-client ~/Persistent/.xmpp-client, and any files in ~/.xmpp-client or ~/.xmpp-clients directories will be used.

**Comment by ioerror** [comment]
On 3/30/16, Ola Bini <notifications@github.com> wrote:
> Actually, the import will automatically find old style .xmpp-client files,
> as long as you have them in the expected place - ~/.xmpp-client
> ~/Persistent/.xmpp-client, and any files in ~/.xmpp-client or
> ~/.xmpp-clients directories will be used.

Ah - in my case - I have a dozen, in different places. Will it
properly treat everything as separated by account?
