### ISSUE TITLE
Sending message to "offline" user

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#313]
In xmpp-client, a user can /otr-start with any user in their buddy list. It would be nice to have a similar feature as many of my contacts lurk in an "offline" state. Thus they're not on the buddy list unless _all_ contacts are shown regardless of status.

**Comment by olabini** [comment]
Not sure I understand what feature you're looking for - you can show offline contacts - do you mean you want to send an OTR start to someone that is offline from the menu or something along those lines?

**Comment by ioerror** [comment]
On 3/30/16, Ola Bini <notifications@github.com> wrote:
> Not sure I understand what feature you're looking for - you can show offline
> contacts - do you mean you want to send an OTR start to someone that is
> offline from the menu or something along those lines?
>

Basically, I think a window that allows a user to type in a user name
with autocomplete.

Eg: "send message to..."

**Comment by sycamoreone** [comment]
I think the correct term here is "invisible" mode, as in [XEP-0186](https://xmpp.org/extensions/xep-0186.html), instead of "offline" mode.

(XEP-0186 has some interesting entanglement with OTR, because most XMPP clients just set up OTR sessions after receiving an OTR Query Message and thus violate this requirement:
> Prompt the user before sending any outbound traffic (message, presence, or IQ stanza) to another user, even if the user generated such traffic; upon receiving authorization from the user, the client might then add the authorized entity to the communicants list for this invisibility session.

The problem here is the invisible client though, so coyim doesn't need to care.)

**Comment by xSmurf** [comment]
I think a simple way to implement what @ioerror wants would be to have a search field at the top of the roster. The search field would be "live" and start showing results after a few characters are typed. It would also search through all contacts, regardless of their status.

**Comment by olabini** [comment]
There already exist something like that, except the search is only for the elements in the treeview. Try typing something when focused on the roster.

It does feel like what @ioerror is looking for is something different, which I'm still not sure I understand.

**Comment by xSmurf** [comment]
I know there is already the generic treeview search but it's rather shitty, imho.

I think my idea would fill half of @ioerror's request, just have a search field that filters all contacts. Second thing I think he would like to see, if I understand properly, is an option to open a conversation with arbitrary JIDs which are not on the roster (something that is perfectly acceptable in XMPP). That should be easy enough to solve by just having a "new conversation with non-contact" (well ok that is not well formulated) button in the contact menu.

**Comment by olabini** [comment]
Ah, ok - these would be nice to haves at some point.
