### ISSUE TITLE
Implement preferences/configurations

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#317]
There's starting to be a lot of things which should use persistence configurations. To handle this a preference window needs to be implemented as well as storing of settings, either in the config file, in another separate config file, or through gsettings.

Things I can currently see that should be configurable in this manner:

- [ ] Multi vs Unified window move
- [ ] Parsing of `/me` action messages
- [ ] Passing of message contents to dbus notifications (with a warning about leakage)
- [ ] Allowing dbus notifications over fullscreen applications
- [ ] Setting (non) expiry of notifications

**Comment by olabini** [comment]
Yeah. there are two different features here. The first one is to store some settings in gsettings. The second feature is to expose global configuration options in the UI - some of those options will be in the config file, and some will be in gsettings, depending on how sensitive they are etc.
