### ISSUE TITLE
Set urgency hint when receiving messages and window is not visible

### ISSUE THREAD

**Issue by duckdalbe** [twstrike/coyim#318]
At least on unix-like systems many chat-clients (e.g. gajim, pidgin) set the urgency-hint for the chat-window when a new message is received and the window is not visible.

I think that's a valueable feature and would be happy if Coy (the new client of my choice) could do that, too. Currently I have to check my chat windows regularly to make sure I don't miss messages, which is cumbersome.

**Comment by olabini** [comment]
Thanks for the comment - we should definitely do this.

**Comment by duckdalbe** [comment]
Great, thanks! And so fast!

It's just that now every activity in a chat windows makes it set the urgency-hint. E.g. when my chat partner changes their status. In my opinion that's a bit much and also unexpected.

Also the pop-up-notification that goes along with this is of level UrgencyCritical, which makes it alarmingly bright red on my desktop. Is that on purpose? Wouldn't UrgencyNormal be more appropriate?

Should I open new issues for this or would you reopen?

**Comment by olabini** [comment]
So what specific things would you expect an urgency hint from?
The urgency level of the notification is done that way to make it visible over full screen windows. We are planning on making it configurable. That stuff is tracked here: #113

**Comment by xSmurf** [comment]
Wait what? The notifications don't get triggered on status change, only messages.

**Comment by duckdalbe** [comment]
I would expect an urgency hint for new messages. Maybe for my chat partner going offline or online. But not for changing presences.

If I'm reading the code right there's not notification if `showFullscreen` is false, right? Maybe you could use `UrgencyCritical` if `showFullscreen` is true, but `UrgencyNormal` if it's false?

**Comment by olabini** [comment]
Wait, I'm confused - are you talking about notifications, or urgencyhints on the windows?

**Comment by duckdalbe** [comment]
Both:
* I'm asking to not set the urgency-hint for changes of the presence of my chat-partner (maybe unless it's going offline/coming online).
* And I'm asking if the notification for new messages needs to be of level UrgencyCritical (https://github.com/twstrike/coyim/blob/master/gui/desktop_notifications.go#L40) — those "critical" notifications don't fade on my system but stay there, bright red in the corner, like a serious error, until I click on them.

Both topics have the word urgency, I understand the confusion. Should I maybe open new tickets for each?

**Comment by xSmurf** [comment]
@duckdalbe So the reason the notification urgency hint is set to Critical is that it is the only way to have the notifications appear on top of full screen windows. As @olabini was mentioning, this should be configurable soon anyway.

**Comment by olabini** [comment]
Indeed, the notifications issue should soon be fixed. However, the urgency-hint I'm more confused about. @xSmurf mentioned we only set it for messages, not for presence changes.

**Comment by duckdalbe** [comment]
I see an urgency-hint whenever the presence of a buddy I'm chatting with changes. There's a new line in the chat-window saying e.g.
`[12:00:00] $name is now Away (I'm not here right now)`

Do you count these as messages? Then the behaviour would be correct.

I wouldn't consider that a message I want to be hinted to, though.

**Comment by olabini** [comment]
wait what? I don't understand what you mean with wanting to be hinted
do you want the urgency-hint set on status messages or not?

**Comment by duckdalbe** [comment]
Sorry to cause confusion!

To be clearer: I'd prefer to not have status-changes cause an urgency-hint.

**Comment by olabini** [comment]
OK, thanks. I'll investigate.
