### ISSUE TITLE
application crashes when exporting private keys

### ISSUE THREAD

**Issue by rodrigomaia17** [twstrike/coyim#319]
I just did a fresh installation and then imported my existent account. Then coy generated my keys and now I want to export them. When I go to AccountDetails->Encryption-> ExportPrivateKeys , it crashes =/

**Comment by olabini** [comment]
Terribly sorry about that. Do you think you can send the crash log?

**Comment by rodrigomaia17** [comment]
It shows something like that: 

...
(CoyIM:21939): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
SIGTRAP: trace trap
...

is this useful?

**Comment by olabini** [comment]
Is this on Windows?

**Comment by olabini** [comment]
Which version of Coy are you using?

**Comment by rodrigomaia17** [comment]
OS X Yosemite 10.10.5
Coy version: 0.3.2 

Installed using .dmg from website

**Comment by tcz001** [comment]
should be fixed by https://github.com/twstrike/coyim/commit/dacf1ffc6ec282f697cc60aae40ce256ac494635

**Comment by juniorz** [comment]
I want to investigate later if this also fix the issue:

`glib-compile-schemas $(brew --prefix)/share/glib-2.0/schemas/ --targetdir=$resources/share/glib-2.0/schemas`

In this case we wont have all the xmls in the bundle, only the compiled schema.

Nice find!

**Comment by tcz001** [comment]
copy all the xmls was a wrong choice, because they are relative symbolic links

**Comment by olabini** [comment]
Great - we will release 0.3.3 this weekend or early next week - from that point on should be fine.
