### ISSUE TITLE
Could not connect error when setting up coy on windows

### ISSUE THREAD

**Issue by lqust** [twstrike/coyim#320]
See attached image. The error occurs for any server. I can ping dukgo.com. 

![could not connect](https://cloud.githubusercontent.com/assets/3587497/14214513/cc712a36-f813-11e5-91a7-68b82604753f.png)

**Comment by olabini** [comment]
Do you have Tor installed and running? I'm not sure the registration gives a nice error message if no Tor is set up yet.

**Comment by lqust** [comment]
That is probably the reason. I couldn't find anything in the documentation
that would make me think I need Tor. I guess it is obvious for for people
closer to the subject, but adding this piece of info may help
adoption/contribution.

2016-04-03 13:07 GMT-03:00 Ola Bini <notifications@github.com>:

**Comment by olabini** [comment]
Yeah, CoyIM by default uses Tor in order to ensure safety for the user. In general you get a good message about it, but not with registration, so we should definitely fix that. I don't think we have a way of turning off Tor-need for registration right now, sorry.

**Comment by lqust** [comment]
I agree that Tor is important and if I have to have it  I might as well
have it during registration. I looked in the site and couldn`t find
anything like Tor as a requirement tho. As I siad, it is obvious to many,
but not to post-techies like me :o)

2016-04-04 20:13 GMT-03:00 Ola Bini <notifications@github.com>:

**Comment by olabini** [comment]
Yeah, we should probably mention it more - and give a good warning when registering without it.

**Comment by olabini** [comment]
But that's another thing that's different with Coy - we try to be safe and secure, and when we can't be, we at least fail closed (meaning we don't leak information to the world in that case).
