### ISSUE TITLE
Implement XMPP console

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#321]
It would be very useful for debugging if there was a raw XMPP console available somewhere like is exposed in Gajim.

**Comment by olabini** [comment]
Agreed, this would be great. Right now, the -debug mode prints a lot of the xmpp, but not all of it.

**Comment by xSmurf** [comment]
It also prints a lot of things I don't care about and sometimes I want to check something in an existing session. As you put it with the milestone, it's not a priority, but I think it would make our life easier in the future to debug things (I'm thinking of that ressources/otr issue for example)

**Comment by olabini** [comment]
OK - I think adding this console will be quite easy. But it will only be available when the -debug flag is there. Does that make sense?
