### ISSUE TITLE
password prompt when using gmail

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#323]
When attempting to use a PRISM enabled gmail account, I was unable to connect. Google sent emails saying that coy wasn't secure and at the same time, coy was in a loop asking me for the password over and over again. Happens every time with this account - it should fail and not prompt for the password repeatedly, I think.

**Comment by xSmurf** [comment]
I think this is a duplicate of #168

**Comment by olabini** [comment]
Agreed, it's a duplicate. The problem here is that currently CoyIM doesn't know whether you entered the wrong password or if there's another error. #168 is about recognizing the difference.
