### ISSUE TITLE
idle user indicators

### ISSUE THREAD

**Issue by cubi7** [twstrike/coyim#330]
This is I thinking very superficial but let see what people thinks

At the moment with coy 0.3.2  is a user is idle for 5 minutes their status icon turns red.  if they are idle 15 minutes it does yellow

I think the colors should be reversed, red indicate more severe or stronger than yellow so make more sense for longer idle time.

**Comment by olabini** [comment]
Actually, the thinking is that the stronger colors indicate more recent activity. This is fairly common for chat clients.

**Comment by cubi7** [comment]
> This is fairly common for chat clients.

If that's the case leave it as is, no point confusing things

**Comment by olabini** [comment]
Thanks
