### ISSUE TITLE
Provide 32bit Linux binaries

### ISSUE THREAD

**Issue by pixelrust** [twstrike/coyim#332]
This happens on Linux Kubuntu 15.10 running 4.2.0-34-generic i686.

When I run CoyIM I get this:
`cannot execute binary file: Exec format error`

**Comment by pixelrust** [comment]
I add that this happens with the Linux binary currently available for download at https://coy.im.

The output of `file` follows:
`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=ed5f470618a7164a76db091ec6ee8849f023811a, not stripped`

(I'm not sure I'm using the right words here) Are there plans to support Linux i686?

Note that I can run CoyIM on the same system by building the 32-bit, Intel 80386 executable.

**Comment by olabini** [comment]
Stupid question here. Is the i686 a 32 bit machine? We currently only build all the binaries for 64bit, but 32bit should work fine as well. We should try to set up automatic 32bit build for the next release. Sorry about that.

**Comment by pixelrust** [comment]
Yes, it's a 32 bit machine. By the way, what's the preferred way to tell this? 
`uname -m`? `arch`? 
```
$ uname -m
i686
```

**Comment by olabini** [comment]
Not sure actually.

I'll rename this issue to specify that we should provide 32bit binaries.

**Comment by olabini** [comment]
So this turns out to be trickier than expected, since we use Travis for our build environment and Travis doesn't support 32bit anymore. We do support 32bit binaries for our downloads of the CLI, but I don't think we can support 32bit GUI downloads.

The easiest way here is probably to simply build it yourself.
