### ISSUE TITLE
Add save-permanently checkbox next to password entry.

### ISSUE THREAD

**Issue by t2d** [twstrike/coyim#335]
I have to enter my password on every start with coyim 0.3.2 on Ubuntu 15.10

**Comment by olabini** [comment]
Hi, sorry about that. 
You should be able to enter your password on the edit screen and then it will be saved in the configuration file. Just choose the Accounts menu, then the name of the account, then Edit... - you should be able to enter the password there.

**Comment by t2d** [comment]
Yes, this works. However, I think it is common sense in most application to have a "remember password" box next to the password field.

**Comment by olabini** [comment]
Agreed, that sounds like a good idea. Will reopen this issue and change the title.

**Comment by t2d** [comment]
awesome, thanks!
