### ISSUE TITLE
Cannot send messages 

### ISSUE THREAD

**Issue by t2d** [twstrike/coyim#337]
I'm using coyim 0.3.2 on Ubuntu 15.10. I downloaded the binary from the website. There is no "Send"-Button in chat windows. Enter, Ctrl+Enter, Shift+Enter... nothing sends the message, but only adds new line.

**Comment by olabini** [comment]
Hi, terribly sorry about your problems. Is it possible that you have caps lock, num lock or scroll lock set? We had an issue with those stopping enter from working.

This is fixed in master, and the next release (coming soon) will have it fixed.
