### ISSUE TITLE
Title bar broken in Ubuntu

### ISSUE THREAD

**Issue by t2d** [twstrike/coyim#338]
After the update from 0.3.2 to 0.3.5 I only see `CoyIM` in the title bar in Ubuntu 15.10. Before, I could access the options with hovering over the title bar. This is now only possible, if I open the window in full screen.

**Comment by olabini** [comment]
Hi,
Which mode are you using? I'm not sure what change made this happen actually - @brl @xSmurf

**Comment by t2d** [comment]
What do you mean by mode?

**Comment by xSmurf** [comment]
@t2d whether you are using multiple window or unified window mode.

@olabini I don't see anything that has changed since that would create this issue, though I'm not entirely certain I understand the problem.

@t2d could you maybe post some screenshots?

**Comment by t2d** [comment]
The problem is present in both multiple and unified window mode.
coyim-0.3.2
![coyim-0 3 2](https://cloud.githubusercontent.com/assets/1834580/14431613/b2d554b2-0006-11e6-9d46-500bc404fe35.png)
coyim-0.3.5
![coyim-0 3 5](https://cloud.githubusercontent.com/assets/1834580/14431614/b2d8d344-0006-11e6-94ff-b1059d64b4a7.png)
The problem is, that if I hover on the title bar, it shows the options in 0.3.2, but not in 0.3.5

**Comment by xSmurf** [comment]
@olabini Was the GtkApplicationWindow implemented in 0.3.2 already?

**Comment by olabini** [comment]
That's extremely strange. And yeah, the GTKApplicationWindow came before 0.3.2 if I remember correctly. 
@t2d - there is nothing different in your environment? You didn't do an update of the gtk libraries or anything?

The 0.3.2 screenshot is quite weird actually - which window manager is it?

**Comment by t2d** [comment]
No, I can reproduce it right at this moment. I'm working on standard Ubuntu 15.10 with Unity.

**Comment by xSmurf** [comment]
@olabini was the GtkHeaderbar "ported" to the multi window mode as well? That's the only thing I could see.

**Comment by olabini** [comment]
No, the GtkHeaderBar is only used in the unified mode... Hmm.

**Comment by olabini** [comment]
I don't know much about how Unity renders stuff though - none of the core devs are on Unity.

**Comment by olabini** [comment]
Any thoughts on this?

**Comment by olabini** [comment]
Any updates here?

**Comment by t2d** [comment]
It looks like there was something wrong with my profile. I created a new one and it is working. Sorry for the disturbance.
