### ISSUE TITLE
UX/UI -- reconnecting after disconnection

### ISSUE THREAD

**Issue by alisonLFP** [twstrike/coyim#339]
When a session is interrupted by an unexpected disconnection, reconnecting is not intuitive. Users must go to the accounts menu and select "disconnect" then "connect". This is confusing in part because it is not how other IM clients behave, and also because the client appears to be reconnecting after the initial disconnection -- the client displays "reconnecting" at the bottom, and the user gets a password prompt that won't resolve...unless the "disconnect" option is first selected from the menu. 

It would be better if either user is given a prompt, eg "You've disconnected. Connect again?" which would give a password prompt, or at the very least, don't let the client appear to be reconnecting when the user has to select the "disconnect" option first. 

Thanks!

**Comment by olabini** [comment]
Yes, this behavior is not completely intuitive. It's a bit hard to judge when to reconnect and when to automatically reconnect. CoyIM tries to do that automatically, but in conjunction with the password prompt it becomes strange.

**Comment by olabini** [comment]
However, the reconnect behavior always works for me - when there is a network outage, CoyIM keeps track of it, and connects again when the network comes back - I basically never touch the "connect"/"disconnect" items - I suspect this might have to do with not having the xmpp password in the config file.

**Comment by olabini** [comment]
I suspect this behavior is currently fixed - we added a bunch of behaviors after this was filed. I'll file this as closed for now.
