### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#34]
- [ ] main          15.8% -> 
- [ ] xmpp         13.2% -> 19.9% -> 28.6% -> 32.9% ->  42.2% -> 
- [ ] session      0%      ->
- [ ] config         14.6% -> 14.1% -> 
- [ ] ui                55.9% ->

**Comment by olabini** [comment]
Let's remove this as a specific task, and just keep in mind to keep the test coverage up. The gui package is the only place that is really bad right now.
