### ISSUE TITLE
Support for emacs/bash keyboard shortcuts

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#342]
Namely ctrl-a/e and ctrl-w in the input field should be configurable to behave according to emacs keyboard shorcuts. ie: move to start, move to end, remove last word.

( see also #341 )

**Comment by olabini** [comment]
I've implemented this by making it possible to switch on the Emacs GTK theme. However, for the moment that doesn't seem to support ctrl+w. Will investigate why.
