### ISSUE TITLE
Can't log in with my correct credentials - Dukgo account - in Subgraph OS.

### ISSUE THREAD

**Issue by gdrdrposteo** [twstrike/coyim#349]
Hi!

I am very sure that I am entering my correct credentials and it I'm just being kept asked for my password. Help please?

Thanks!

**Comment by tcz001** [comment]
Could you please dump some debug log? BTW, Have you tried login without tor-auto proxy?

**Comment by olabini** [comment]
Ping about this?

**Comment by olabini** [comment]
Sorry, since we haven't gotten any more feedback to be able to debug this problem, we're closing this issue for now.

**Comment by sym40** [comment]
Hello, I have the same issue. Installation is fine, secure password is entered but the OS doesn't seem to recognize it. Have re-loaded OS several times so I am confident that the password is entered correctly.
