### ISSUE TITLE
coyim fails to build on Tails (due go version 1.0.2)

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#35]
The golang verson available at debian is old (reason: http://blog.labix.org/2013/06/15/in-flight-deb-packages-of-go)

```
$ docker run -i -t debian:wheezy bash -c "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y golang && go version"
go version go1.0.2
```

Installing a different go version on wheezy using `godeb` also fails (reason: http://stackoverflow.com/a/26845235)

```
$ docker run -i -t debian:wheezy bash -c "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y golang git bzr && export GOPATH=/gopath && mkdir $GOPATH && go get github.com/niemeyer/godeb && $GOPATH/bin/godeb list"
error: Get https://code.google.com/p/go/wiki/Downloads: x509: certificate signed by unknown authority
```

We can instruct the user to install the testing version (similarly to `pond` install instructions) and it should work.

```
foo@tails $ apt-get install -y -t testing golang && go version
go version go1.4.2 linux/amd64
```

But `go get` still have problems to download packages from `golang.org/x/`. Replacing them by their `github.com/golang/` counterparts fix the issue.

Related build https://travis-ci.org/twstrike/coyim/jobs/82831870

**Comment by olabini** [comment]
We have a workaround for this.
