### ISSUE TITLE
Add "Nickname" field for accounts

### ISSUE THREAD

**Issue by bnvk** [twstrike/coyim#350]
In Pidgin / Adium one can add a "Nickname" field to their user account so that in message threads whereby a user is messaging someone with a nickname it will look like

```
YourName: what's in a name, yo?
CoolCat: I dunno, not much
```

Instead of the current display which is:

```
yourname@jabber.server.org: what's in a name, yo?
CoolCat: I dunno, not much
```

**Comment by olabini** [comment]
Ah, you want a nickname for yourself? The configuration and display already supports this, but we don't have it exposed in the user interface yet.

**Comment by bnvk** [comment]
@olabini yah exactly, as this is standard in other clients and makes for a slightly nicer interface of reading messages than long email looking names. I figured it was in the API and should be simple-ish to do. If I knew Go I would take a stab at it myself :smile:
