### ISSUE TITLE
Closing chat pane should allow optionally destroying messages

### ISSUE THREAD

**Issue by bnvk** [twstrike/coyim#351]
Currently when a user has `Unify conversations` feature enabled, and a user clicks on the "X" button in a single chat thread, this does not "destroy" the messages in that thread. Clicking on the same contact in the buddy list, then re-opens the same thread with all the messages from that previous session.

**Comment by bnvk** [comment]
This also happens when `Unify conversations` is not selected as well. When closing the isolated chat window and then re-starting a thread, the previous messages are still there. 

To clarify what I mean "optionally" you pop-up an alert saying "Would you like erase messages from this session?" or just by default with Pidigin/Admin delete the messages stored in the view

**Comment by olabini** [comment]
I'm not a huge fan of popping up a question when closing a conversation window. The current behavior is that older content will be reaped when a window is closed - that is currently fixed to 1 hour or older, but we're planning on making that customizable. As far as I can tell, that is the same behavior in both unified views and un-unified ones.
