### ISSUE TITLE
Cannot launch CoyIM Application in GNOME's application search (gnome-do)

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#354]
I have installed coyim, and I cannot seem to launch it through GNOME's application search and launch feature called gnome-do (similar to Spotlight on Mac OS). I have to launch it through the terminal. I'm not sure why gnome-do does not consider it an app. 

I am using GNOME version 3.20.1-1 and gnome-do version 0.95.3-3  
https://launchpad.net/do/

**Comment by cubi7** [comment]
`gnome-do` lets you launch applications that have a corresponding `.desktop` file in either `$HOME/.local/share/applications` (you might have to create this folder) or `/usr/share/applications`.  You can see more [here](wkGzEJKMdqePsMaxBsmAiCB_ESSfjVPY2z5nyhcf)

An example for coy would be

    [Desktop Entry]
    Version=1.0
    Name=CoyIM 
    Comment=Secure Instant Messenger
    Exec=/path/to/coyim
    Terminal=false
    Type=Application
    Categories=Internet;

Just change the line for `Exec` so it is where you installed coyim, save the file as `coyim.desktop`, then place the file in one of the two above folders

**Comment by olabini** [comment]
Yeah - we haven't created a .desktop file yet, since we don't have installable packages on Linux so far. But it might be a good idea to have a template in the repo.

**Comment by rosatolen** [comment]
Thanks @cubi7 :D 

Here's a template candidate based on advice from responses to this Issue. 
https://github.com/twstrike/coyim/pull/356

**Comment by olabini** [comment]
I'll close this issue for now - it is tracked in the other packaging issues.
