### ISSUE TITLE
instance tag in dh commit

### ISSUE THREAD

**Issue by hannesm** [twstrike/coyim#358]
according to the otr v3 specification (see https://otr.cypherpunks.ca/Protocol-v3-4.0.0.html), the receiver instance tag of a dh commit message should be "invalid" (thus between 0 and 0x100), but coy seems to save instance tags on disk and reuse them for new sessions.  I do not understand why it is doing so (and needed to specifically allow for valid receiver instance tags to interoperate with coy).

is there any reason why coy violates the specification (and is there any reason to preserve instance tags)?

**Comment by olabini** [comment]
Hi,

CoyIM follow the specification (and behavior of libotr and pidgin as well). If you read the specification under instance tags you will see the first sentence being "Clients include instance tags in all OTR version 3 messages. Instance tags are 32-bit values that are intended to be persistent. " - where the operative word is "persistent".

If you look at the specification for DH Commit, you will find that the sender instance tag should always be set - while the receiver instance tag is usually 0 if we don't know who we are talking to. CoyIM has the correct behavior here.

Cheers
