### ISSUE TITLE
Crash if desktop notifications can't be set up

### ISSUE THREAD

**Issue by meejah** [twstrike/coyim#359]
I get a crash on master and v0.3.4 if desktop notifications can't be setup (it looks like). I believe what is happening here is that I am running in a `tmux` session that was started in a Gnome terminal, but I've since re-attached from a non-Gnome session. I tried un-setting a few promising looking environment variables but to no avail.

(Note that from a fresh terminal in a non-Gnome X session, coyim works fine! So, this isn't a "general problem" but might still bite some users...)

For the record the stack-trace I see is:

```
goroutine 12 [running]:
panic(0xf129c0, 0xc82000a1a0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/twstrike/coyim/gui.(*desktopNotifications).updateWith(0x0, 0xc8201ccec0)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/desktop_notifications.go:26 +0xb3
github.com/twstrike/coyim/gui.(*gtkUI).configLoaded(0xc8200c2240, 0xc82001a0a0)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/ui.go:197 +0x8b
github.com/twstrike/coyim/gui.(*gtkUI).loadConfig.func1(0xc82001a0a0)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/ui.go:166 +0x2a
created by github.com/twstrike/coyim/config.(*ApplicationConfig).accountLoaded
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/config/application_config.go:53 +0x11b
```

**Comment by olabini** [comment]
Thanks for the report - I'm not sure I understand this at all. Can you give me the stack trace from master/0.3.6 instead?

**Comment by meejah** [comment]
Note that my "go" fu is low. So, it turns out "go get ..." didn't update the repo as I expected. So, I *believe* this is v0.3.6 (I manually "git fetch" and checked out v0.3.6 and then said `go install .../coyim`).

```
goroutine 10 [running]:
panic(0xf1ec20, 0xc82000a1a0)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/twstrike/coyim/gui.(*desktopNotifications).updateWith(0x0, 0xc8201ba060)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/desktop_notifications.go:39 +0xb3
github.com/twstrike/coyim/gui.(*gtkUI).configLoaded(0xc8200b2240, 0xc82015e280)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/ui.go:196 +0x8b
github.com/twstrike/coyim/gui.(*gtkUI).(github.com/twstrike/coyim/gui.configLoaded)-fm(0xc82015e280)
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/gui/ui.go:165 +0x2a
created by github.com/twstrike/coyim/config.(*ApplicationConfig).accountLoaded
        /home/user/gocode-1.6/src/github.com/twstrike/coyim/config/application_config.go:53 +0x11b
```

**Comment by meejah** [comment]
The behavior is that it starts up and asks for the password, and then crashes as above after successful password entry...I'm happy to try and isolate which env-vars are the right ones if that will help narrow it down. I suspect it's because I'm not running gnome session-bus or whatever it's called.

**Comment by olabini** [comment]
(you can use "go get -u" to get it to update a package)

**Comment by olabini** [comment]
This behavior looks more like a race condition rather than anything else. Let me see if I can understand what's happening. Sorry about this! =)

**Comment by olabini** [comment]
Oh wait, I see what's happening. Sigh. I'll fix =)

**Comment by olabini** [comment]
ok I think it should be fixed now. Do a "go get -u" of the coyim package and you should have it working

**Comment by meejah** [comment]
Awesome. Yeah, I can confirm that this now works in the same shell that failed on `v.0.3.6`.
