### ISSUE TITLE
Cannot see sections under Account Details window on Arch Linux

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#361]
When I navigate to Accounts -> Add... I cannot see the tabs: Accounts, Server, Proxies, Encryption. I am only served the Accounts section. 

This is problematic when trying to setup a new account with keys exported from another device. The encryption tab should have the affordance to import the key but a user has no way to navigate to it. 

Credit to @yakiradixon for finding this while comparing the interfaces on Mac OS X and Arch Linux.

**Comment by olabini** [comment]
?? I have no idea why this is happening. What window manager are you using? What version of GTK?

**Comment by yakiradixon** [comment]
I'm using awesome window manager (v3.5.9) and gtk3. 

The interesting is I can see and select tabs in the Preferences window (General, Notifications, Debugging) but no tabs in the Accounts window.

**Comment by rosatolen** [comment]
I also see this bug in my system. I am using Arch Linux and Mutter window manager (3.20.3-1) with gnome and gtk3 (3.20.9-1)

**Comment by olabini** [comment]
Hmmmmmmmmmmmmmmmmmm.

**Comment by olabini** [comment]
So, @rosatolen, @yakiradixon - did you click in the "Display all settings" checkbox?

**Comment by yakiradixon** [comment]
![image](https://cloud.githubusercontent.com/assets/1497635/18497604/4f0349b2-79f5-11e6-8986-9a34864364c8.png)

ye... 
wait, no.

wow.

**Comment by rosatolen** [comment]
Haha damn. Good thing we've been chatting about usability lately ;)
