### ISSUE TITLE
When importing private key, having a prpl-aim account seems to cause problems

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#363]
See #292

**Comment by olabini** [comment]
Actually, @ageis - I'm a bit confused. Your comment refers to prpl-jabber and prpl-aim - but you're talking about the import of private keys. Importing private keys doesn't use the prpl-jabber format at all, so what are you referring to here?

**Comment by olabini** [comment]
Gah. Our test code doesn't seem to match the real format. That confused me. Sorry about that.

**Comment by olabini** [comment]
Oh ok - I see what's happening, @ageis. The code that imports a private key does NOT use the protocol matcher for prpl-jabber that you pointed to. In fact, it uses a matcher that matches anything. 

This still doesn't explain the problem you're having. In fact, as far as I can tell the code is doing things as it should.

**Comment by ageis** [comment]
When I get a moment in a day ortwo I'll try to reproduce it again. I might be able to send you a non-importing otr.private_keys file (I'll use fake keys, of course).

**Comment by olabini** [comment]
That would be super helpful! Thanks so much!

**Comment by olabini** [comment]
Any news on this, @ageis?

**Comment by olabini** [comment]
Any news on this?

**Comment by ageis** [comment]
@olabini I'm sorry, no. Very busy. Maybe tonight?

**Comment by ageis** [comment]
Attached an `otr.private_key` file with a disposable DSA key.
[otr.private_key.txt](https://github.com/twstrike/coyim/files/530128/otr.private_key.txt)

To reproduce: set up one of my accounts in coyim, ex. ageisp0lis@jabber.org. Select this file to import key. Get an error:  
![failed](https://cloud.githubusercontent.com/assets/1161532/19397490/e9d7244e-91fc-11e6-8d36-f030c8fad7cf.png)

Workaround: manually edit `otr.private_key` and delete the `prpl-aim` account. Save. Now it works: 
![keys](https://cloud.githubusercontent.com/assets/1161532/19397537/1db7f720-91fd-11e6-8ac3-ac1cdaff253d.png)

**Comment by olabini** [comment]
Hey - thanks for the example file. With it, I could quickly establish that the problems was not that the type as prpl-aim - but that the account name was not encoded as a string, but as a symbol.

This should work fine now!
