### ISSUE TITLE
cannot open menu items

### ISSUE THREAD

**Issue by alisonLFP** [twstrike/coyim#365]
After launching Coyim and entering my master password for the configuration file, I cannot proceed to login to my account or view any other menu options. When I click on the menus, nothing happens. I am using version 0.3.5-1 on Subgraph.

**Comment by xSmurf** [comment]
I'm certain this is OZ (well Xpra to be exact) related and not a problem with CoyIM.

**Comment by olabini** [comment]
OK, sorry to hear that. @xSmurf - you want to open a bug in subgraph for this instead, or want to keep it open here?

**Comment by xSmurf** [comment]
You can definitely close this, it's an issue from upstream with recent gtk upgrades.
