### ISSUE TITLE
Closing conversation in Unified View causes user list window to grow 

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#366]
Each time you close a conversation, the user list window to grow. Several closes will cause the window to grow beyond the size of your screen.

This has been seen on Mac OS X but not tested on other platforms.

**Comment by olabini** [comment]
I can't reproduce this on Linux. Either this is mac specific, or there are more specific instructions necessary to reproduce it.

**Comment by olabini** [comment]
@rosatolen - any news on this? I need more specific reproducibility instructions.

**Comment by olabini** [comment]
@rosatolen - ping??

**Comment by rosatolen** [comment]
This currently seems to be a problem only with my local setup. I haven't been able to replicate it on other machines with the latest build.
