### ISSUE TITLE
CoyIM crashes when turning on Unified View on Mac OS X

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#367]
CoyIM crashes when turning on Unified View preference while a conversation window is already open in Mac OS X

**Comment by olabini** [comment]
This doesn't seem to happen on Linux.
In order to be able to debug it, we need the crash-output from this event.

**Comment by olabini** [comment]
Ah, wait - it does happen on Linux - but only after you try to open a new conversation with someone else.

**Comment by olabini** [comment]
This was fixed in 055ba15
