### ISSUE TITLE
Conversations opened without Unified View are not opened correctly with Unified View

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#368]
Recreating the error:
1. Without unified view, message with someone and then close the conversation
2. Add unified view with a checkbox in the preference menu
3. Restart CoyIM
4. Open a conversation with the person in step 1

At this point the conversation does not open in Unified View.

**Comment by juniorz** [comment]
There was a bug introduced by this: you can open an arbitrary number of conversation windows by switching between the two layouts and leaving the conversations open.
