### ISSUE TITLE
Migrating to Golang >= 1.6 vendoring system.

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#369]
> godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.

Godep `Godeps/_workspace` is deprecated in 1.7, and will be going away with golang 1.8. It would be wise to start migrating to the new >= 1.6 `vendor` mechanism.

The instructions at https://github.com/tools/godep#migrating-to-vendor worked fine for me.

One particular advantage is that it makes building "dirty" packages using dh_golang (that is builds that don't have all of their vendored libs packaged in debian) much easier.

**Comment by olabini** [comment]
Yeah, I've been thinking about this. But the problem is supporting 1.4 which doesn't support vendor at all, and 1.5 where the support doesn't work.

**Comment by xSmurf** [comment]
But the alternative is not supporting >= 1.8... is it really worth keep backwards compatibility this far back?

**Comment by olabini** [comment]
Yeah, I'm not sure. The 1.4 compatibility is for all the Tails 1.* users - but I'm not sure how many users like that CoyIM has. Maybe we just need to stop supporting 1.4 and 1.5

**Comment by juniorz** [comment]
I noticed a few weird things (and problems):

We don't directly use `github.com/gotk3` anymore (and the only reference to it outside the `vendor` folder is in the `Godeps.json`, so there should not be `vendor/github.com/gotk3/gotk3`. If I remove it, everything compiles fine, but `godep save` was not able to remove it automatically.

Then I updated godeps to `godep v74` but `godep save` fails with a `godep: Package (flag) not found` error (`flag` is a stdlib package).

**Comment by juniorz** [comment]
I'm confused about the implication of this change to the dev workflow.

Does it mean after migrating to 1.6 vendoring system we don't need `godep` anymore or we still need it to conveniently upgrade vendored dependencies to latest version?

And what about not having the paths rewritten to point to `Godeps/_workspace` anymore? Does it mean we should not replace `go` by `godep go` (or alternatively do `$GOPATH=$(godep path)`) anymore?

**Comment by olabini** [comment]
About the last point, the vendor experiment from Go 1.6 means Golang will automatically load dependencies from the respective /vendor directories, so no rewriting is necessary. For this to work well, it's good to _not_ have the libraries on the GOPATH (I've noticed a bunch of recompilation happens otherwise)

**Comment by olabini** [comment]
We only need godep when actually updating dependencies - regular use should be possible without having godep installed, since all the functionality is built in to Golang.
