### ISSUE TITLE
"Not sent yet" is pretty confusing

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#372]
Based on conversation with @SweetVirginia - the current behavior when force encryption is turned on can look pretty confusing:

  [16:36:44] (Not sent yet) xx@yy.ec:  ~~one~~
  [16:36:44] Attempting to start a private conversation...
  [16:36:45] (Not sent yet) xx@yy.ec:  ~~two~~
  [16:36:46] (Not sent yet) xx@yy.ec:  ~~three~~
  [16:36:47] Private conversation started.
  [16:36:47] xx@yy.ec:  one
  [16:36:47] xx@yy.ec:  two
  [16:36:47] xx@yy.ec:  three

Because Coy doesn't want to modify the previous text the "Not sent yet" part is not super helpful. On the other hand, we want to allow the user to send more than one message while the private conversation is still being set up. We could just not put anything in the chat window, but that makes it confusing if the conversation never gets started, and all the things said will disappear completely.

Another proposal from @SweetVirginia is to have a third window for the pending messages that will pop up when needed and disappear when the messages have been sent for real.

We need to figure out a better solution than what we currently have.

**Comment by SweetVirginia** [comment]
> "Another proposal from @SweetVirginia is to have a third window for the pending messages that will pop up when needed and disappear when the messages have been sent for real."

It was just an idea, not a proposal :)  I'll come with proposals soon.

**Comment by olabini** [comment]
Sure, I'm fine with calling it an idea. Sorry for misrepresenting =D

**Comment by iapazmino** [comment]
The problem: The current behavior of how we warn the user that messages typed while the private conversation is still being set up is confusing, as each message has the error "Not sent yet," and then is re-sent later.

Options:
1. Keep current behavior.
2. Keep a box for the pending messages and remove them once they are sent.
3. Remove messages from the transcript once they were sent.

First option kept the transcript with a lot of noise around the conversation which made users feel confused.
Second option would keep a much cleaner conversation but produced an incomplete transcript.
Third option had the same pros and cons as the second.

The solution: keep the transcript as the original but hide the noise in a light color so conversation would stay relevant plus have a pending box where messages that are typed but cannot be sent will be held. When these messages are finally sent, they will have two timestamps; one that is when the message was typed, and one when the message was sent.

**Comment by olabini** [comment]
Any progress on this?

**Comment by olabini** [comment]
Any progress, @iapazmino ?

**Comment by iapazmino** [comment]
Some refactoring is due, but functionality is there now.

**Comment by juniorz** [comment]
Messages seem to be sent in plaintext even after I press the "Secure chat" button in the conversation window. Is this expected?

Steps to reproduce:

- Disable Require Encryption.
- Open the conversation window.
- Click the "Secure chat" button.
- Send messages.

The messages I type are displayed in my history after the `Attempting to start a private conversation...` line, and the recipient receives them in plaintext.

**Comment by iapazmino** [comment]
@juniorz That's known bug, meaning we have a TODO for it ;) , and now is documented in #426

**Comment by iapazmino** [comment]
@juniorz That's known bug, meaning we have a TODO for it ;) , and now is documented in #426
