### ISSUE TITLE
Notification messages not displayed with XFCE

### ISSUE THREAD

**Issue by cubi7** [twstrike/coyim#374]
OS: Qubes 3.2
DE: XFCE  4.12
IM: Coy v0.3.6
AppVM: Debian 8

Expected behavior:

When messages come in while Coy is in the background, it should display an on screen notification

What Happens:

No notifications are displayed when a message comes in and Coy is in the background

Other:

Notification settings 
- Notification type: Show who sent the message
- Should notifications be displayed urgently - yes
- Should notifications expire - yes
- Notifictation command - empty
- Minumum time between notification in seconds - 60

This has previously been working with Qubes 3.1 and KDE DE

**Comment by olabini** [comment]
Did this work with 0.3.6 on Qubes 3.1 and KDE DE, or was that an older version?
Not sure how to debug this - we did some smaller changes to Notifications for 0.3.6, but that was mostly for supporting OS X and Windows.

**Comment by cubi7** [comment]
I am going to close this for the time being.  I think it may be a bug with XFCE and dual monitors.

**Comment by cubi7** [comment]
@olabini I should mention though that yes it did work with 0.3.6 and Qubes 3.1 / KDE DE
