### ISSUE TITLE
CoyIM requires too much horizontal space to see the "conversations" column

### ISSUE THREAD

**Issue by fowlslegs** [twstrike/coyim#376]
I'd like to have my IRC client and CoyIM each take up half of my screen, split vertically. However, even on my 1440p monitor, CoyIM will hide the "conversations" column from view unless I give it about 2/3 of the screen. I think it would be fine to shrink the contacts column, or even the text column. Keeping them at a ratio could work, but allowing the user to resize the 3 columns with their mouse (and storing that information in state) would be best.

**Comment by olabini** [comment]
Hi,

I'm a bit confused by this issue. Which version are you using? Are you using the "unified" mode?

**Comment by fowlslegs** [comment]
> I'm a bit confused by this issue.

I tried my best to describe it. Basically if you make the horizontal span of the window too small it hides the column in the unified view titled "Conversations." It'd be better if the three columns (contacts, message window, conversations) shrank down further to support smaller horizontal sizing of the window.

> Which version are you using?

3bf97af86ae12fdfcce823bb7c49bbf61bbf46cb

> Are you using the "unified" mode?

Yes.

**Comment by olabini** [comment]
That version is quite old. Would it be possible for you to update to a more modern version and see if the problem persists?

**Comment by fowlslegs** [comment]
I just built 1.0 using the README instructions (was using the .deb from subgraph repo before). Problem persists.

**Comment by olabini** [comment]
OK, thanks - I'll take a look!
When you say 1.0, what do you mean? We haven't released a 1.0 yet (the current version is 0.3.6)

**Comment by fowlslegs** [comment]
![2016-10-19-110920_579x613_scrot](https://cloud.githubusercontent.com/assets/3538418/19531475/a504ffa0-95ec-11e6-8f9b-1369c88e9142.png)

I built this using the directions exactly in the README... maybe another issue.
