### ISSUE TITLE
Graphical Add/Confirm New Contact

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#38]

**Comment by juniorz** [comment]
Should we support "Cancel presence notification" and "Unsubscribe" for a contact?

**Comment by olabini** [comment]
Yes, but not for the MVP

**Comment by juniorz** [comment]
It should be working, but I cant see the "contact request" on the other account. It may be broken, since both the CLI and the GUI have the same behavior.

**Comment by juniorz** [comment]
Found it. If you have already been accepted by the other peer, it will not see your request unless you "unsubscribe" before sending a new subscription request.
