### ISSUE TITLE
Can't add a new contact

### ISSUE THREAD

**Issue by rsdy** [twstrike/coyim#385]
I'm trying to add a new contact into CoyIM.
After clicking "Add" in the menu, I can't see the new contact appearing in my roster, however, I can see it in the `~/.config/coyim/accounts.json` under `Accounts[0].Peers`.

I'm not sure if it's related, but a contact also added me to their roster after I did, and I have not received any notification, nor did they appear in my roster.

Version: 3bf97af86ae12fdfcce823bb7c49bbf61bbf46cb

**Comment by rsdy** [comment]
Checking with another client, I can see that the roster invite has been sent. Maybe the UI could be more clear on this?

**Comment by olabini** [comment]
Hey
Do you want to see contacts you have sent a subscription request to in the roster? (with something like a question mark or something for status) - or are you looking for another type of behavior?

**Comment by rsdy** [comment]
Yes, I'd like to see invited contacts in my roster, with e.g. a question mark, or a different coloured "light" in front of the contact..
