### ISSUE TITLE
No alert to user that is needed to have Tor open

### ISSUE THREAD

**Issue by Dsuarezj** [twstrike/coyim#387]
When you open CoyIm without open TorBrowser, it does not notify (alert) to the user that you need to have it open to start a private conversation, and only get stuck in the attempt to start a conversation. 

![image](https://cloud.githubusercontent.com/assets/20112802/19781769/83232f5a-9c50-11e6-9099-cefc3b7b2ddf.png)

This confused me as an user the first time I was using CoyIm, make me think that i doesn't work.

**Comment by tcz001** [comment]
Thanks DJ for submitting this, I'm also considering adding tor as a bundled service, so that if there's no tor installed we still can use the embedded-tor for use. Created a new issue #388 for this.

**Comment by olabini** [comment]
The current behavior is quite different from this, and we are planning on changing the flow around Tor significantly.
