### ISSUE TITLE
ctrl-F show a textbox but not working as "finding" on mac

### ISSUE THREAD

**Issue by tcz001** [twstrike/coyim#391]
<img width="340" alt="screen shot 2016-11-01 at 4 15 43 pm" src="https://cloud.githubusercontent.com/assets/1702340/19907832/80f8864c-a04e-11e6-85af-1d045655bd86.png">

Can't even type anything inside.

**Comment by olabini** [comment]
Any ideas on why this happens on OS X? Another GTK/OS X bug?

**Comment by tcz001** [comment]
I couldn't find any code about this in coyim, is it a gtk built-in feature?

**Comment by olabini** [comment]
Yes, it's part of the treeview I think.

**Comment by tcz001** [comment]
ok, I will to look into gtk-osx... hope it's not too much to implement...

**Comment by olabini** [comment]
Any updates on this one?

**Comment by olabini** [comment]
Seen anything more on this?
