### ISSUE TITLE
Contact's fingerprints menu does not show the known fingerprints as advertised.

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#393]
### Coy version

0.3.7_1

### How to reproduce

1. Open a conversation window with a unverified contact
2. Send a message to start the private conversation
3. You will see the `You have not verified the identity of foo@example.com` warning.

In theory, at this moment you know the current fingerprint of `foo@example.com`. Continuing:

1. Right-click on `foo@example.com` in the contact list.
2. Chose "Fingerprints..."

### Actual behavior

You will see `There are no known fingerprints for foo@example.com` even though you know the fingerprint associated with this contact in the current conversation.

### Expected behavior

You should see, at least:

```
These are the fingerprints known for foo@example.com:

A0CBC473 380411C6 59E87088 031035ED 464C9270 not trusted
```

**Comment by olabini** [comment]
This only happens the _first_ time you start a conversation with an unverified contact. After that, the fingerprint will be saved.
