### ISSUE TITLE
Secure auto-update

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#394]
One nice thing from Tor Messenger is they can make use of the existing code from Tor Browser Bundle (based on the Mozilla solution) to do automatic updates in a secure way.

I don't know in details how the system works, and I have no idea if this is something we should build or something we should use any existing solution. I'm also not sure if we have the same requirements for security in the auto-update as Tor Browser Bundle (and Tor Messenger).

So I'm interested in resources and opinions if this is something worth doing (targeting v1.0?) or not.

**Comment by olabini** [comment]
I'm split on this feature as you know. While auto-update can be really good, it also brings alot of complexity to do well. My inclination is to not do this right now - and focus on other aspects.
