### ISSUE TITLE
Gdk-ERROR: X Window System

### ISSUE THREAD

**Issue by 3n7r0p1** [twstrike/coyim#395]
coyim 0.3.7_1 running on Debian-8 (Whonix-Workstation) under Xen (Qubes) hypervisor.

Errors began after Debian's bind9 updates today; however, I have not been a heavy user so it's possible I only noticed this now. Can not reproduce at will. Client crashes at random times while performing various actions: clicking inside windows, selecting menus, right-click contacts, etc.

Various error messages:
```
(CoyIM:1616): Gdk-ERROR **: The program 'CoyIM' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 62028 error_code 3 request_code 4 (core protocol) minor_code 0)
```
```
(CoyIM:1687): GLib-CRITICAL **: Source ID 5860 was not found when attempting to remove it
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
coyim: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x90 pc=0x55cf5d]
```
```
(CoyIM:1758): Gdk-ERROR **: The program 'CoyIM' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 110509 error_code 3 request_code 4 (core protocol) minor_code 0)
```
As advised: 
>    X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior.

Ran with `export GDK_SYNCHRONIZE=1`:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
coyim: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

(CoyIM:9743): Gdk-ERROR **: The program 'CoyIM' received an X Window System error.
This probably reflects a bug in the program.
The error was 'XSyncBadCounter'.
  (Details: serial 201579 error_code 134 request_code 134 (SYNC) minor_code 6)
```

I do have the full error-outputs saved but I can't tell if any personally identifying information is contained in them. Please advise. Thanks!

EDIT: added some color.

**Comment by 3n7r0p1** [comment]
My issue appears to have been installation-specific. It no longer occurs on a fresh system.
I was testing different IM clients but I can't isolate which one might have caused a conflict.
Sorry to bother - will reopen if needed.

**Comment by olabini** [comment]
Ah, thanks for letting us know!

**Comment by 3n7r0p1** [comment]
I've had a couple more crashes over the last few days. I've been running coyim with --debug but not GDK_SYNCHRONIZE. I no longer believe that these crashes are related to other IM clients.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x90 pc=0x55cf5d]
```
```
goroutine 1 [running, locked to thread]:
panic(0xf5b7a0, 0xc82000e160)
```
```
(CoyIM:1774): Gdk-WARNING **: CoyIM: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
Also, one crash with no --debug output.

**Comment by olabini** [comment]
Hmm, that's bad. Did you get any stack trace of any kind?

**Comment by olabini** [comment]
I also got the Fatal IO error 11 on a regular Fedora 24 box, so something is definitely happening here. I first thought it was related to Qubes, but that doesn't seem to be the case.

**Comment by olabini** [comment]
Based on some rudimentary googling, this seems like a problem that happens most often when GTK objects are accessed from different threads. In general CoyIM does this right in most places, but it seems we must have added some code recently that is not thread safe. It will be a bit tricky finding the place for this, sadly.

If there are any stack traces from your runs, that would be helpful. For me, the Fatal IO error 11 happened when I clicked on a user in the roster menu to start a conversation.

**Comment by 3n7r0p1** [comment]
> I first thought it was related to Qubes, but that doesn't seem to be the case.
Good to know. Last thing I want is to send you off on some edge-case.

Unfortunately, I deleted output when I thought I was in the clear. And there was really no discernible pattern to the crashes. I've been using coyim daily and haven't had any crashes in the past couple of days. Will update when I have something.

**Comment by olabini** [comment]
I suspect this and #410 is related

**Comment by olabini** [comment]
Since #410 has been closed, can you take a look and see if the problem persists with the newest version?

**Comment by olabini** [comment]
I haven't seen any crashes for months now, so this might be OK. Let's reopen if it comes back.
