### ISSUE TITLE
CoyIM failing on OSX Sierra

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#410]
Reported in this tweet: https://twitter.com/headhntr/status/806196097253134336

**Comment by tcz001** [comment]
[CoyIM] 2016/12/15 16:53:35 /Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:568: -> Stanza &data.ClientMessage{XMLName:xml.Name{Space:"jabber:client", Local:"message"}, From:"tdruiva@riseup.net/8994c5dd-4423-4b3e-a6ac-3643e0cf2b48", ID:"", To:"fanjiang@jabber.calyxinstitute.org/5fecccfa-b15f-4592-97c6-56e7270fd583", Type:"chat", Subject:"", Body:"?OTR:AAMDS2CZ4AxP/dEAAAAABQAAAAUAAADAf15b3RKzR5MsQoh9HGKkVbd3BEZFyd2QhNkxIDGdK5uudAOy6nMDBzmjdLkhpJkTtx10n8D13RO575+oP+owUpHzUDjtWII/REeDL6abMzsCGA5b2ugFBDliP0tETLwb6mg2OjaJXIgZOVfdW8b5fd46MjucCV+LRTHC8bxMyIYjlZbPAgxFXZH0JjnymxmDn+kHKtyBG15YlSjr6Yley/6EexvcYWrbjE304Pmq/oDU7iu1AMyRPu88sAtDHLDlAAAAAAAAAAEAAAEASMPneURwSFHVgc1IPuNuZb5+JfmW/DT0e14mhWYr6nalidVmqIW2ThlBKVrcBUV+oVilWhOJk6G6X5g5ZQzxJdHyl5MDKsIeeURd9qEPTQNPLmkmyIbVFXZg82c816FBvSN0J7DKoD7wM55ErJXfqzpBzwU12RItOd3qqGeMwcau9z0zHfMGm6eBRuwLsnvVLr1/nUwBz6nKCzLf7myJRuVQlZRbcggHz6OvY1HVUlcm4mOJXDVuKY+6RvvTmX1ma9I5DBZ2SZFt03wm7OtjNwYyNNMsvRTg/zrAfQayybtcnYne4m9O8PbLIkuAW78dvOmS2iMeZ/ArrbuGhC6hxtUJcxtG2xrKf12nRb+hAnCM1UsrAAAAtAGoBGXPfK5PG9x13HAi02/9iZD+AagEZc98rk8b3HXccCLTb/2JkP4BqARlz3yuTxvcddxwItNv/YmQ/gGoBGXPfK5PG9x13HAi02/9iZD+AagEZc98rk8b3HXccCLTb/2JkP6QDf4eIdbm2+O8nf7ywlmuz3sK7gGoBGXPfK5PG9x13HAi02/9iZD+AagEZc98rk8b3HXccCLTb/2JkP4BqARlz3yuTxvcddxwItNv/YmQ/g==.", Thread:"", Delay:(*data.Delay)(nil), Error:(*data.StanzaError)(nil), Extensions:data.Extensions{(*data.Extension)(0xc8204499e0), (*data.Extension)(0xc820449a40), (*data.Extension)(0xc820449a70), (*data.Extension)(0xc820449aa0), (*data.Extension)(0xc820449ad0)}}
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x45d2b75896ef pc=0x7fff9df97880]

runtime stack:
runtime.throw(0x4ea23e0, 0x2a)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4766390, 0xc820197b48, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/cgocall.go:123 +0x11b fp=0xc820197af8 sp=0xc820197ac8
github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x90081a0, 0x0, 0x802f9f0, 0x0)
	??:0 +0x41 fp=0xc820197b48 sp=0xc820197af8
github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib.(*Application).Run(0xc82002e148, 0x5800a18, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib/application.go:199 +0x3d7 fp=0xc820197c10 sp=0xc820197b48
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc8200f72b0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:297 +0x13b fp=0xc820197cb0 sp=0xc820197c10
main.runClient()
	/Users/travis/gopath/src/github.com/twstrike/coyim/gtk.go:28 +0x35c fp=0xc820197ea8 sp=0xc820197cb0
main.main()
	/Users/travis/gopath/src/github.com/twstrike/coyim/main.go:35 +0xc7 fp=0xc820197f40 sp=0xc820197ea8
runtime.main()
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/proc.go:188 +0x2b0 fp=0xc820197f90 sp=0xc820197f40
runtime.goexit()
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820197f98 sp=0xc820197f90

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).watchCommands(0xc8200f72b0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/commands.go:58 +0xa2
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:290 +0xa3

goroutine 6 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc8200f72b0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/account_events.go:48 +0x59
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:291 +0xc5

goroutine 45 [chan receive, 3 minutes]:
github.com/twstrike/coyim/xmpp.(*conn).watchKeepAlive(0xc8202cc000, 0x135ba2b8, 0xc8201e6088)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/keepalive.go:26 +0x1b2
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/dialer.go:132 +0x304

goroutine 18 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.observe(0xc8201fc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x9a
created by github.com/twstrike/coyim/session.Factory
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:158 +0x605

goroutine 19 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc8201fc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/reconnect.go:11 +0x6a
created by github.com/twstrike/coyim/session.Factory
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:159 +0x627

goroutine 20 [chan receive]:
github.com/twstrike/coyim/session.observe(0xc8201fc160)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x9a
created by github.com/twstrike/coyim/session.Factory
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:158 +0x605

goroutine 21 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc8201fc160)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/reconnect.go:11 +0x6a
created by github.com/twstrike/coyim/session.Factory
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:159 +0x627

goroutine 70 [IO wait, 1 minutes]:
net.runtime_pollWait(0x135bb288, 0x72, 0xc82048a000)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82024a1b0, 0x72, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82024a1b0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82024a150, 0xc82048a000, 0x800, 0x800, 0x0, 0x8200028, 0xc8200120e0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201e6088, 0xc82048a000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8202228a0, 0x12fc2348, 0xc8201e6088, 0x5, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8202f2000, 0x4f44a17, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8202f2000, 0xc8202f5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:939 +0x167
io.(*teeReader).Read(0xc820311020, 0xc8202f5000, 0x1000, 0x1000, 0xc820480158, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/io/io.go:513 +0x7c
bufio.(*Reader).fill(0xc820237920)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc820237920, 0x5, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/bufio/bufio.go:229 +0x7a
encoding/xml.(*Decoder).getc(0xc82023da20, 0x47c0740)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:870 +0xad
encoding/xml.(*Decoder).rawToken(0xc82023da20, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:516 +0x148
encoding/xml.(*Decoder).Token(0xc82023da20, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:248 +0xe7f
github.com/twstrike/coyim/xmpp.nextElement(0xc82023da20, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/xml.go:46 +0x93
github.com/twstrike/coyim/xmpp.next(0x8209590, 0xc8202cc000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/xml.go:87 +0xc3
github.com/twstrike/coyim/xmpp.(*conn).Next(0xc8202cc000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/connection.go:182 +0xdc
github.com/twstrike/coyim/xmpp.(*conn).ReadStanzas(0xc8202cc000, 0xc8203b01e0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/connection.go:272 +0x9e
github.com/twstrike/coyim/session.(*session).readStanzasAndAlertOnErrors(0xc8201fc000, 0xc8203b01e0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:358 +0x5c
created by github.com/twstrike/coyim/session.(*session).watchStanzas
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:352 +0x88

goroutine 24 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToToggleConnectAllAutomatically(0xc8200f72b0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:543 +0x43
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:232 +0x184

goroutine 25 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToSetShowAdvancedSettings(0xc8200f72b0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:559 +0x43
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/ui.go:233 +0x1a6

goroutine 293 [chan receive, 1 minutes]:
github.com/twstrike/coyim/session.(*session).listenToNotifications(0xc8201fc160, 0xc820286f00, 0xc8201bd480, 0x12)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:504 +0x5c
created by github.com/twstrike/coyim/session.(*session).NewConversation
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:553 +0x3ee

goroutine 225 [IO wait]:
net.runtime_pollWait(0x135bb1c8, 0x72, 0xc8202aa000)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82029a140, 0x72, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82029a140, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82029a0e0, 0xc8202aa000, 0x4000, 0x4000, 0x0, 0x8200028, 0xc8200120e0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82026e0d0, 0xc8202aa000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820270f00, 0x12fc2348, 0xc82026e0d0, 0x5, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200b2300, 0x4f44a17, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8200b2300, 0xc82016a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/crypto/tls/conn.go:939 +0x167
io.(*teeReader).Read(0xc8201e4280, 0xc82016a000, 0x1000, 0x1000, 0xc8200b1ae0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/io/io.go:513 +0x7c
bufio.(*Reader).fill(0xc820014240)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc820014240, 0x7, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/bufio/bufio.go:229 +0x7a
encoding/xml.(*Decoder).getc(0xc82028c000, 0x1a107)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:870 +0xad
encoding/xml.(*Decoder).rawToken(0xc82028c000, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:516 +0x148
encoding/xml.(*Decoder).Token(0xc82028c000, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/encoding/xml/xml.go:248 +0xe7f
github.com/twstrike/coyim/xmpp.nextElement(0xc82028c000, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/xml.go:46 +0x93
github.com/twstrike/coyim/xmpp.next(0x8209590, 0xc82024c240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/xml.go:87 +0xc3
github.com/twstrike/coyim/xmpp.(*conn).Next(0xc82024c240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/connection.go:182 +0xdc
github.com/twstrike/coyim/xmpp.(*conn).ReadStanzas(0xc82024c240, 0xc8200143c0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/connection.go:272 +0x9e
github.com/twstrike/coyim/session.(*session).readStanzasAndAlertOnErrors(0xc8201fc160, 0xc8200143c0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:358 +0x5c
created by github.com/twstrike/coyim/session.(*session).watchStanzas
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:352 +0x88

goroutine 46 [chan receive, 3 minutes]:
github.com/twstrike/coyim/xmpp.(*conn).watchPings(0xc8202cc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/ping.go:61 +0xc4
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/dialer.go:133 +0x326

goroutine 66 [sleep, 3 minutes]:
time.Sleep(0x29e8d60800)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/time.go:59 +0xf9
github.com/twstrike/coyim/session.(*session).watchRoster(0xc8201fc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:803 +0x3e
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:938 +0x232

goroutine 68 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.(*session).watchTimeout(0xc8201fc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:767 +0xaf
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:940 +0x27c

goroutine 69 [chan receive, 1 minutes]:
github.com/twstrike/coyim/session.(*session).receiveStanza(0xc8201fc000, 0xc8203b01e0, 0xc8201fc001)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:326 +0x89
github.com/twstrike/coyim/session.(*session).watchStanzas(0xc8201fc000)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:353 +0xa0
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:941 +0x2a1

goroutine 285 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc820202240)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/account.go:245 +0x68
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/account.go:269 +0x118

goroutine 284 [chan receive, 1 minutes]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc820202090)
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/account.go:245 +0x68
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/travis/gopath/src/github.com/twstrike/coyim/gui/account.go:269 +0x118

goroutine 217 [chan receive, 3 minutes]:
github.com/twstrike/coyim/xmpp.(*conn).watchPings(0xc82024c240)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/ping.go:61 +0xc4
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/dialer.go:133 +0x326

goroutine 216 [chan receive, 3 minutes]:
github.com/twstrike/coyim/xmpp.(*conn).watchKeepAlive(0xc82024c240, 0x135ba2b8, 0xc82026e0d0)
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/keepalive.go:26 +0x1b2
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/travis/gopath/src/github.com/twstrike/coyim/xmpp/dialer.go:132 +0x304

goroutine 221 [sleep, 3 minutes]:
time.Sleep(0x29e8d60800)
	/Users/travis/.gimme/versions/go1.6.3.darwin.amd64/src/runtime/time.go:59 +0xf9
github.com/twstrike/coyim/session.(*session).watchRoster(0xc8201fc160)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:803 +0x3e
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:938 +0x232

goroutine 223 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.(*session).watchTimeout(0xc8201fc160)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:767 +0xaf
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:940 +0x27c

goroutine 224 [chan receive]:
github.com/twstrike/coyim/session.(*session).receiveStanza(0xc8201fc160, 0xc8200143c0, 0xc8201fc101)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:326 +0x89
github.com/twstrike/coyim/session.(*session).watchStanzas(0xc8201fc160)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:353 +0xa0
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:941 +0x2a1

goroutine 294 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.(*session).listenToDelayedMessageDelivery(0xc8201fc160, 0xc820286f60, 0xc8201bd480, 0x12)
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:514 +0x4b
created by github.com/twstrike/coyim/session.(*session).NewConversation
	/Users/travis/gopath/src/github.com/twstrike/coyim/session/session.go:556 +0x475

**Comment by olabini** [comment]
This is likely to be due to us doing something graphic related outside the main thread, and Sierra makes that more likely to hit. Can someone with Sierra potentially look into this?

**Comment by tcz001** [comment]
It seems the latest build doesn't crash on my machine anymore

**Comment by olabini** [comment]
Great! Let's close this, and if we see it again, open it again.
