### ISSUE TITLE
Newline not inserted at cursor position

### ISSUE THREAD

**Issue by bfix** [twstrike/coyim#412]
When a newline is inserted into a message, it does not get inserted at the cursor position, but always at the end of the message.

**Comment by olabini** [comment]
Hi, thanks for the report!

I'm not sure I understand how to reproduce this problem - can you specify a little bit more what you do to make it happen?

**Comment by bfix** [comment]
Write a multiline message like:
---
line1
line2line3
line4
----
now move the cursor after "line2" and press shift-enter to enter a line break at that position. Instead a new line at the end of the message is inserted.

**Comment by olabini** [comment]
Thanks. This issue has been fixed on master.
