### ISSUE TITLE
Arc Dark theme renders text unreadable under GNOME3

### ISSUE THREAD

**Issue by georgeowell** [twstrike/coyim#419]
Noticed there's white text on grey background readability issues with Arc-Dark theme enabled under GNOME3. This isn't an issue with the default Adwaita theme.

![coyim dark](https://cloud.githubusercontent.com/assets/18296993/22119890/30e9f536-de75-11e6-93b1-060267c7042c.png)

Obviously I blurred the text but you can you can still see the problem and it's easy to reproduce. This is a popular theme that's shipped as default on some distros, so I thought I'd open the issue. 

**Version:** GNOME 3.22
**GTK+ Theme:** Arc-Dark 
**Shell Theme:** Arc-Dark

**Comment by kn00tcn** [comment]
is arc not supposed to deal with this? https://github.com/horst3180/arc-theme/issues the css in arc clearly contains very specific lines for various individual apps already

**Comment by olabini** [comment]
As kn00tcn mentions, this isn't something we can do much about. We recognize the global dark themes when they are used, but Coy can't hard code knowledge about specific themes into the application - that needs to exist in the theme.
