### ISSUE TITLE
Google don't see CoyIM as secure app

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#420]
Looks like Google have changed its strategy to allow third apps to connect to your account.
Before was used to generate a password for each app but now it asked me to allow less secure apps feature to be able to connect.

https://support.google.com/accounts/answer/6010255?hl=en

Do they have any guideline to be considered as secure?

**Comment by tdruiva** [comment]
**What criteria is used to identify an application as being “less secure”?**
`Applications that rely on plain username/password authentication to access an account programmatically are considered less secure than those using modern day security standards such as OAuth 2.0.`

https://support.google.com/a/answer/6260879?hl=en

**Comment by Atavic** [comment]
Google dropped Open Standards for Instant Messaging, as XMPP protocol.
Also OTR 3 protocol is far more secure than OAuth 2.0
https://en.wikipedia.org/wiki/OAuth#Controversy

**Comment by olabini** [comment]
Actually, the "secure apps" thing is not new - it's been this way since before we created Coy. I don't see this is a bug we can do anything about.

**Comment by Atavic** [comment]
"Secure apps" as defined by google is an uncommon definition, used by Google to push their own standards.
