### ISSUE TITLE
Messages sent in plain text after pressing secure chat button.

### ISSUE THREAD

**Issue by iapazmino** [twstrike/coyim#426]
Messages seem to be sent in plaintext even after I press the "Secure chat" button in the conversation window. Is this expected?

Steps to reproduce:

    Disable Require Encryption.
    Open the conversation window.
    Click the "Secure chat" button.
    Send messages.

The messages I type are displayed in my history after the Attempting to start a private conversation... line, and the recipient receives them in plaintext.

**Comment by olabini** [comment]
Not sure if I understand this issue. I assume wht you mean is that you type and send something BEFORE the OTR session has finished setting up? In that case, yeah, I would expect that to be sent in plaintext. Or do you mean something different?

**Comment by iapazmino** [comment]
Before, when encrypted messages were added to the transcript before notifying the secure conversation had started, produced the impression these messages were sent in plain text. Fixed with 1246fd3c0b05b8d920abf3ca0f21deafea9140f2
