### ISSUE TITLE
Flatpak or AppImage

### ISSUE THREAD

**Issue by baimafeima** [twstrike/coyim#429]
Could you add either Flatpak or AppImage releases (depending on which you consider the more secure solution for end-users) in addition to versioned tarballs here on GitHub? This would significantly increase the potential user base and make it easier to test the application and report bugs, especially for those who are unable to compile from source.

**Comment by olabini** [comment]
Hi,

I don't think there is any real value to Flatpak or AppImage for us at the moment. We have a separate issue for tracking sandboxing - (#108). And for distribution of compiled binaries, we refer to https://coy.im where you can find precompiled files for all operating systems.

**Comment by baimafeima** [comment]
@olabini For Linux-based operating systems it would still need to be compiled, hence my request for an easy cross-platform release in the form of either a Flatpak or an AppImage.

**Comment by olabini** [comment]
@baimafeima - I'm confused by your comment - as I mentioned, on the website we have precompiled executables for Linux as well. Additionally, for Linux, an application like CoyIM should be distributed through the package managers - which we are working on and tracking in a few different issues. Flatpak or AppImage doesn't help in any way.

**Comment by yurkobb** [comment]
In my opinion, Flatpak does have value *to the user* by providing a ready sandbox for running not-100%-trusted applications. So, to try and run coyim now I would need to wrap it with a sandbox myself. With Flatpak, it's built-in.

P.S. Of course I'm assuming good faith and am not expecting coyim developers to provide me with malware:) But as a general practice I'm hesitant to run any software not from my distribution with 100% privileges.

**Comment by olabini** [comment]
I completely agree that a sandbox for CoyIM is a very important thing to have - however, from what I've seen, Flatpak is not the strongest solution for this. We are tracking sandboxing in #108.

And incidentally, even if you assume good faith, the CoyIM developers are not perfect and there will be bugs. Sandboxes protect you against those kinds of things as well.

And you're completely right about not trusting things from outside your distribution - which is also one of the reasons why we're working to get CoyIM into the package managers for different distributions as well, as mentioned above.

**Comment by yurkobb** [comment]
Having CoyIM in all major distributions would of course be great. I wanted to learn Fedora packaging, but haven't got there yet... 

However, if I were to download and run a binary, it wouldn't probably make it more trusted to me if it claimed to be sandboxed (chicken and egg problem basically - do I trust the sandbox that the binary claims to include?).

So a package manager like Flatpak which installs each app within its own sandbox seems like a good starting point. What weaknesses does Flatpak's sandbox have that are relevant in the context of CoyIM?

**Comment by TNTBOMBOM** [comment]
>So a package manager like Flatpak which installs each app within its own sandbox seems like a good starting point. What weaknesses does Flatpak's sandbox have that are relevant in the context of CoyIM?

bubblewrap not only exposes security vulnerabilities in the kernel but also in the window compositor. Users should be aware that running untrustworthy code in bubblewrap is still not safe.
