### ISSUE TITLE
[coyim-cli] Output does not show up well

### ISSUE THREAD

**Issue by rosatolen** [twstrike/coyim#437]
Currently, using the command "/help" will result in the following output:
![coyim-cli_output](https://user-images.githubusercontent.com/2407070/29589536-34de64ee-875b-11e7-91b3-ec67de4e0838.png)

I am using gnome-shell 3.22.3-1 on ArchLinux.

**Comment by claucece** [comment]
This was related to
https://github.com/golang/crypto/commit/911fafb28f4ee7c7bd483539a6c96190bbbccc3f

and 
https://github.com/nogoegst/terminal/commit/c142040ecbde3c1ea57db8f64ba6ff011a852428
