### ISSUE TITLE
Crash when registering a new jabber account

### ISSUE THREAD

**Issue by toast** [twstrike/coyim#438]
I haven't used jabber in a while and don't remember my credentials, so I went to create a new jabber account as part of trying out CoyIM. This animated gif shows the steps I took before CoyIM crashed:

[https://giphy.com/gifs/3o7aCYPJPRtn6rsVUY/fullscreen](https://giphy.com/gifs/3o7aCYPJPRtn6rsVUY/fullscreen)

### Steps to reproduce the behavior:
1. Launch CoyIM (v0.3.8) for the first time after installing using the dmg downloaded from https://coy.im/ home page.
2. Choose to encrypt the settings file with a password (64 characters)
3. On 'Setup your first account' choose 'Register account'
4. On 'Choose a server to register your account' go with the default 'jabber.calyxinstitute.org'
5. On selecting 'Next' - CoyIM crashes

**Expected behavior**: progress to the next step of creating the jabber account.
**Actual behavior**: CoyIM crashes

### Meta-information

**From Console app 'system.log' section:**
Aug 27 22:09:59 com.apple.xpc.launchd[1] (im.coy.coyim.14908[25877]): Service exited with abnormal code: 2

**Date / time of crash:**
27th August 2017 22:09:59

**CoyIM version:**
v0.3.8 ('dogfood')

**OSX version**
10.12.3 (Sierra) (it's a macbook pro)

**Comment by claucece** [comment]
Hey!

Thanks for pointing out this issue. It has already been fixed on 7172ea687f07a742c82247974c7c00cabcca8336. :)
