### ISSUE TITLE
Security audits

### ISSUE THREAD

**Issue by baimafeima** [twstrike/coyim#440]
> Use of a unified security rating that combines several different measures of security.

You've mentioned that there have not been any security audits. Do you have anyone in mind who would conduct security audits and when would this be planned? I know that EFF is working on a new scorecard for text, voice and video applications and it might make sense to get yourself involved there. On the other hand, I am not sure to what extent this is an actual security audit.

**Comment by olabini** [comment]
Hi, this is a duplicate of #297 
In terms of when and who, we are still not at the stage of feature completeness where we feel it makes sense to audit coyim. We have several mayor features we want to implement, and we also would like to have reproducible builds working on windows and Mac before looking at auditing.
