### ISSUE TITLE
voice and video chat and screen sharing

### ISSUE THREAD

**Issue by baimafeima** [twstrike/coyim#442]
I would like to briefly confirm what kind of features are already implemented and which ones are planned or not planned (beyond what I read on your website):
- voice chat
- video chat
- screen sharing

**Comment by olabini** [comment]
Hi,

Neither of these features are planned for CoyIM - we want CoyIM to be a solid instant message solution with high security - adding voice or video would introduce too much complexity for us to feel comfortable with the security of the application.

**Comment by baimafeima** [comment]
Thanks for the feedback and I can understand your decision. It would perhaps make sense to emphasize this on your website.
