### ISSUE TITLE
Migrate to GTK+ 3

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#46]
We are currently using a modified version of `mattn/go-gtk` which is GTK+ 2. That would be another open source contribution.

By the way, `pond` uses its own `go-gtk` which has been migrated to GTK+ 3.

**Comment by olabini** [comment]
I think we should use GTK+ 3. Any thoughts on how much work it would be to migrate?

**Comment by juniorz** [comment]
I started to play with this last night.

`pango` and `glib` can simply be copied from `go-gtk`; there seems to be no version change. `gdk` and `gtk` have a bunch of missing symbols.

I tried to go lame and use SWIG, but it's not easy. Then I started to migrate manually each widget in GTK.

It's a boring manual process unless some programming language geek comes with an easy way to parse the header files, extract each function, and translate them to golang and also convert them to methods.

I have't tried to use the version made by `agl` though.

**Comment by juniorz** [comment]
I'm experimenting with `agl/go-gtk`. Building it reveals a bunch of deprecation warnings: https://gist.github.com/juniorz/1ba9225bd004c549c0a8

There's a lot of differences in coding style between `agl/go-gtk` and `mattn/go-gtk`:

- classes prefixed with `Gtk` - `gtk.Window` becomes `gtk.GtkWindow` :disappointed:
- constants prefixed with `GTK_` - `WINDOW_TOPLEVEL`becomes `GTK_WINDOW_TOPLEVEL`
- `IWidget` is `WidgetLike`
- The constructors are not `gtk.NewWindow` but `gtk.Window`
- No `VBox` and `HBox`, only `Box`
- Constants are not referencing their counterparts in GTK, but redefined with the same value. It may break if GTK changes their value.
- By convention, it uses interfaces and methods rather than functions to access the reference to the native gobject. As a consequence, passing `nil` where a wrapped GObject is expected breaks the app.
For example: `gtk_menu_item_set_submenu` accepts `NULL` to remove a submenu. `menuItem.SetSubmenu(nil)` works on `mattn/go-gtk` but breaks on `agl/go-gtk`. You are forced to use a typed `nil`, like `menuItem.SetSubmenu((*gtk.GtkWidget)(nil))`

**Comment by juniorz** [comment]
Everything seems to be working now. I believe we should rebase `agl/go-gtk` on `mattn/go-gtk` before moving forward with this.

For example, I had to reapply https://github.com/twstrike/go-gtk/commit/46059afd946e854828b61181ee591211bd441741 to make it work.

`mattn` version already had it, and it fixes the data structure to match the definition at https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventKey

**Comment by olabini** [comment]
So, as mentioned earlier, I think we should just go with https://github.com/gotk3

**Comment by olabini** [comment]
This is done, correct?
