### ISSUE TITLE
Fail to send message after the other end closes the OTR channel

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#47]
When you attempt to send a message after the other end has closed the OTR channel, you receive a `cannot send message because secure conversation has finished` error.

This is intended to protect us from accidentally sending a message through an unencrypted channel. The protocol says we should store the message for possible retransmission once when the channel is restored. Should we implement this? Where (client vs protocol)?

This is a very confusing moment, and an opportunity to improve the experience.

**Comment by olabini** [comment]
Well, the OTR3 implementation already takes care of that.

**Comment by juniorz** [comment]
I guess I know what is happening.

Following the same principle as the `wipe` functions, I had decided to release the `Conversation` object when the OTR channel is finished, so it would not stay in memory when it's not needed. But it seems to break the retransmission.

**Comment by olabini** [comment]
Ah. =/

**Comment by juniorz** [comment]
This will be fixed by #48
