### ISSUE TITLE
Restarting the OTR channel after the other end closes it

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#48]
Adium's UI does not allow you to restart the OTR channel after the other end terminates it unless you terminate the channel on your side.

I can think of 2 possible reasons for this:

- Making sure all data structures are freed/wiped before starting another conversation
- Making sure you will reveal the final MAC keys before you start a new conversation

We are currently doing this differently. Should we do not?

The second reason seems to be reasonable enough for me, but nothing prevents me from not ending the conversation on my side. Restarting the AKE will not wipe the the reveal MAC keys, and the final MAC keys will be revealed as soon as you send the next encrypted message. But again there's no guarantee this will happen.

I'm concerned about this being a responsibility of the client rather than the protocol. Having retransmission builtin the protocol (see #47) would move this responsibility to the protocol, but would not fix it.

xmpp-client has an `OTRAutoTearDown` config which seems to be used to address this issue.

**Comment by olabini** [comment]
Yeah, I like the idea of auto tear down. I see no reason to keep the OTR season alive once the other person has killed it.
