### ISSUE TITLE
config.go reduces the available cipher suites to only ECDHE ones

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#50]
This might be too restrictive. We should revisit.

**Comment by tcz001** [comment]
Is this a bug or feature?

**Comment by olabini** [comment]
It's more a task to review these settings.

**Comment by olabini** [comment]
After reviewing the available ciphers and looked at our settings, I decided to make it possible to use RSA for key exchange as a final possibility. This makes it possible to set up a non-PFS session to the server in the worst case, but in that case we can add warnings around the security rating for this.
