### ISSUE TITLE
Locked down build

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#51]
It would be great to have a build that is basically completely locked down, where you can't change any of the settings to be less secure. 
This won't suit everyone, but might be useful for a smaller group of high-risk people.

**Comment by juniorz** [comment]
This should not be hard to do. We could have a build tag for that, like `go get -tags locked-down github.com/twstrike/coyim`, and it would be orthogonal to the UI selection.

**Comment by olabini** [comment]
After thinking about this for a while, I don't feel it's appropriate, at least not right now. We should already be locked down in general.
