### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#52]
In case we are planning to distribute static builds[1] for `coyim`, I found some information that might be relevant:

### GTK

> Remember that GTK is licensed under LGPL, which essentially means that in order to link it to your application _statically_, your application will have to be (L)GPL-licensed.

Source: https://wiki.wxwidgets.org/Linking_With_Gtk_And_Running_On_Any_Linux

> Specifying --enable-explicit-deps or --enable-static can cause compatibility problems when libraries that GTK+ depends upon change their versions, and should be avoided if possible.

Source: https://developer.gnome.org/gtk3/stable/gtk-building.html

### Darwin/OS X

The `man` page got `gcc` used to mention:
>This option will not work on Mac OS X unless all libraries (including libgcc.a) have also been compiled with -static. Since neither a static version of libSystem.dylib nor crt0.o are provided, this option is not useful to most people.

Source: https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag/3801032#3801032

In the context of golang, the `net` package mentions[2]:
> On Unix systems, the resolver has two options for resolving names. It can use a pure Go resolver that sends DNS requests directly to the servers listed in /etc/resolv.conf, or it can use a cgo-based resolver that calls C library routines such as getaddrinfo and getnameinfo.

OS X it is supposed to use the cgo-based resolver which would require statically linking against `getaddrinfo` and `getnameinfo`, which is not possible unless we static versions of `libSystem.dylib` and `crt0.o`.

1 - https://en.wikipedia.org/wiki/Static_build
2 - https://golang.org/pkg/net/

**Comment by olabini** [comment]
sigh.

**Comment by olabini** [comment]
After discussing this in person:
- We can probably make this work for Linux
- It would be useful to have a static version for Tails, for example
- We can't make it work for OS X or Windows, probably
- But that's OK. The only thing we need is for the OS X and Windows things to have a downloadable installer that installs everything - no MacPorts or Brew needed.

**Comment by olabini** [comment]
Thinking more about it, I don't think there is any real point. It's definitely not interesting for reproducible builds. Closing the issue for now.
