### ISSUE TITLE
Use Tor hidden service if we can

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#56]

**Comment by juniorz** [comment]
Calyx Institute already responds to SRV requests with a hidden service address, which has higher priority than the other address.

```
_xmpp-client._tcp.jabber.calyxinstitute.org. 899 IN SRV	4 0 5222 ijeeynrc6x2uy5ob.onion.
_xmpp-client._tcp.jabber.calyxinstitute.org. 899 IN SRV	5 1 5222 jabber.calyxinstitute.org.
```

PR #70 (plus auto-detecting Tor in #15) gives us this for free in such cases. Is this issue about improving the list of hardcoded mapping between servers and hidden services?

**Comment by olabini** [comment]
AFAIK it's only the CLI that uses the hardcoded list right now. But yeah, expanding it is also a good idea.

**Comment by juniorz** [comment]
Both CLI and GUI are using the same hardcoded list.
