### ISSUE TITLE
Text entry should be a gtkentry, not a gtktextview

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#57]

**Comment by juniorz** [comment]
To rephrase my concern about this: a `GtkEntry` will make it harder to review/edit a multiline message copied and pasted from somewhere else before sending, since it's harder to review multiline text inside a single-line `GtkEntry`.

**Comment by olabini** [comment]
Yes, absolutely. But looking at all the other clients out there, and how confusing it is to have a multiline thing where pressing enter actually sends the message I think that having an Entry is still better. Just look at Facebook messages and all the mess they've had to do (and they have changed several times now)

**Comment by xSmurf** [comment]
I would like to see this re-discussed. I'm not sure what Facebook had to go through but this is the behavior of every chat program I've used in the passed decade and half.

![IMHO something like this is absolutely unacceptable.](https://cloud.githubusercontent.com/assets/525356/13204480/f2c31772-d8c8-11e5-906d-4783690a7a19.png)

Almost every program retains `enter` to send and uses `<ctrl>enter` to insert a new line (although some, such as Adium make that configurable - but this is still the default). Many, such as Gajim, just grow the TextBox as needed (up to a point where it enables scrolling).

**Comment by olabini** [comment]
Wait, I have no idea what you're arguing for here? And not what the screenshot has to do with either, actually.

**Comment by xSmurf** [comment]
Sorry I had most of it written down first and then found this closed issue and sort of reworked what I had into a comment here but failed to convey the same message I guess. I have updated the original message with more information.
