### ISSUE TITLE
New account dialog smaller fixes

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#60]
- [x] There should be explanation text
- [x] Default port should be 5222, not 0
- [x] The socks URL display is pretty bad with username and password. I think we should just hide that stuff
- [x] Account and server are very confusing. We should probably have example texts that show what they should be 
- [x] Server, port and socks should not be displayed at all right now - they should be only for advanced users

**Comment by tdruiva** [comment]
What do you think if user decided not to encrypt CoyIM we don't allow to save password?
