### ISSUE TITLE
Basic key bindings for Gnome would be good.

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#69]

**Comment by juniorz** [comment]
What are the basic keybindings?

**Comment by olabini** [comment]
So, @juniorz, it seems we need better support for accelerators for much of this work. Specifically, it would be fantastic if we can implement gtk_accelerator_parse and gtk_accel_group_connect. Many of the other accelerator functions will be helpful as well, of course.

Can we pair on this tomorrow so I learn the process?

**Comment by juniorz** [comment]
Absolutely, sir.
Em 18/10/2015 4:25 PM, "Ola Bini" <notifications@github.com> escreveu:
