### ISSUE TITLE
Connect to Tor using unix domain socket

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#71]
I suspect it should be enough to setup the proxy to `unix:/var/run/tor.sock` and it should "just work", since the `net` package mentions it: https://golang.org/pkg/net/#UnixAddr

Should we probe for it? What should it priority be comparing to the ports 9050 and 9150? Is there a default place for this file?

**Comment by juniorz** [comment]
I could not find any standard way to represent a socks5 proxy using an unix domain socket in the config file.

Initially I thought it should be an URI containing the `socks5` scheme, and also indicate that the host is a path in the filesystem that represents an address in the `unix` network (in golang's `net` pkg lingo).

I thought about using an URI with `socks` scheme and an opaque part containing the address represented as an URL in the `unix` network. The result would be like this `socks5://unix:///Users/rjunior/torsock/tor.sock`, but that seems horribly ugly.

According to RFC 3986, "each scheme's specification may further restrict the syntax and semantics of identifiers using that scheme", but I could not find any spec for the scheme `socks5` in RFC 1928.

On the other hand, `net/proxy` allows us to provide Dialer generators for different schemas, so we could use a custom scheme (for example, `socks5+unix`) with a generator as simple as:

```
net.RegisterDialerType("socks5+unix", func(u *url.URL, d Dialer) (Dialer, error){
    auth := authFrom(u.User)
    return net.SOCKS5("unix", u.Path, auth, d)
})
```

A custom scheme seems to be a good choice because `socks5` scheme implies the SOCKS5 protocol proxying request in the `tcp` or `udp` networks (according to the standard https://en.wikipedia.org/wiki/SOCKS#SOCKS5). `socks5+unix` would imply the same thing, but through a connection in the `unix` network.

I'm not an RFC 3986 expert, so I'd like to hear some ideas.

**Comment by olabini** [comment]
Sounds good to me - lets do a custom scheme. I'll see if there's a default place for the file.

**Comment by olabini** [comment]
It seems that Tor doesn't open this by default. So to me, this means it will have be an advanced option that someone will have to manually configure. We can offer the option, but shouldn't probe for it by default.

**Comment by juniorz** [comment]
This is done. You need to manually change change the config file.
