### ISSUE TITLE
Advanced config options

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#72]
Every configuration that is not enable by default, which can either cover a particular configuration need or lower the security for compatibility reasons.

- [x] Connect to Tor using an unix domain socket
- [x] Turn off Tor
- [x] Turn off Encryption Required
- [x] Force/disable encryption for specific contacts (`AlwaysEncryptWith` and `DontEncryptWith`)

**Comment by juniorz** [comment]
b236007 allows turning off encryption required.

**Comment by csoghoian** [comment]
It would be handy to be able to specify a IP address/port for the Tor client, for users running under Qubes. Right now, I have to run an additional Tor client in my coyim VM, instead of being able to use the Tor client already running in my whonix VM.

**Comment by olabini** [comment]
Yes, absolutely.

**Comment by juniorz** [comment]
@csoghoian, specifying an IP/port for the Tor client is implemented as part of #215.

You need to edit your account and change the proxy, after enabling the "advanced settings".

**Comment by olabini** [comment]
I don't even know if I want us to be able to turn off TLS.

**Comment by olabini** [comment]
The final pieces of this functionality has been implemented now.
