### ISSUE TITLE
Signing up to an account from inside the client

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#8]
XMPP supports signing up from the client.

**Comment by tcz001** [comment]
related specific:
[xep0077](http://xmpp.org/extensions/xep-0077.html)

**Comment by olabini** [comment]
This becomes harder when it comes to making sure we use Tor, solving captchas, etc.

**Comment by tdruiva** [comment]
-[ ] display list of XMPP servers
-[ ] show errors
-[ ] ability to send additional information as captcha

**Comment by tcz001** [comment]
https://github.com/twstrike/coyim/blob/57d72b49e348069496db6ad5d3ce56a1d952412d/xmpp/register.go

**Comment by tcz001** [comment]
https://github.com/twstrike/coyim/blob/master/xmpp/register.go

**Comment by juniorz** [comment]
I believe this is done, at a very basic level. It has no support for captchas or any field that is not a text entry, but we can handle this as separate small issues. It also needs some work on the UI, but it works.
