### ISSUE TITLE
Handle "user is typing" messages

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#85]
I noticed we receive a stanza with an empty `Body` when the other peer starts typing. We are considering it an error, since such message is forwarded to the OTR conversation.

**Comment by olabini** [comment]
What other things are in the stanza? What kind of stanza is it? client:message?

**Comment by juniorz** [comment]
```
&xmpp.ClientMessage{XMLName:xml.Name{Space:"jabber:client", Local:"message"}, From:"xxx@dukgo.com/kingnaldo", ID:"purple1659f7e2", To:"strike-test@dukgo.com", Type:"chat", Subject:"", Body:"", Thread:"", Delay:(*xmpp.Delay)(nil)}
```

**Comment by olabini** [comment]
Strange. Nothing in it at all. Have you found a spec that clarifies this behavior?

**Comment by juniorz** [comment]
XEP-0085[1] mentions state notifications. I'm reading it.

https://xmpp.org/extensions/xep-0085.html

**Comment by juniorz** [comment]
I noticed that the extensions work by adding xml nodes inside the `<message>`. It may be the case that we are receiving a message that has only the extension body.

This is an example from XEP-0085

```
<message 
    from='bernardo@shakespeare.lit/pda'
    to='francisco@shakespeare.lit/elsinore'
    type='chat'>
  <composing xmlns='http://jabber.org/protocol/chatstates'/>
</message>
```

And an example from XEP-0022:

```
<message to='romeo@montague.net' id='message22'>
  <body>Art thou not Romeo, and a Montague?</body>
  <x xmlns='jabber:x:event'>
    <offline/>
    <delivered/>
    <composing/>
  </x>
</message>
```

**Comment by olabini** [comment]
Yeah, that's what I would expect. But actually, have you looked at the raw data?
Golangs XML deserialization ignores elements it doesn't know how to deserialize, so it could be that those elements are coming in, but are thrown away by the XMPP client.

**Comment by juniorz** [comment]
As suspected, this is XEP-0085:

```
2015/10/23 14:25:00 -> Stanza &xmpp.ClientMessage{XMLName:xml.Name{Space:"jabber:client", Local:"message"}, From:"xxx@dukgo.com/xxx", ID:"purple412f173e", To:"strike-test@dukgo.com", Type:"chat", Subject:"", Body:"", Thread:"", Delay:(*xmpp.Delay)(nil),
Extension:[]xmpp.AnyHolder{xmpp.AnyHolder{XMLName:xml.Name{Space:"http://jabber.org/protocol/chatstates", Local:"composing"}, XML:""}}}

2015/10/23 14:25:03 -> Stanza &xmpp.ClientMessage{XMLName:xml.Name{Space:"jabber:client", Local:"message"}, From:"xxx@dukgo.com/xxx", ID:"purple412f173f", To:"strike-test@dukgo.com", Type:"chat", Subject:"", Body:"", Thread:"", Delay:(*xmpp.Delay)(nil),
Extension:[]xmpp.AnyHolder{xmpp.AnyHolder{XMLName:xml.Name{Space:"http://jabber.org/protocol/chatstates", Local:"paused"}, XML:""}}}
```

**Comment by olabini** [comment]
Nice find. Good that we understand this enough to make predictions on weird issues. ;D

**Comment by olabini** [comment]
This is handled by ignoring for now.
