### ISSUE TITLE
Rename contacts

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#86]

**Comment by juniorz** [comment]
Is there any reason for saving the custom contact name only locally and not saving on the server with a roster set IQ[1]? Is this on purpose?

1 - https://xmpp.org/rfcs/rfc6121.html#roster-syntax-actions-set

**Comment by olabini** [comment]
Yep, there is a reason. =D I wonder why it isn't in this ticket though - I thought I had added it. Anyway, the reason is I don't want to leak contact names to the server, at least not by default. That way people can feel more secure in what names they give people locally, without necessarily knowing the connection between a random afdfsgdf@sdfgsdfgdsf.onion and the name Ola.

**Comment by juniorz** [comment]
OK. It was not clear from the UI that this nickname is something local only. It would be useful to add this to the UI, so people can use it with a peaceful mind.

**Comment by juniorz** [comment]
Should the groups be also only local?

**Comment by olabini** [comment]
Yep, I think it actually does say so in #87 - or maybe it doesn't. Very strange. I'm pretty sure I had it in them originally.
