### ISSUE TITLE
Associate contacts with groups

### ISSUE THREAD

**Issue by olabini** [twstrike/coyim#87]
Similarly to #86 we want to have any identifiable information of a contact local only.

**Comment by juniorz** [comment]
I think we should unify the UI for this and #86 under an "Edit contact" menu item in the contact context menu. It would open a dialog where we could change everything related to a contact.

Initially, we have rename (by changing the nickname property) and add/remove group associations. In the future, we will have other contact-related setting in the same dialog, like fingerprints, encryption settings (`config.Account#AlwaysEncryptWith` and `config.Account#DontEncryptWith`).

btw, it seems we should move `config.Account#AlwaysEncryptWith` and `config.Account#DontEncryptWith` to `config.Peer`.

**Comment by olabini** [comment]
Yep, agree.

**Comment by iapazmino** [comment]
#86 is ready.

**Comment by juniorz** [comment]
Group association should be local only. Reopening.
