### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#9]
- Message support i18n
- UI support i18n (can be less?)

**Comment by olabini** [comment]
Probably necessary for user ids and nicknames etc at least. Probably also for explanations of complex things

**Comment by olabini** [comment]
#2 is a subtask of this one.

**Comment by juniorz** [comment]
I have started to investigate using `gettext` with `GtkBuilder` and it works as expected. I'm waiting gotk3/gotk3#38 to be merged.

**Comment by olabini** [comment]
I would argue this is done. Let's keep track of #36 in its own issue.
