### ISSUE TITLE
User Flow - Add contact - Display error

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#92]
If fails to subscript a contact we should display the error

![add_contact](https://cloud.githubusercontent.com/assets/1254745/10746807/9bac81d4-7c1c-11e5-9da9-bac15fe7f205.png)

**Comment by olabini** [comment]
I've added error information when you try to add a malformed JID, but there is no way of knowing whether a subscription failed or not.

**Comment by tdruiva** [comment]
:+1:
