### ISSUE TITLE
Visual information about encrypted chat

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#93]
As we require encryption by default, I think we only should mark the conversation as encrypted in some visual way

![start_security_chat](https://cloud.githubusercontent.com/assets/1254745/10747113/a5439252-7c1f-11e5-8876-d618540c3da1.png)

**Comment by juniorz** [comment]
#24 is related to this user flow.

**Comment by iapazmino** [comment]
Does #24 close this issue?
If not, should we get some help with the icon or icons we wish to display to visually show the conversation is insecure?

**Comment by olabini** [comment]
Nope it doesn't. And no, icons is not what I have in mind either.
