### ISSUE TITLE
User Flow - Start Security Chat - Notify if fingerprint is verified

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#95]
When user starts a conversation we should notify if the other person's fingerprint is virified

![start_security_chat](https://cloud.githubusercontent.com/assets/1254745/10747113/a5439252-7c1f-11e5-8876-d618540c3da1.png)

**Comment by juniorz** [comment]
We actually notify by not warning as we do in case the fingerprint is not verified (See #99). Is this enough?

**Comment by tdruiva** [comment]
I think so :+1:
