### ISSUE TITLE
User Flow - Connect Account - Check if Tor is running

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#96]
When user want to add a new account to CoyIm we need to check if Tor is running.
Otherwise CoyIm will leak their data.

If Tor is not running, notify user and wait it to be installed.

![connect_account](https://cloud.githubusercontent.com/assets/1254745/10747220/a8667b4c-7c20-11e5-9ded-ec9b9e03a9a1.png)

**Comment by tdruiva** [comment]
Should we check this before user to type the password?

**Comment by tdruiva** [comment]
Have a clear text/instruction of how to have Tor running.

This is our current window:

![screenshot from 2015-11-20 16-41-17](https://cloud.githubusercontent.com/assets/1254745/11312660/99983b44-8fa5-11e5-9912-45154957b811.png)

**Comment by olabini** [comment]
I don't think we can do this before the user manually tries to connect - doing anything else without user consent is probably a bad idea.
