### ISSUE TITLE
User Flow - Connect Account - Show error

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#97]
When user try to connect an account, CoyIm should display an error message if its fails

![connect_account](https://cloud.githubusercontent.com/assets/1254745/10747267/2a9e934c-7c21-11e5-93ee-d392c8765c20.png)

**Comment by tdruiva** [comment]
In our currently implementation, if we have problem with authentication we just ask for password again and don't explain what happened.

**Comment by tdruiva** [comment]
Notify if internet is not connected

**Comment by olabini** [comment]
We do give feedback on connection failure now, with the infobar.
