### ISSUE TITLE
User Flow - Verify Fingerprint - Warn user if fingerprint is not verified

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#99]
When user starts an conversation, if fingerprint is not verified we should notify it and ask to verify.

![verify_fpr](https://cloud.githubusercontent.com/assets/1254745/10747461/4f485a64-7c23-11e5-9e04-79f4351f1398.png)

**Comment by juniorz** [comment]
I suspect edc9b5f completes this flow, doesn't it?

**Comment by tdruiva** [comment]
Yes sir! \o/
